version: '2'
services:
  cas-server:
    scale: 2
    start_on_create: true
  cas-haproxy:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: cas-server
        source_port: 8090
        target_port: 8090
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
