package com.sstc.hmis.log.dbaccess.data;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OperationLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public OperationLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClIdIsNull() {
            addCriterion("cl_id is null");
            return (Criteria) this;
        }

        public Criteria andClIdIsNotNull() {
            addCriterion("cl_id is not null");
            return (Criteria) this;
        }

        public Criteria andClIdEqualTo(String value) {
            addCriterion("cl_id =", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotEqualTo(String value) {
            addCriterion("cl_id <>", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdGreaterThan(String value) {
            addCriterion("cl_id >", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdGreaterThanOrEqualTo(String value) {
            addCriterion("cl_id >=", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdLessThan(String value) {
            addCriterion("cl_id <", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdLessThanOrEqualTo(String value) {
            addCriterion("cl_id <=", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdLike(String value) {
            addCriterion("cl_id like", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotLike(String value) {
            addCriterion("cl_id not like", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdIn(List<String> values) {
            addCriterion("cl_id in", values, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotIn(List<String> values) {
            addCriterion("cl_id not in", values, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdBetween(String value1, String value2) {
            addCriterion("cl_id between", value1, value2, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotBetween(String value1, String value2) {
            addCriterion("cl_id not between", value1, value2, "clId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdIsNull() {
            addCriterion("cl_grp_id is null");
            return (Criteria) this;
        }

        public Criteria andClGrpIdIsNotNull() {
            addCriterion("cl_grp_id is not null");
            return (Criteria) this;
        }

        public Criteria andClGrpIdEqualTo(String value) {
            addCriterion("cl_grp_id =", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdNotEqualTo(String value) {
            addCriterion("cl_grp_id <>", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdGreaterThan(String value) {
            addCriterion("cl_grp_id >", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdGreaterThanOrEqualTo(String value) {
            addCriterion("cl_grp_id >=", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdLessThan(String value) {
            addCriterion("cl_grp_id <", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdLessThanOrEqualTo(String value) {
            addCriterion("cl_grp_id <=", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdLike(String value) {
            addCriterion("cl_grp_id like", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdNotLike(String value) {
            addCriterion("cl_grp_id not like", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdIn(List<String> values) {
            addCriterion("cl_grp_id in", values, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdNotIn(List<String> values) {
            addCriterion("cl_grp_id not in", values, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdBetween(String value1, String value2) {
            addCriterion("cl_grp_id between", value1, value2, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdNotBetween(String value1, String value2) {
            addCriterion("cl_grp_id not between", value1, value2, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdIsNull() {
            addCriterion("cl_hotel_id is null");
            return (Criteria) this;
        }

        public Criteria andClHotelIdIsNotNull() {
            addCriterion("cl_hotel_id is not null");
            return (Criteria) this;
        }

        public Criteria andClHotelIdEqualTo(String value) {
            addCriterion("cl_hotel_id =", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdNotEqualTo(String value) {
            addCriterion("cl_hotel_id <>", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdGreaterThan(String value) {
            addCriterion("cl_hotel_id >", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdGreaterThanOrEqualTo(String value) {
            addCriterion("cl_hotel_id >=", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdLessThan(String value) {
            addCriterion("cl_hotel_id <", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdLessThanOrEqualTo(String value) {
            addCriterion("cl_hotel_id <=", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdLike(String value) {
            addCriterion("cl_hotel_id like", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdNotLike(String value) {
            addCriterion("cl_hotel_id not like", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdIn(List<String> values) {
            addCriterion("cl_hotel_id in", values, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdNotIn(List<String> values) {
            addCriterion("cl_hotel_id not in", values, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdBetween(String value1, String value2) {
            addCriterion("cl_hotel_id between", value1, value2, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdNotBetween(String value1, String value2) {
            addCriterion("cl_hotel_id not between", value1, value2, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClClientIpIsNull() {
            addCriterion("cl_client_ip is null");
            return (Criteria) this;
        }

        public Criteria andClClientIpIsNotNull() {
            addCriterion("cl_client_ip is not null");
            return (Criteria) this;
        }

        public Criteria andClClientIpEqualTo(String value) {
            addCriterion("cl_client_ip =", value, "clClientIp");
            return (Criteria) this;
        }

        public Criteria andClClientIpNotEqualTo(String value) {
            addCriterion("cl_client_ip <>", value, "clClientIp");
            return (Criteria) this;
        }

        public Criteria andClClientIpGreaterThan(String value) {
            addCriterion("cl_client_ip >", value, "clClientIp");
            return (Criteria) this;
        }

        public Criteria andClClientIpGreaterThanOrEqualTo(String value) {
            addCriterion("cl_client_ip >=", value, "clClientIp");
            return (Criteria) this;
        }

        public Criteria andClClientIpLessThan(String value) {
            addCriterion("cl_client_ip <", value, "clClientIp");
            return (Criteria) this;
        }

        public Criteria andClClientIpLessThanOrEqualTo(String value) {
            addCriterion("cl_client_ip <=", value, "clClientIp");
            return (Criteria) this;
        }

        public Criteria andClClientIpLike(String value) {
            addCriterion("cl_client_ip like", value, "clClientIp");
            return (Criteria) this;
        }

        public Criteria andClClientIpNotLike(String value) {
            addCriterion("cl_client_ip not like", value, "clClientIp");
            return (Criteria) this;
        }

        public Criteria andClClientIpIn(List<String> values) {
            addCriterion("cl_client_ip in", values, "clClientIp");
            return (Criteria) this;
        }

        public Criteria andClClientIpNotIn(List<String> values) {
            addCriterion("cl_client_ip not in", values, "clClientIp");
            return (Criteria) this;
        }

        public Criteria andClClientIpBetween(String value1, String value2) {
            addCriterion("cl_client_ip between", value1, value2, "clClientIp");
            return (Criteria) this;
        }

        public Criteria andClClientIpNotBetween(String value1, String value2) {
            addCriterion("cl_client_ip not between", value1, value2, "clClientIp");
            return (Criteria) this;
        }

        public Criteria andClServerIpIsNull() {
            addCriterion("cl_server_ip is null");
            return (Criteria) this;
        }

        public Criteria andClServerIpIsNotNull() {
            addCriterion("cl_server_ip is not null");
            return (Criteria) this;
        }

        public Criteria andClServerIpEqualTo(String value) {
            addCriterion("cl_server_ip =", value, "clServerIp");
            return (Criteria) this;
        }

        public Criteria andClServerIpNotEqualTo(String value) {
            addCriterion("cl_server_ip <>", value, "clServerIp");
            return (Criteria) this;
        }

        public Criteria andClServerIpGreaterThan(String value) {
            addCriterion("cl_server_ip >", value, "clServerIp");
            return (Criteria) this;
        }

        public Criteria andClServerIpGreaterThanOrEqualTo(String value) {
            addCriterion("cl_server_ip >=", value, "clServerIp");
            return (Criteria) this;
        }

        public Criteria andClServerIpLessThan(String value) {
            addCriterion("cl_server_ip <", value, "clServerIp");
            return (Criteria) this;
        }

        public Criteria andClServerIpLessThanOrEqualTo(String value) {
            addCriterion("cl_server_ip <=", value, "clServerIp");
            return (Criteria) this;
        }

        public Criteria andClServerIpLike(String value) {
            addCriterion("cl_server_ip like", value, "clServerIp");
            return (Criteria) this;
        }

        public Criteria andClServerIpNotLike(String value) {
            addCriterion("cl_server_ip not like", value, "clServerIp");
            return (Criteria) this;
        }

        public Criteria andClServerIpIn(List<String> values) {
            addCriterion("cl_server_ip in", values, "clServerIp");
            return (Criteria) this;
        }

        public Criteria andClServerIpNotIn(List<String> values) {
            addCriterion("cl_server_ip not in", values, "clServerIp");
            return (Criteria) this;
        }

        public Criteria andClServerIpBetween(String value1, String value2) {
            addCriterion("cl_server_ip between", value1, value2, "clServerIp");
            return (Criteria) this;
        }

        public Criteria andClServerIpNotBetween(String value1, String value2) {
            addCriterion("cl_server_ip not between", value1, value2, "clServerIp");
            return (Criteria) this;
        }

        public Criteria andClBizDateIsNull() {
            addCriterion("cl_biz_date is null");
            return (Criteria) this;
        }

        public Criteria andClBizDateIsNotNull() {
            addCriterion("cl_biz_date is not null");
            return (Criteria) this;
        }

        public Criteria andClBizDateEqualTo(Date value) {
            addCriterion("cl_biz_date =", value, "clBizDate");
            return (Criteria) this;
        }

        public Criteria andClBizDateNotEqualTo(Date value) {
            addCriterion("cl_biz_date <>", value, "clBizDate");
            return (Criteria) this;
        }

        public Criteria andClBizDateGreaterThan(Date value) {
            addCriterion("cl_biz_date >", value, "clBizDate");
            return (Criteria) this;
        }

        public Criteria andClBizDateGreaterThanOrEqualTo(Date value) {
            addCriterion("cl_biz_date >=", value, "clBizDate");
            return (Criteria) this;
        }

        public Criteria andClBizDateLessThan(Date value) {
            addCriterion("cl_biz_date <", value, "clBizDate");
            return (Criteria) this;
        }

        public Criteria andClBizDateLessThanOrEqualTo(Date value) {
            addCriterion("cl_biz_date <=", value, "clBizDate");
            return (Criteria) this;
        }

        public Criteria andClBizDateIn(List<Date> values) {
            addCriterion("cl_biz_date in", values, "clBizDate");
            return (Criteria) this;
        }

        public Criteria andClBizDateNotIn(List<Date> values) {
            addCriterion("cl_biz_date not in", values, "clBizDate");
            return (Criteria) this;
        }

        public Criteria andClBizDateBetween(Date value1, Date value2) {
            addCriterion("cl_biz_date between", value1, value2, "clBizDate");
            return (Criteria) this;
        }

        public Criteria andClBizDateNotBetween(Date value1, Date value2) {
            addCriterion("cl_biz_date not between", value1, value2, "clBizDate");
            return (Criteria) this;
        }

        public Criteria andClSystemIsNull() {
            addCriterion("cl_system is null");
            return (Criteria) this;
        }

        public Criteria andClSystemIsNotNull() {
            addCriterion("cl_system is not null");
            return (Criteria) this;
        }

        public Criteria andClSystemEqualTo(String value) {
            addCriterion("cl_system =", value, "clSystem");
            return (Criteria) this;
        }

        public Criteria andClSystemNotEqualTo(String value) {
            addCriterion("cl_system <>", value, "clSystem");
            return (Criteria) this;
        }

        public Criteria andClSystemGreaterThan(String value) {
            addCriterion("cl_system >", value, "clSystem");
            return (Criteria) this;
        }

        public Criteria andClSystemGreaterThanOrEqualTo(String value) {
            addCriterion("cl_system >=", value, "clSystem");
            return (Criteria) this;
        }

        public Criteria andClSystemLessThan(String value) {
            addCriterion("cl_system <", value, "clSystem");
            return (Criteria) this;
        }

        public Criteria andClSystemLessThanOrEqualTo(String value) {
            addCriterion("cl_system <=", value, "clSystem");
            return (Criteria) this;
        }

        public Criteria andClSystemLike(String value) {
            addCriterion("cl_system like", value, "clSystem");
            return (Criteria) this;
        }

        public Criteria andClSystemNotLike(String value) {
            addCriterion("cl_system not like", value, "clSystem");
            return (Criteria) this;
        }

        public Criteria andClSystemIn(List<String> values) {
            addCriterion("cl_system in", values, "clSystem");
            return (Criteria) this;
        }

        public Criteria andClSystemNotIn(List<String> values) {
            addCriterion("cl_system not in", values, "clSystem");
            return (Criteria) this;
        }

        public Criteria andClSystemBetween(String value1, String value2) {
            addCriterion("cl_system between", value1, value2, "clSystem");
            return (Criteria) this;
        }

        public Criteria andClSystemNotBetween(String value1, String value2) {
            addCriterion("cl_system not between", value1, value2, "clSystem");
            return (Criteria) this;
        }

        public Criteria andClModularIsNull() {
            addCriterion("cl_modular is null");
            return (Criteria) this;
        }

        public Criteria andClModularIsNotNull() {
            addCriterion("cl_modular is not null");
            return (Criteria) this;
        }

        public Criteria andClModularEqualTo(String value) {
            addCriterion("cl_modular =", value, "clModular");
            return (Criteria) this;
        }

        public Criteria andClModularNotEqualTo(String value) {
            addCriterion("cl_modular <>", value, "clModular");
            return (Criteria) this;
        }

        public Criteria andClModularGreaterThan(String value) {
            addCriterion("cl_modular >", value, "clModular");
            return (Criteria) this;
        }

        public Criteria andClModularGreaterThanOrEqualTo(String value) {
            addCriterion("cl_modular >=", value, "clModular");
            return (Criteria) this;
        }

        public Criteria andClModularLessThan(String value) {
            addCriterion("cl_modular <", value, "clModular");
            return (Criteria) this;
        }

        public Criteria andClModularLessThanOrEqualTo(String value) {
            addCriterion("cl_modular <=", value, "clModular");
            return (Criteria) this;
        }

        public Criteria andClModularLike(String value) {
            addCriterion("cl_modular like", value, "clModular");
            return (Criteria) this;
        }

        public Criteria andClModularNotLike(String value) {
            addCriterion("cl_modular not like", value, "clModular");
            return (Criteria) this;
        }

        public Criteria andClModularIn(List<String> values) {
            addCriterion("cl_modular in", values, "clModular");
            return (Criteria) this;
        }

        public Criteria andClModularNotIn(List<String> values) {
            addCriterion("cl_modular not in", values, "clModular");
            return (Criteria) this;
        }

        public Criteria andClModularBetween(String value1, String value2) {
            addCriterion("cl_modular between", value1, value2, "clModular");
            return (Criteria) this;
        }

        public Criteria andClModularNotBetween(String value1, String value2) {
            addCriterion("cl_modular not between", value1, value2, "clModular");
            return (Criteria) this;
        }

        public Criteria andClFunIsNull() {
            addCriterion("cl_fun is null");
            return (Criteria) this;
        }

        public Criteria andClFunIsNotNull() {
            addCriterion("cl_fun is not null");
            return (Criteria) this;
        }

        public Criteria andClFunEqualTo(String value) {
            addCriterion("cl_fun =", value, "clFun");
            return (Criteria) this;
        }

        public Criteria andClFunNotEqualTo(String value) {
            addCriterion("cl_fun <>", value, "clFun");
            return (Criteria) this;
        }

        public Criteria andClFunGreaterThan(String value) {
            addCriterion("cl_fun >", value, "clFun");
            return (Criteria) this;
        }

        public Criteria andClFunGreaterThanOrEqualTo(String value) {
            addCriterion("cl_fun >=", value, "clFun");
            return (Criteria) this;
        }

        public Criteria andClFunLessThan(String value) {
            addCriterion("cl_fun <", value, "clFun");
            return (Criteria) this;
        }

        public Criteria andClFunLessThanOrEqualTo(String value) {
            addCriterion("cl_fun <=", value, "clFun");
            return (Criteria) this;
        }

        public Criteria andClFunLike(String value) {
            addCriterion("cl_fun like", value, "clFun");
            return (Criteria) this;
        }

        public Criteria andClFunNotLike(String value) {
            addCriterion("cl_fun not like", value, "clFun");
            return (Criteria) this;
        }

        public Criteria andClFunIn(List<String> values) {
            addCriterion("cl_fun in", values, "clFun");
            return (Criteria) this;
        }

        public Criteria andClFunNotIn(List<String> values) {
            addCriterion("cl_fun not in", values, "clFun");
            return (Criteria) this;
        }

        public Criteria andClFunBetween(String value1, String value2) {
            addCriterion("cl_fun between", value1, value2, "clFun");
            return (Criteria) this;
        }

        public Criteria andClFunNotBetween(String value1, String value2) {
            addCriterion("cl_fun not between", value1, value2, "clFun");
            return (Criteria) this;
        }

        public Criteria andClOperationIsNull() {
            addCriterion("cl_operation is null");
            return (Criteria) this;
        }

        public Criteria andClOperationIsNotNull() {
            addCriterion("cl_operation is not null");
            return (Criteria) this;
        }

        public Criteria andClOperationEqualTo(String value) {
            addCriterion("cl_operation =", value, "clOperation");
            return (Criteria) this;
        }

        public Criteria andClOperationNotEqualTo(String value) {
            addCriterion("cl_operation <>", value, "clOperation");
            return (Criteria) this;
        }

        public Criteria andClOperationGreaterThan(String value) {
            addCriterion("cl_operation >", value, "clOperation");
            return (Criteria) this;
        }

        public Criteria andClOperationGreaterThanOrEqualTo(String value) {
            addCriterion("cl_operation >=", value, "clOperation");
            return (Criteria) this;
        }

        public Criteria andClOperationLessThan(String value) {
            addCriterion("cl_operation <", value, "clOperation");
            return (Criteria) this;
        }

        public Criteria andClOperationLessThanOrEqualTo(String value) {
            addCriterion("cl_operation <=", value, "clOperation");
            return (Criteria) this;
        }

        public Criteria andClOperationLike(String value) {
            addCriterion("cl_operation like", value, "clOperation");
            return (Criteria) this;
        }

        public Criteria andClOperationNotLike(String value) {
            addCriterion("cl_operation not like", value, "clOperation");
            return (Criteria) this;
        }

        public Criteria andClOperationIn(List<String> values) {
            addCriterion("cl_operation in", values, "clOperation");
            return (Criteria) this;
        }

        public Criteria andClOperationNotIn(List<String> values) {
            addCriterion("cl_operation not in", values, "clOperation");
            return (Criteria) this;
        }

        public Criteria andClOperationBetween(String value1, String value2) {
            addCriterion("cl_operation between", value1, value2, "clOperation");
            return (Criteria) this;
        }

        public Criteria andClOperationNotBetween(String value1, String value2) {
            addCriterion("cl_operation not between", value1, value2, "clOperation");
            return (Criteria) this;
        }

        public Criteria andClAccnoIsNull() {
            addCriterion("cl_accno is null");
            return (Criteria) this;
        }

        public Criteria andClAccnoIsNotNull() {
            addCriterion("cl_accno is not null");
            return (Criteria) this;
        }

        public Criteria andClAccnoEqualTo(String value) {
            addCriterion("cl_accno =", value, "clAccno");
            return (Criteria) this;
        }

        public Criteria andClAccnoNotEqualTo(String value) {
            addCriterion("cl_accno <>", value, "clAccno");
            return (Criteria) this;
        }

        public Criteria andClAccnoGreaterThan(String value) {
            addCriterion("cl_accno >", value, "clAccno");
            return (Criteria) this;
        }

        public Criteria andClAccnoGreaterThanOrEqualTo(String value) {
            addCriterion("cl_accno >=", value, "clAccno");
            return (Criteria) this;
        }

        public Criteria andClAccnoLessThan(String value) {
            addCriterion("cl_accno <", value, "clAccno");
            return (Criteria) this;
        }

        public Criteria andClAccnoLessThanOrEqualTo(String value) {
            addCriterion("cl_accno <=", value, "clAccno");
            return (Criteria) this;
        }

        public Criteria andClAccnoLike(String value) {
            addCriterion("cl_accno like", value, "clAccno");
            return (Criteria) this;
        }

        public Criteria andClAccnoNotLike(String value) {
            addCriterion("cl_accno not like", value, "clAccno");
            return (Criteria) this;
        }

        public Criteria andClAccnoIn(List<String> values) {
            addCriterion("cl_accno in", values, "clAccno");
            return (Criteria) this;
        }

        public Criteria andClAccnoNotIn(List<String> values) {
            addCriterion("cl_accno not in", values, "clAccno");
            return (Criteria) this;
        }

        public Criteria andClAccnoBetween(String value1, String value2) {
            addCriterion("cl_accno between", value1, value2, "clAccno");
            return (Criteria) this;
        }

        public Criteria andClAccnoNotBetween(String value1, String value2) {
            addCriterion("cl_accno not between", value1, value2, "clAccno");
            return (Criteria) this;
        }

        public Criteria andClGroupnoIsNull() {
            addCriterion("cl_groupno is null");
            return (Criteria) this;
        }

        public Criteria andClGroupnoIsNotNull() {
            addCriterion("cl_groupno is not null");
            return (Criteria) this;
        }

        public Criteria andClGroupnoEqualTo(String value) {
            addCriterion("cl_groupno =", value, "clGroupno");
            return (Criteria) this;
        }

        public Criteria andClGroupnoNotEqualTo(String value) {
            addCriterion("cl_groupno <>", value, "clGroupno");
            return (Criteria) this;
        }

        public Criteria andClGroupnoGreaterThan(String value) {
            addCriterion("cl_groupno >", value, "clGroupno");
            return (Criteria) this;
        }

        public Criteria andClGroupnoGreaterThanOrEqualTo(String value) {
            addCriterion("cl_groupno >=", value, "clGroupno");
            return (Criteria) this;
        }

        public Criteria andClGroupnoLessThan(String value) {
            addCriterion("cl_groupno <", value, "clGroupno");
            return (Criteria) this;
        }

        public Criteria andClGroupnoLessThanOrEqualTo(String value) {
            addCriterion("cl_groupno <=", value, "clGroupno");
            return (Criteria) this;
        }

        public Criteria andClGroupnoLike(String value) {
            addCriterion("cl_groupno like", value, "clGroupno");
            return (Criteria) this;
        }

        public Criteria andClGroupnoNotLike(String value) {
            addCriterion("cl_groupno not like", value, "clGroupno");
            return (Criteria) this;
        }

        public Criteria andClGroupnoIn(List<String> values) {
            addCriterion("cl_groupno in", values, "clGroupno");
            return (Criteria) this;
        }

        public Criteria andClGroupnoNotIn(List<String> values) {
            addCriterion("cl_groupno not in", values, "clGroupno");
            return (Criteria) this;
        }

        public Criteria andClGroupnoBetween(String value1, String value2) {
            addCriterion("cl_groupno between", value1, value2, "clGroupno");
            return (Criteria) this;
        }

        public Criteria andClGroupnoNotBetween(String value1, String value2) {
            addCriterion("cl_groupno not between", value1, value2, "clGroupno");
            return (Criteria) this;
        }

        public Criteria andClPronoIsNull() {
            addCriterion("cl_prono is null");
            return (Criteria) this;
        }

        public Criteria andClPronoIsNotNull() {
            addCriterion("cl_prono is not null");
            return (Criteria) this;
        }

        public Criteria andClPronoEqualTo(String value) {
            addCriterion("cl_prono =", value, "clProno");
            return (Criteria) this;
        }

        public Criteria andClPronoNotEqualTo(String value) {
            addCriterion("cl_prono <>", value, "clProno");
            return (Criteria) this;
        }

        public Criteria andClPronoGreaterThan(String value) {
            addCriterion("cl_prono >", value, "clProno");
            return (Criteria) this;
        }

        public Criteria andClPronoGreaterThanOrEqualTo(String value) {
            addCriterion("cl_prono >=", value, "clProno");
            return (Criteria) this;
        }

        public Criteria andClPronoLessThan(String value) {
            addCriterion("cl_prono <", value, "clProno");
            return (Criteria) this;
        }

        public Criteria andClPronoLessThanOrEqualTo(String value) {
            addCriterion("cl_prono <=", value, "clProno");
            return (Criteria) this;
        }

        public Criteria andClPronoLike(String value) {
            addCriterion("cl_prono like", value, "clProno");
            return (Criteria) this;
        }

        public Criteria andClPronoNotLike(String value) {
            addCriterion("cl_prono not like", value, "clProno");
            return (Criteria) this;
        }

        public Criteria andClPronoIn(List<String> values) {
            addCriterion("cl_prono in", values, "clProno");
            return (Criteria) this;
        }

        public Criteria andClPronoNotIn(List<String> values) {
            addCriterion("cl_prono not in", values, "clProno");
            return (Criteria) this;
        }

        public Criteria andClPronoBetween(String value1, String value2) {
            addCriterion("cl_prono between", value1, value2, "clProno");
            return (Criteria) this;
        }

        public Criteria andClPronoNotBetween(String value1, String value2) {
            addCriterion("cl_prono not between", value1, value2, "clProno");
            return (Criteria) this;
        }

        public Criteria andClRsvnoIsNull() {
            addCriterion("cl_rsvno is null");
            return (Criteria) this;
        }

        public Criteria andClRsvnoIsNotNull() {
            addCriterion("cl_rsvno is not null");
            return (Criteria) this;
        }

        public Criteria andClRsvnoEqualTo(String value) {
            addCriterion("cl_rsvno =", value, "clRsvno");
            return (Criteria) this;
        }

        public Criteria andClRsvnoNotEqualTo(String value) {
            addCriterion("cl_rsvno <>", value, "clRsvno");
            return (Criteria) this;
        }

        public Criteria andClRsvnoGreaterThan(String value) {
            addCriterion("cl_rsvno >", value, "clRsvno");
            return (Criteria) this;
        }

        public Criteria andClRsvnoGreaterThanOrEqualTo(String value) {
            addCriterion("cl_rsvno >=", value, "clRsvno");
            return (Criteria) this;
        }

        public Criteria andClRsvnoLessThan(String value) {
            addCriterion("cl_rsvno <", value, "clRsvno");
            return (Criteria) this;
        }

        public Criteria andClRsvnoLessThanOrEqualTo(String value) {
            addCriterion("cl_rsvno <=", value, "clRsvno");
            return (Criteria) this;
        }

        public Criteria andClRsvnoLike(String value) {
            addCriterion("cl_rsvno like", value, "clRsvno");
            return (Criteria) this;
        }

        public Criteria andClRsvnoNotLike(String value) {
            addCriterion("cl_rsvno not like", value, "clRsvno");
            return (Criteria) this;
        }

        public Criteria andClRsvnoIn(List<String> values) {
            addCriterion("cl_rsvno in", values, "clRsvno");
            return (Criteria) this;
        }

        public Criteria andClRsvnoNotIn(List<String> values) {
            addCriterion("cl_rsvno not in", values, "clRsvno");
            return (Criteria) this;
        }

        public Criteria andClRsvnoBetween(String value1, String value2) {
            addCriterion("cl_rsvno between", value1, value2, "clRsvno");
            return (Criteria) this;
        }

        public Criteria andClRsvnoNotBetween(String value1, String value2) {
            addCriterion("cl_rsvno not between", value1, value2, "clRsvno");
            return (Criteria) this;
        }

        public Criteria andClRoomnoIsNull() {
            addCriterion("cl_roomno is null");
            return (Criteria) this;
        }

        public Criteria andClRoomnoIsNotNull() {
            addCriterion("cl_roomno is not null");
            return (Criteria) this;
        }

        public Criteria andClRoomnoEqualTo(Integer value) {
            addCriterion("cl_roomno =", value, "clRoomno");
            return (Criteria) this;
        }

        public Criteria andClRoomnoNotEqualTo(Integer value) {
            addCriterion("cl_roomno <>", value, "clRoomno");
            return (Criteria) this;
        }

        public Criteria andClRoomnoGreaterThan(Integer value) {
            addCriterion("cl_roomno >", value, "clRoomno");
            return (Criteria) this;
        }

        public Criteria andClRoomnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("cl_roomno >=", value, "clRoomno");
            return (Criteria) this;
        }

        public Criteria andClRoomnoLessThan(Integer value) {
            addCriterion("cl_roomno <", value, "clRoomno");
            return (Criteria) this;
        }

        public Criteria andClRoomnoLessThanOrEqualTo(Integer value) {
            addCriterion("cl_roomno <=", value, "clRoomno");
            return (Criteria) this;
        }

        public Criteria andClRoomnoIn(List<Integer> values) {
            addCriterion("cl_roomno in", values, "clRoomno");
            return (Criteria) this;
        }

        public Criteria andClRoomnoNotIn(List<Integer> values) {
            addCriterion("cl_roomno not in", values, "clRoomno");
            return (Criteria) this;
        }

        public Criteria andClRoomnoBetween(Integer value1, Integer value2) {
            addCriterion("cl_roomno between", value1, value2, "clRoomno");
            return (Criteria) this;
        }

        public Criteria andClRoomnoNotBetween(Integer value1, Integer value2) {
            addCriterion("cl_roomno not between", value1, value2, "clRoomno");
            return (Criteria) this;
        }

        public Criteria andClCodeIsNull() {
            addCriterion("cl_code is null");
            return (Criteria) this;
        }

        public Criteria andClCodeIsNotNull() {
            addCriterion("cl_code is not null");
            return (Criteria) this;
        }

        public Criteria andClCodeEqualTo(String value) {
            addCriterion("cl_code =", value, "clCode");
            return (Criteria) this;
        }

        public Criteria andClCodeNotEqualTo(String value) {
            addCriterion("cl_code <>", value, "clCode");
            return (Criteria) this;
        }

        public Criteria andClCodeGreaterThan(String value) {
            addCriterion("cl_code >", value, "clCode");
            return (Criteria) this;
        }

        public Criteria andClCodeGreaterThanOrEqualTo(String value) {
            addCriterion("cl_code >=", value, "clCode");
            return (Criteria) this;
        }

        public Criteria andClCodeLessThan(String value) {
            addCriterion("cl_code <", value, "clCode");
            return (Criteria) this;
        }

        public Criteria andClCodeLessThanOrEqualTo(String value) {
            addCriterion("cl_code <=", value, "clCode");
            return (Criteria) this;
        }

        public Criteria andClCodeLike(String value) {
            addCriterion("cl_code like", value, "clCode");
            return (Criteria) this;
        }

        public Criteria andClCodeNotLike(String value) {
            addCriterion("cl_code not like", value, "clCode");
            return (Criteria) this;
        }

        public Criteria andClCodeIn(List<String> values) {
            addCriterion("cl_code in", values, "clCode");
            return (Criteria) this;
        }

        public Criteria andClCodeNotIn(List<String> values) {
            addCriterion("cl_code not in", values, "clCode");
            return (Criteria) this;
        }

        public Criteria andClCodeBetween(String value1, String value2) {
            addCriterion("cl_code between", value1, value2, "clCode");
            return (Criteria) this;
        }

        public Criteria andClCodeNotBetween(String value1, String value2) {
            addCriterion("cl_code not between", value1, value2, "clCode");
            return (Criteria) this;
        }

        public Criteria andClBatchIsNull() {
            addCriterion("\" cl_batch\" is null");
            return (Criteria) this;
        }

        public Criteria andClBatchIsNotNull() {
            addCriterion("\" cl_batch\" is not null");
            return (Criteria) this;
        }

        public Criteria andClBatchEqualTo(String value) {
            addCriterion("\" cl_batch\" =", value, "clBatch");
            return (Criteria) this;
        }

        public Criteria andClBatchNotEqualTo(String value) {
            addCriterion("\" cl_batch\" <>", value, "clBatch");
            return (Criteria) this;
        }

        public Criteria andClBatchGreaterThan(String value) {
            addCriterion("\" cl_batch\" >", value, "clBatch");
            return (Criteria) this;
        }

        public Criteria andClBatchGreaterThanOrEqualTo(String value) {
            addCriterion("\" cl_batch\" >=", value, "clBatch");
            return (Criteria) this;
        }

        public Criteria andClBatchLessThan(String value) {
            addCriterion("\" cl_batch\" <", value, "clBatch");
            return (Criteria) this;
        }

        public Criteria andClBatchLessThanOrEqualTo(String value) {
            addCriterion("\" cl_batch\" <=", value, "clBatch");
            return (Criteria) this;
        }

        public Criteria andClBatchLike(String value) {
            addCriterion("\" cl_batch\" like", value, "clBatch");
            return (Criteria) this;
        }

        public Criteria andClBatchNotLike(String value) {
            addCriterion("\" cl_batch\" not like", value, "clBatch");
            return (Criteria) this;
        }

        public Criteria andClBatchIn(List<String> values) {
            addCriterion("\" cl_batch\" in", values, "clBatch");
            return (Criteria) this;
        }

        public Criteria andClBatchNotIn(List<String> values) {
            addCriterion("\" cl_batch\" not in", values, "clBatch");
            return (Criteria) this;
        }

        public Criteria andClBatchBetween(String value1, String value2) {
            addCriterion("\" cl_batch\" between", value1, value2, "clBatch");
            return (Criteria) this;
        }

        public Criteria andClBatchNotBetween(String value1, String value2) {
            addCriterion("\" cl_batch\" not between", value1, value2, "clBatch");
            return (Criteria) this;
        }

        public Criteria andClEditConIsNull() {
            addCriterion("cl_edit_con is null");
            return (Criteria) this;
        }

        public Criteria andClEditConIsNotNull() {
            addCriterion("cl_edit_con is not null");
            return (Criteria) this;
        }

        public Criteria andClEditConEqualTo(String value) {
            addCriterion("cl_edit_con =", value, "clEditCon");
            return (Criteria) this;
        }

        public Criteria andClEditConNotEqualTo(String value) {
            addCriterion("cl_edit_con <>", value, "clEditCon");
            return (Criteria) this;
        }

        public Criteria andClEditConGreaterThan(String value) {
            addCriterion("cl_edit_con >", value, "clEditCon");
            return (Criteria) this;
        }

        public Criteria andClEditConGreaterThanOrEqualTo(String value) {
            addCriterion("cl_edit_con >=", value, "clEditCon");
            return (Criteria) this;
        }

        public Criteria andClEditConLessThan(String value) {
            addCriterion("cl_edit_con <", value, "clEditCon");
            return (Criteria) this;
        }

        public Criteria andClEditConLessThanOrEqualTo(String value) {
            addCriterion("cl_edit_con <=", value, "clEditCon");
            return (Criteria) this;
        }

        public Criteria andClEditConLike(String value) {
            addCriterion("cl_edit_con like", value, "clEditCon");
            return (Criteria) this;
        }

        public Criteria andClEditConNotLike(String value) {
            addCriterion("cl_edit_con not like", value, "clEditCon");
            return (Criteria) this;
        }

        public Criteria andClEditConIn(List<String> values) {
            addCriterion("cl_edit_con in", values, "clEditCon");
            return (Criteria) this;
        }

        public Criteria andClEditConNotIn(List<String> values) {
            addCriterion("cl_edit_con not in", values, "clEditCon");
            return (Criteria) this;
        }

        public Criteria andClEditConBetween(String value1, String value2) {
            addCriterion("cl_edit_con between", value1, value2, "clEditCon");
            return (Criteria) this;
        }

        public Criteria andClEditConNotBetween(String value1, String value2) {
            addCriterion("cl_edit_con not between", value1, value2, "clEditCon");
            return (Criteria) this;
        }

        public Criteria andClBeforeEditIsNull() {
            addCriterion("cl_before_edit is null");
            return (Criteria) this;
        }

        public Criteria andClBeforeEditIsNotNull() {
            addCriterion("cl_before_edit is not null");
            return (Criteria) this;
        }

        public Criteria andClBeforeEditEqualTo(String value) {
            addCriterion("cl_before_edit =", value, "clBeforeEdit");
            return (Criteria) this;
        }

        public Criteria andClBeforeEditNotEqualTo(String value) {
            addCriterion("cl_before_edit <>", value, "clBeforeEdit");
            return (Criteria) this;
        }

        public Criteria andClBeforeEditGreaterThan(String value) {
            addCriterion("cl_before_edit >", value, "clBeforeEdit");
            return (Criteria) this;
        }

        public Criteria andClBeforeEditGreaterThanOrEqualTo(String value) {
            addCriterion("cl_before_edit >=", value, "clBeforeEdit");
            return (Criteria) this;
        }

        public Criteria andClBeforeEditLessThan(String value) {
            addCriterion("cl_before_edit <", value, "clBeforeEdit");
            return (Criteria) this;
        }

        public Criteria andClBeforeEditLessThanOrEqualTo(String value) {
            addCriterion("cl_before_edit <=", value, "clBeforeEdit");
            return (Criteria) this;
        }

        public Criteria andClBeforeEditLike(String value) {
            addCriterion("cl_before_edit like", value, "clBeforeEdit");
            return (Criteria) this;
        }

        public Criteria andClBeforeEditNotLike(String value) {
            addCriterion("cl_before_edit not like", value, "clBeforeEdit");
            return (Criteria) this;
        }

        public Criteria andClBeforeEditIn(List<String> values) {
            addCriterion("cl_before_edit in", values, "clBeforeEdit");
            return (Criteria) this;
        }

        public Criteria andClBeforeEditNotIn(List<String> values) {
            addCriterion("cl_before_edit not in", values, "clBeforeEdit");
            return (Criteria) this;
        }

        public Criteria andClBeforeEditBetween(String value1, String value2) {
            addCriterion("cl_before_edit between", value1, value2, "clBeforeEdit");
            return (Criteria) this;
        }

        public Criteria andClBeforeEditNotBetween(String value1, String value2) {
            addCriterion("cl_before_edit not between", value1, value2, "clBeforeEdit");
            return (Criteria) this;
        }

        public Criteria andClAfterEditIsNull() {
            addCriterion("cl_after_edit is null");
            return (Criteria) this;
        }

        public Criteria andClAfterEditIsNotNull() {
            addCriterion("cl_after_edit is not null");
            return (Criteria) this;
        }

        public Criteria andClAfterEditEqualTo(String value) {
            addCriterion("cl_after_edit =", value, "clAfterEdit");
            return (Criteria) this;
        }

        public Criteria andClAfterEditNotEqualTo(String value) {
            addCriterion("cl_after_edit <>", value, "clAfterEdit");
            return (Criteria) this;
        }

        public Criteria andClAfterEditGreaterThan(String value) {
            addCriterion("cl_after_edit >", value, "clAfterEdit");
            return (Criteria) this;
        }

        public Criteria andClAfterEditGreaterThanOrEqualTo(String value) {
            addCriterion("cl_after_edit >=", value, "clAfterEdit");
            return (Criteria) this;
        }

        public Criteria andClAfterEditLessThan(String value) {
            addCriterion("cl_after_edit <", value, "clAfterEdit");
            return (Criteria) this;
        }

        public Criteria andClAfterEditLessThanOrEqualTo(String value) {
            addCriterion("cl_after_edit <=", value, "clAfterEdit");
            return (Criteria) this;
        }

        public Criteria andClAfterEditLike(String value) {
            addCriterion("cl_after_edit like", value, "clAfterEdit");
            return (Criteria) this;
        }

        public Criteria andClAfterEditNotLike(String value) {
            addCriterion("cl_after_edit not like", value, "clAfterEdit");
            return (Criteria) this;
        }

        public Criteria andClAfterEditIn(List<String> values) {
            addCriterion("cl_after_edit in", values, "clAfterEdit");
            return (Criteria) this;
        }

        public Criteria andClAfterEditNotIn(List<String> values) {
            addCriterion("cl_after_edit not in", values, "clAfterEdit");
            return (Criteria) this;
        }

        public Criteria andClAfterEditBetween(String value1, String value2) {
            addCriterion("cl_after_edit between", value1, value2, "clAfterEdit");
            return (Criteria) this;
        }

        public Criteria andClAfterEditNotBetween(String value1, String value2) {
            addCriterion("cl_after_edit not between", value1, value2, "clAfterEdit");
            return (Criteria) this;
        }

        public Criteria andClBuildDateIsNull() {
            addCriterion("cl_build_date is null");
            return (Criteria) this;
        }

        public Criteria andClBuildDateIsNotNull() {
            addCriterion("cl_build_date is not null");
            return (Criteria) this;
        }

        public Criteria andClBuildDateEqualTo(Date value) {
            addCriterion("cl_build_date =", value, "clBuildDate");
            return (Criteria) this;
        }

        public Criteria andClBuildDateNotEqualTo(Date value) {
            addCriterion("cl_build_date <>", value, "clBuildDate");
            return (Criteria) this;
        }

        public Criteria andClBuildDateGreaterThan(Date value) {
            addCriterion("cl_build_date >", value, "clBuildDate");
            return (Criteria) this;
        }

        public Criteria andClBuildDateGreaterThanOrEqualTo(Date value) {
            addCriterion("cl_build_date >=", value, "clBuildDate");
            return (Criteria) this;
        }

        public Criteria andClBuildDateLessThan(Date value) {
            addCriterion("cl_build_date <", value, "clBuildDate");
            return (Criteria) this;
        }

        public Criteria andClBuildDateLessThanOrEqualTo(Date value) {
            addCriterion("cl_build_date <=", value, "clBuildDate");
            return (Criteria) this;
        }

        public Criteria andClBuildDateIn(List<Date> values) {
            addCriterion("cl_build_date in", values, "clBuildDate");
            return (Criteria) this;
        }

        public Criteria andClBuildDateNotIn(List<Date> values) {
            addCriterion("cl_build_date not in", values, "clBuildDate");
            return (Criteria) this;
        }

        public Criteria andClBuildDateBetween(Date value1, Date value2) {
            addCriterion("cl_build_date between", value1, value2, "clBuildDate");
            return (Criteria) this;
        }

        public Criteria andClBuildDateNotBetween(Date value1, Date value2) {
            addCriterion("cl_build_date not between", value1, value2, "clBuildDate");
            return (Criteria) this;
        }

        public Criteria andClCreateByIsNull() {
            addCriterion("cl_create_by is null");
            return (Criteria) this;
        }

        public Criteria andClCreateByIsNotNull() {
            addCriterion("cl_create_by is not null");
            return (Criteria) this;
        }

        public Criteria andClCreateByEqualTo(String value) {
            addCriterion("cl_create_by =", value, "clCreateBy");
            return (Criteria) this;
        }

        public Criteria andClCreateByNotEqualTo(String value) {
            addCriterion("cl_create_by <>", value, "clCreateBy");
            return (Criteria) this;
        }

        public Criteria andClCreateByGreaterThan(String value) {
            addCriterion("cl_create_by >", value, "clCreateBy");
            return (Criteria) this;
        }

        public Criteria andClCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("cl_create_by >=", value, "clCreateBy");
            return (Criteria) this;
        }

        public Criteria andClCreateByLessThan(String value) {
            addCriterion("cl_create_by <", value, "clCreateBy");
            return (Criteria) this;
        }

        public Criteria andClCreateByLessThanOrEqualTo(String value) {
            addCriterion("cl_create_by <=", value, "clCreateBy");
            return (Criteria) this;
        }

        public Criteria andClCreateByLike(String value) {
            addCriterion("cl_create_by like", value, "clCreateBy");
            return (Criteria) this;
        }

        public Criteria andClCreateByNotLike(String value) {
            addCriterion("cl_create_by not like", value, "clCreateBy");
            return (Criteria) this;
        }

        public Criteria andClCreateByIn(List<String> values) {
            addCriterion("cl_create_by in", values, "clCreateBy");
            return (Criteria) this;
        }

        public Criteria andClCreateByNotIn(List<String> values) {
            addCriterion("cl_create_by not in", values, "clCreateBy");
            return (Criteria) this;
        }

        public Criteria andClCreateByBetween(String value1, String value2) {
            addCriterion("cl_create_by between", value1, value2, "clCreateBy");
            return (Criteria) this;
        }

        public Criteria andClCreateByNotBetween(String value1, String value2) {
            addCriterion("cl_create_by not between", value1, value2, "clCreateBy");
            return (Criteria) this;
        }

        public Criteria andClOperationDateIsNull() {
            addCriterion("cl_operation_date is null");
            return (Criteria) this;
        }

        public Criteria andClOperationDateIsNotNull() {
            addCriterion("cl_operation_date is not null");
            return (Criteria) this;
        }

        public Criteria andClOperationDateEqualTo(Date value) {
            addCriterion("cl_operation_date =", value, "clOperationDate");
            return (Criteria) this;
        }

        public Criteria andClOperationDateNotEqualTo(Date value) {
            addCriterion("cl_operation_date <>", value, "clOperationDate");
            return (Criteria) this;
        }

        public Criteria andClOperationDateGreaterThan(Date value) {
            addCriterion("cl_operation_date >", value, "clOperationDate");
            return (Criteria) this;
        }

        public Criteria andClOperationDateGreaterThanOrEqualTo(Date value) {
            addCriterion("cl_operation_date >=", value, "clOperationDate");
            return (Criteria) this;
        }

        public Criteria andClOperationDateLessThan(Date value) {
            addCriterion("cl_operation_date <", value, "clOperationDate");
            return (Criteria) this;
        }

        public Criteria andClOperationDateLessThanOrEqualTo(Date value) {
            addCriterion("cl_operation_date <=", value, "clOperationDate");
            return (Criteria) this;
        }

        public Criteria andClOperationDateIn(List<Date> values) {
            addCriterion("cl_operation_date in", values, "clOperationDate");
            return (Criteria) this;
        }

        public Criteria andClOperationDateNotIn(List<Date> values) {
            addCriterion("cl_operation_date not in", values, "clOperationDate");
            return (Criteria) this;
        }

        public Criteria andClOperationDateBetween(Date value1, Date value2) {
            addCriterion("cl_operation_date between", value1, value2, "clOperationDate");
            return (Criteria) this;
        }

        public Criteria andClOperationDateNotBetween(Date value1, Date value2) {
            addCriterion("cl_operation_date not between", value1, value2, "clOperationDate");
            return (Criteria) this;
        }

        public Criteria andClTerminalIsNull() {
            addCriterion("cl_terminal is null");
            return (Criteria) this;
        }

        public Criteria andClTerminalIsNotNull() {
            addCriterion("cl_terminal is not null");
            return (Criteria) this;
        }

        public Criteria andClTerminalEqualTo(String value) {
            addCriterion("cl_terminal =", value, "clTerminal");
            return (Criteria) this;
        }

        public Criteria andClTerminalNotEqualTo(String value) {
            addCriterion("cl_terminal <>", value, "clTerminal");
            return (Criteria) this;
        }

        public Criteria andClTerminalGreaterThan(String value) {
            addCriterion("cl_terminal >", value, "clTerminal");
            return (Criteria) this;
        }

        public Criteria andClTerminalGreaterThanOrEqualTo(String value) {
            addCriterion("cl_terminal >=", value, "clTerminal");
            return (Criteria) this;
        }

        public Criteria andClTerminalLessThan(String value) {
            addCriterion("cl_terminal <", value, "clTerminal");
            return (Criteria) this;
        }

        public Criteria andClTerminalLessThanOrEqualTo(String value) {
            addCriterion("cl_terminal <=", value, "clTerminal");
            return (Criteria) this;
        }

        public Criteria andClTerminalLike(String value) {
            addCriterion("cl_terminal like", value, "clTerminal");
            return (Criteria) this;
        }

        public Criteria andClTerminalNotLike(String value) {
            addCriterion("cl_terminal not like", value, "clTerminal");
            return (Criteria) this;
        }

        public Criteria andClTerminalIn(List<String> values) {
            addCriterion("cl_terminal in", values, "clTerminal");
            return (Criteria) this;
        }

        public Criteria andClTerminalNotIn(List<String> values) {
            addCriterion("cl_terminal not in", values, "clTerminal");
            return (Criteria) this;
        }

        public Criteria andClTerminalBetween(String value1, String value2) {
            addCriterion("cl_terminal between", value1, value2, "clTerminal");
            return (Criteria) this;
        }

        public Criteria andClTerminalNotBetween(String value1, String value2) {
            addCriterion("cl_terminal not between", value1, value2, "clTerminal");
            return (Criteria) this;
        }

        public Criteria andClResultIsNull() {
            addCriterion("cl_result is null");
            return (Criteria) this;
        }

        public Criteria andClResultIsNotNull() {
            addCriterion("cl_result is not null");
            return (Criteria) this;
        }

        public Criteria andClResultEqualTo(Short value) {
            addCriterion("cl_result =", value, "clResult");
            return (Criteria) this;
        }

        public Criteria andClResultNotEqualTo(Short value) {
            addCriterion("cl_result <>", value, "clResult");
            return (Criteria) this;
        }

        public Criteria andClResultGreaterThan(Short value) {
            addCriterion("cl_result >", value, "clResult");
            return (Criteria) this;
        }

        public Criteria andClResultGreaterThanOrEqualTo(Short value) {
            addCriterion("cl_result >=", value, "clResult");
            return (Criteria) this;
        }

        public Criteria andClResultLessThan(Short value) {
            addCriterion("cl_result <", value, "clResult");
            return (Criteria) this;
        }

        public Criteria andClResultLessThanOrEqualTo(Short value) {
            addCriterion("cl_result <=", value, "clResult");
            return (Criteria) this;
        }

        public Criteria andClResultIn(List<Short> values) {
            addCriterion("cl_result in", values, "clResult");
            return (Criteria) this;
        }

        public Criteria andClResultNotIn(List<Short> values) {
            addCriterion("cl_result not in", values, "clResult");
            return (Criteria) this;
        }

        public Criteria andClResultBetween(Short value1, Short value2) {
            addCriterion("cl_result between", value1, value2, "clResult");
            return (Criteria) this;
        }

        public Criteria andClResultNotBetween(Short value1, Short value2) {
            addCriterion("cl_result not between", value1, value2, "clResult");
            return (Criteria) this;
        }

        public Criteria andClFrameIsNull() {
            addCriterion("cl_frame is null");
            return (Criteria) this;
        }

        public Criteria andClFrameIsNotNull() {
            addCriterion("cl_frame is not null");
            return (Criteria) this;
        }

        public Criteria andClFrameEqualTo(String value) {
            addCriterion("cl_frame =", value, "clFrame");
            return (Criteria) this;
        }

        public Criteria andClFrameNotEqualTo(String value) {
            addCriterion("cl_frame <>", value, "clFrame");
            return (Criteria) this;
        }

        public Criteria andClFrameGreaterThan(String value) {
            addCriterion("cl_frame >", value, "clFrame");
            return (Criteria) this;
        }

        public Criteria andClFrameGreaterThanOrEqualTo(String value) {
            addCriterion("cl_frame >=", value, "clFrame");
            return (Criteria) this;
        }

        public Criteria andClFrameLessThan(String value) {
            addCriterion("cl_frame <", value, "clFrame");
            return (Criteria) this;
        }

        public Criteria andClFrameLessThanOrEqualTo(String value) {
            addCriterion("cl_frame <=", value, "clFrame");
            return (Criteria) this;
        }

        public Criteria andClFrameLike(String value) {
            addCriterion("cl_frame like", value, "clFrame");
            return (Criteria) this;
        }

        public Criteria andClFrameNotLike(String value) {
            addCriterion("cl_frame not like", value, "clFrame");
            return (Criteria) this;
        }

        public Criteria andClFrameIn(List<String> values) {
            addCriterion("cl_frame in", values, "clFrame");
            return (Criteria) this;
        }

        public Criteria andClFrameNotIn(List<String> values) {
            addCriterion("cl_frame not in", values, "clFrame");
            return (Criteria) this;
        }

        public Criteria andClFrameBetween(String value1, String value2) {
            addCriterion("cl_frame between", value1, value2, "clFrame");
            return (Criteria) this;
        }

        public Criteria andClFrameNotBetween(String value1, String value2) {
            addCriterion("cl_frame not between", value1, value2, "clFrame");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 20 09:22:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table log.log_t_pms_cashier
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}