package com.sstc.hmis.log.dbaccess.data;

import java.util.Date;

public class OperationLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_id
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_grp_id
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clGrpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_hotel_id
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clHotelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_client_ip
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clClientIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_server_ip
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clServerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_biz_date
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private Date clBizDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_system
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_modular
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clModular;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_fun
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clFun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_operation
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clOperation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_accno
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clAccno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_groupno
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clGroupno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_prono
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clProno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_rsvno
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clRsvno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_roomno
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private Integer clRoomno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_code
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier. cl_batch
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clBatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_edit_con
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clEditCon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_before_edit
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clBeforeEdit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_after_edit
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clAfterEdit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_build_date
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private Date clBuildDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_create_by
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clCreateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_operation_date
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private Date clOperationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_terminal
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clTerminal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_result
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private Short clResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.log_t_pms_cashier.cl_frame
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    private String clFrame;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_id
     *
     * @return the value of log.log_t_pms_cashier.cl_id
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClId() {
        return clId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_id
     *
     * @param clId the value for log.log_t_pms_cashier.cl_id
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClId(String clId) {
        this.clId = clId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_grp_id
     *
     * @return the value of log.log_t_pms_cashier.cl_grp_id
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClGrpId() {
        return clGrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_grp_id
     *
     * @param clGrpId the value for log.log_t_pms_cashier.cl_grp_id
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClGrpId(String clGrpId) {
        this.clGrpId = clGrpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_hotel_id
     *
     * @return the value of log.log_t_pms_cashier.cl_hotel_id
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClHotelId() {
        return clHotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_hotel_id
     *
     * @param clHotelId the value for log.log_t_pms_cashier.cl_hotel_id
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClHotelId(String clHotelId) {
        this.clHotelId = clHotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_client_ip
     *
     * @return the value of log.log_t_pms_cashier.cl_client_ip
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClClientIp() {
        return clClientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_client_ip
     *
     * @param clClientIp the value for log.log_t_pms_cashier.cl_client_ip
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClClientIp(String clClientIp) {
        this.clClientIp = clClientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_server_ip
     *
     * @return the value of log.log_t_pms_cashier.cl_server_ip
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClServerIp() {
        return clServerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_server_ip
     *
     * @param clServerIp the value for log.log_t_pms_cashier.cl_server_ip
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClServerIp(String clServerIp) {
        this.clServerIp = clServerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_biz_date
     *
     * @return the value of log.log_t_pms_cashier.cl_biz_date
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public Date getClBizDate() {
        return clBizDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_biz_date
     *
     * @param clBizDate the value for log.log_t_pms_cashier.cl_biz_date
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClBizDate(Date clBizDate) {
        this.clBizDate = clBizDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_system
     *
     * @return the value of log.log_t_pms_cashier.cl_system
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClSystem() {
        return clSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_system
     *
     * @param clSystem the value for log.log_t_pms_cashier.cl_system
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClSystem(String clSystem) {
        this.clSystem = clSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_modular
     *
     * @return the value of log.log_t_pms_cashier.cl_modular
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClModular() {
        return clModular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_modular
     *
     * @param clModular the value for log.log_t_pms_cashier.cl_modular
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClModular(String clModular) {
        this.clModular = clModular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_fun
     *
     * @return the value of log.log_t_pms_cashier.cl_fun
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClFun() {
        return clFun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_fun
     *
     * @param clFun the value for log.log_t_pms_cashier.cl_fun
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClFun(String clFun) {
        this.clFun = clFun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_operation
     *
     * @return the value of log.log_t_pms_cashier.cl_operation
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClOperation() {
        return clOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_operation
     *
     * @param clOperation the value for log.log_t_pms_cashier.cl_operation
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClOperation(String clOperation) {
        this.clOperation = clOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_accno
     *
     * @return the value of log.log_t_pms_cashier.cl_accno
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClAccno() {
        return clAccno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_accno
     *
     * @param clAccno the value for log.log_t_pms_cashier.cl_accno
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClAccno(String clAccno) {
        this.clAccno = clAccno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_groupno
     *
     * @return the value of log.log_t_pms_cashier.cl_groupno
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClGroupno() {
        return clGroupno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_groupno
     *
     * @param clGroupno the value for log.log_t_pms_cashier.cl_groupno
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClGroupno(String clGroupno) {
        this.clGroupno = clGroupno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_prono
     *
     * @return the value of log.log_t_pms_cashier.cl_prono
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClProno() {
        return clProno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_prono
     *
     * @param clProno the value for log.log_t_pms_cashier.cl_prono
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClProno(String clProno) {
        this.clProno = clProno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_rsvno
     *
     * @return the value of log.log_t_pms_cashier.cl_rsvno
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClRsvno() {
        return clRsvno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_rsvno
     *
     * @param clRsvno the value for log.log_t_pms_cashier.cl_rsvno
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClRsvno(String clRsvno) {
        this.clRsvno = clRsvno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_roomno
     *
     * @return the value of log.log_t_pms_cashier.cl_roomno
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public Integer getClRoomno() {
        return clRoomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_roomno
     *
     * @param clRoomno the value for log.log_t_pms_cashier.cl_roomno
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClRoomno(Integer clRoomno) {
        this.clRoomno = clRoomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_code
     *
     * @return the value of log.log_t_pms_cashier.cl_code
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClCode() {
        return clCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_code
     *
     * @param clCode the value for log.log_t_pms_cashier.cl_code
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClCode(String clCode) {
        this.clCode = clCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier. cl_batch
     *
     * @return the value of log.log_t_pms_cashier. cl_batch
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClBatch() {
        return clBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier. cl_batch
     *
     * @param clBatch the value for log.log_t_pms_cashier. cl_batch
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClBatch(String clBatch) {
        this.clBatch = clBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_edit_con
     *
     * @return the value of log.log_t_pms_cashier.cl_edit_con
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClEditCon() {
        return clEditCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_edit_con
     *
     * @param clEditCon the value for log.log_t_pms_cashier.cl_edit_con
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClEditCon(String clEditCon) {
        this.clEditCon = clEditCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_before_edit
     *
     * @return the value of log.log_t_pms_cashier.cl_before_edit
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClBeforeEdit() {
        return clBeforeEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_before_edit
     *
     * @param clBeforeEdit the value for log.log_t_pms_cashier.cl_before_edit
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClBeforeEdit(String clBeforeEdit) {
        this.clBeforeEdit = clBeforeEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_after_edit
     *
     * @return the value of log.log_t_pms_cashier.cl_after_edit
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClAfterEdit() {
        return clAfterEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_after_edit
     *
     * @param clAfterEdit the value for log.log_t_pms_cashier.cl_after_edit
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClAfterEdit(String clAfterEdit) {
        this.clAfterEdit = clAfterEdit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_build_date
     *
     * @return the value of log.log_t_pms_cashier.cl_build_date
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public Date getClBuildDate() {
        return clBuildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_build_date
     *
     * @param clBuildDate the value for log.log_t_pms_cashier.cl_build_date
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClBuildDate(Date clBuildDate) {
        this.clBuildDate = clBuildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_create_by
     *
     * @return the value of log.log_t_pms_cashier.cl_create_by
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClCreateBy() {
        return clCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_create_by
     *
     * @param clCreateBy the value for log.log_t_pms_cashier.cl_create_by
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClCreateBy(String clCreateBy) {
        this.clCreateBy = clCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_operation_date
     *
     * @return the value of log.log_t_pms_cashier.cl_operation_date
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public Date getClOperationDate() {
        return clOperationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_operation_date
     *
     * @param clOperationDate the value for log.log_t_pms_cashier.cl_operation_date
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClOperationDate(Date clOperationDate) {
        this.clOperationDate = clOperationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_terminal
     *
     * @return the value of log.log_t_pms_cashier.cl_terminal
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClTerminal() {
        return clTerminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_terminal
     *
     * @param clTerminal the value for log.log_t_pms_cashier.cl_terminal
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClTerminal(String clTerminal) {
        this.clTerminal = clTerminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_result
     *
     * @return the value of log.log_t_pms_cashier.cl_result
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public Short getClResult() {
        return clResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_result
     *
     * @param clResult the value for log.log_t_pms_cashier.cl_result
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClResult(Short clResult) {
        this.clResult = clResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.log_t_pms_cashier.cl_frame
     *
     * @return the value of log.log_t_pms_cashier.cl_frame
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public String getClFrame() {
        return clFrame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.log_t_pms_cashier.cl_frame
     *
     * @param clFrame the value for log.log_t_pms_cashier.cl_frame
     *
     * @mbggenerated Fri Apr 20 09:22:13 CST 2018
     */
    public void setClFrame(String clFrame) {
        this.clFrame = clFrame;
    }
    
    private String clBeforeView ;
    
    private String clAfterView ;
    
    
    
    public String getClBeforeView() {
		return clBeforeView;
	}

	public void setClBeforeView(String clBeforeView) {
		this.clBeforeView = clBeforeView;
	}

	public String getClAfterView() {
		return clAfterView;
	}

	public void setClAfterView(String clAfterView) {
		this.clAfterView = clAfterView;
	}

	private String tableName ; // 表名
    
    private String startDate ;
    
    private String endDate ; 
    
    private String[] clAccnos ;
    
    private String[] clRoomnos ;
    
    private String[] clCreateBys;
    

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String[] getClAccnos() {
		return clAccnos;
	}

	public void setClAccnos(String[] clAccnos) {
		this.clAccnos = clAccnos;
	}

	public String[] getClRoomnos() {
		return clRoomnos;
	}

	public void setClRoomnos(String[] clRoomnos) {
		this.clRoomnos = clRoomnos;
	}

	public String[] getClCreateBys() {
		return clCreateBys;
	}

	public void setClCreateBys(String[] clCreateBys) {
		this.clCreateBys = clCreateBys;
	}

	
    
    
    
}