package com.sstc.hmis.notification.dbaccess.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.sstc.hmis.notification.dbaccess.data.PermsTNotice;
import com.sstc.hmis.notification.dbaccess.data.PermsTNoticeExample;

@Mapper
public interface PermsTNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    int countByExample(PermsTNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    int deleteByExample(PermsTNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    int deleteByPrimaryKey(String clId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    int insert(PermsTNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    int insertSelective(PermsTNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    List<PermsTNotice> selectByExample(PermsTNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    PermsTNotice selectByPrimaryKey(String clId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") PermsTNotice record, @Param("example") PermsTNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    int updateByExample(@Param("record") PermsTNotice record, @Param("example") PermsTNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    int updateByPrimaryKeySelective(PermsTNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    int updateByPrimaryKey(PermsTNotice record);
    
    List<PermsTNotice> selectNoticeList(PermsTNotice record);
    
    List<PermsTNotice> selectNoticeByCurrTime(@Param("nowDate") Date nowDate, @Param("status") short status, @Param("hotelId") String hotelId);
}