package com.sstc.hmis.notification.dbaccess.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.sstc.hmis.notification.dbaccess.data.PermsTNoticeAccount;
import com.sstc.hmis.notification.dbaccess.data.PermsTNoticeAccountExample;

@Mapper
public interface PermsTNoticeAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_account
     *
     * @mbggenerated Wed May 09 16:17:03 CST 2018
     */
    int countByExample(PermsTNoticeAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_account
     *
     * @mbggenerated Wed May 09 16:17:03 CST 2018
     */
    int deleteByExample(PermsTNoticeAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_account
     *
     * @mbggenerated Wed May 09 16:17:03 CST 2018
     */
    int deleteByPrimaryKey(String clId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_account
     *
     * @mbggenerated Wed May 09 16:17:03 CST 2018
     */
    int insert(PermsTNoticeAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_account
     *
     * @mbggenerated Wed May 09 16:17:03 CST 2018
     */
    int insertSelective(PermsTNoticeAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_account
     *
     * @mbggenerated Wed May 09 16:17:03 CST 2018
     */
    List<PermsTNoticeAccount> selectByExample(PermsTNoticeAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_account
     *
     * @mbggenerated Wed May 09 16:17:03 CST 2018
     */
    PermsTNoticeAccount selectByPrimaryKey(String clId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_account
     *
     * @mbggenerated Wed May 09 16:17:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") PermsTNoticeAccount record, @Param("example") PermsTNoticeAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_account
     *
     * @mbggenerated Wed May 09 16:17:03 CST 2018
     */
    int updateByExample(@Param("record") PermsTNoticeAccount record, @Param("example") PermsTNoticeAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_account
     *
     * @mbggenerated Wed May 09 16:17:03 CST 2018
     */
    int updateByPrimaryKeySelective(PermsTNoticeAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_account
     *
     * @mbggenerated Wed May 09 16:17:03 CST 2018
     */
    int updateByPrimaryKey(PermsTNoticeAccount record);
}