package com.sstc.hmis.notification.dbaccess.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.sstc.hmis.notification.dbaccess.data.PermsTNoticeReceipt;
import com.sstc.hmis.notification.dbaccess.data.PermsTNoticeReceiptExample;

@Mapper
public interface PermsTNoticeReceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_receipt
     *
     * @mbggenerated Wed May 09 16:16:49 CST 2018
     */
    int countByExample(PermsTNoticeReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_receipt
     *
     * @mbggenerated Wed May 09 16:16:49 CST 2018
     */
    int deleteByExample(PermsTNoticeReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_receipt
     *
     * @mbggenerated Wed May 09 16:16:49 CST 2018
     */
    int deleteByPrimaryKey(String clId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_receipt
     *
     * @mbggenerated Wed May 09 16:16:49 CST 2018
     */
    int insert(PermsTNoticeReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_receipt
     *
     * @mbggenerated Wed May 09 16:16:49 CST 2018
     */
    int insertSelective(PermsTNoticeReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_receipt
     *
     * @mbggenerated Wed May 09 16:16:49 CST 2018
     */
    List<PermsTNoticeReceipt> selectByExample(PermsTNoticeReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_receipt
     *
     * @mbggenerated Wed May 09 16:16:49 CST 2018
     */
    PermsTNoticeReceipt selectByPrimaryKey(String clId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_receipt
     *
     * @mbggenerated Wed May 09 16:16:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") PermsTNoticeReceipt record, @Param("example") PermsTNoticeReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_receipt
     *
     * @mbggenerated Wed May 09 16:16:49 CST 2018
     */
    int updateByExample(@Param("record") PermsTNoticeReceipt record, @Param("example") PermsTNoticeReceiptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_receipt
     *
     * @mbggenerated Wed May 09 16:16:49 CST 2018
     */
    int updateByPrimaryKeySelective(PermsTNoticeReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice_receipt
     *
     * @mbggenerated Wed May 09 16:16:49 CST 2018
     */
    int updateByPrimaryKey(PermsTNoticeReceipt record);
    
    List<PermsTNoticeReceipt> selectNoticeReceiptList(@Param("startDate") Date startDate, @Param("endDate") Date endDate, @Param("hotelId") String hotelId, @Param("text") String text);
}