package com.sstc.hmis.notification.dbaccess.data;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PermsTNoticeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    public PermsTNoticeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClIdIsNull() {
            addCriterion("cl_id is null");
            return (Criteria) this;
        }

        public Criteria andClIdIsNotNull() {
            addCriterion("cl_id is not null");
            return (Criteria) this;
        }

        public Criteria andClIdEqualTo(String value) {
            addCriterion("cl_id =", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotEqualTo(String value) {
            addCriterion("cl_id <>", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdGreaterThan(String value) {
            addCriterion("cl_id >", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdGreaterThanOrEqualTo(String value) {
            addCriterion("cl_id >=", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdLessThan(String value) {
            addCriterion("cl_id <", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdLessThanOrEqualTo(String value) {
            addCriterion("cl_id <=", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdLike(String value) {
            addCriterion("cl_id like", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotLike(String value) {
            addCriterion("cl_id not like", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdIn(List<String> values) {
            addCriterion("cl_id in", values, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotIn(List<String> values) {
            addCriterion("cl_id not in", values, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdBetween(String value1, String value2) {
            addCriterion("cl_id between", value1, value2, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotBetween(String value1, String value2) {
            addCriterion("cl_id not between", value1, value2, "clId");
            return (Criteria) this;
        }

        public Criteria andClTitleIsNull() {
            addCriterion("cl_title is null");
            return (Criteria) this;
        }

        public Criteria andClTitleIsNotNull() {
            addCriterion("cl_title is not null");
            return (Criteria) this;
        }

        public Criteria andClTitleEqualTo(String value) {
            addCriterion("cl_title =", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleNotEqualTo(String value) {
            addCriterion("cl_title <>", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleGreaterThan(String value) {
            addCriterion("cl_title >", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleGreaterThanOrEqualTo(String value) {
            addCriterion("cl_title >=", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleLessThan(String value) {
            addCriterion("cl_title <", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleLessThanOrEqualTo(String value) {
            addCriterion("cl_title <=", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleLike(String value) {
            addCriterion("cl_title like", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleNotLike(String value) {
            addCriterion("cl_title not like", value, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleIn(List<String> values) {
            addCriterion("cl_title in", values, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleNotIn(List<String> values) {
            addCriterion("cl_title not in", values, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleBetween(String value1, String value2) {
            addCriterion("cl_title between", value1, value2, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClTitleNotBetween(String value1, String value2) {
            addCriterion("cl_title not between", value1, value2, "clTitle");
            return (Criteria) this;
        }

        public Criteria andClSummaryIsNull() {
            addCriterion("cl_summary is null");
            return (Criteria) this;
        }

        public Criteria andClSummaryIsNotNull() {
            addCriterion("cl_summary is not null");
            return (Criteria) this;
        }

        public Criteria andClSummaryEqualTo(String value) {
            addCriterion("cl_summary =", value, "clSummary");
            return (Criteria) this;
        }

        public Criteria andClSummaryNotEqualTo(String value) {
            addCriterion("cl_summary <>", value, "clSummary");
            return (Criteria) this;
        }

        public Criteria andClSummaryGreaterThan(String value) {
            addCriterion("cl_summary >", value, "clSummary");
            return (Criteria) this;
        }

        public Criteria andClSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("cl_summary >=", value, "clSummary");
            return (Criteria) this;
        }

        public Criteria andClSummaryLessThan(String value) {
            addCriterion("cl_summary <", value, "clSummary");
            return (Criteria) this;
        }

        public Criteria andClSummaryLessThanOrEqualTo(String value) {
            addCriterion("cl_summary <=", value, "clSummary");
            return (Criteria) this;
        }

        public Criteria andClSummaryLike(String value) {
            addCriterion("cl_summary like", value, "clSummary");
            return (Criteria) this;
        }

        public Criteria andClSummaryNotLike(String value) {
            addCriterion("cl_summary not like", value, "clSummary");
            return (Criteria) this;
        }

        public Criteria andClSummaryIn(List<String> values) {
            addCriterion("cl_summary in", values, "clSummary");
            return (Criteria) this;
        }

        public Criteria andClSummaryNotIn(List<String> values) {
            addCriterion("cl_summary not in", values, "clSummary");
            return (Criteria) this;
        }

        public Criteria andClSummaryBetween(String value1, String value2) {
            addCriterion("cl_summary between", value1, value2, "clSummary");
            return (Criteria) this;
        }

        public Criteria andClSummaryNotBetween(String value1, String value2) {
            addCriterion("cl_summary not between", value1, value2, "clSummary");
            return (Criteria) this;
        }

        public Criteria andClDetailIsNull() {
            addCriterion("cl_detail is null");
            return (Criteria) this;
        }

        public Criteria andClDetailIsNotNull() {
            addCriterion("cl_detail is not null");
            return (Criteria) this;
        }

        public Criteria andClDetailEqualTo(String value) {
            addCriterion("cl_detail =", value, "clDetail");
            return (Criteria) this;
        }

        public Criteria andClDetailNotEqualTo(String value) {
            addCriterion("cl_detail <>", value, "clDetail");
            return (Criteria) this;
        }

        public Criteria andClDetailGreaterThan(String value) {
            addCriterion("cl_detail >", value, "clDetail");
            return (Criteria) this;
        }

        public Criteria andClDetailGreaterThanOrEqualTo(String value) {
            addCriterion("cl_detail >=", value, "clDetail");
            return (Criteria) this;
        }

        public Criteria andClDetailLessThan(String value) {
            addCriterion("cl_detail <", value, "clDetail");
            return (Criteria) this;
        }

        public Criteria andClDetailLessThanOrEqualTo(String value) {
            addCriterion("cl_detail <=", value, "clDetail");
            return (Criteria) this;
        }

        public Criteria andClDetailLike(String value) {
            addCriterion("cl_detail like", value, "clDetail");
            return (Criteria) this;
        }

        public Criteria andClDetailNotLike(String value) {
            addCriterion("cl_detail not like", value, "clDetail");
            return (Criteria) this;
        }

        public Criteria andClDetailIn(List<String> values) {
            addCriterion("cl_detail in", values, "clDetail");
            return (Criteria) this;
        }

        public Criteria andClDetailNotIn(List<String> values) {
            addCriterion("cl_detail not in", values, "clDetail");
            return (Criteria) this;
        }

        public Criteria andClDetailBetween(String value1, String value2) {
            addCriterion("cl_detail between", value1, value2, "clDetail");
            return (Criteria) this;
        }

        public Criteria andClDetailNotBetween(String value1, String value2) {
            addCriterion("cl_detail not between", value1, value2, "clDetail");
            return (Criteria) this;
        }

        public Criteria andClTypeIsNull() {
            addCriterion("cl_type is null");
            return (Criteria) this;
        }

        public Criteria andClTypeIsNotNull() {
            addCriterion("cl_type is not null");
            return (Criteria) this;
        }

        public Criteria andClTypeEqualTo(String value) {
            addCriterion("cl_type =", value, "clType");
            return (Criteria) this;
        }

        public Criteria andClTypeNotEqualTo(String value) {
            addCriterion("cl_type <>", value, "clType");
            return (Criteria) this;
        }

        public Criteria andClTypeGreaterThan(String value) {
            addCriterion("cl_type >", value, "clType");
            return (Criteria) this;
        }

        public Criteria andClTypeGreaterThanOrEqualTo(String value) {
            addCriterion("cl_type >=", value, "clType");
            return (Criteria) this;
        }

        public Criteria andClTypeLessThan(String value) {
            addCriterion("cl_type <", value, "clType");
            return (Criteria) this;
        }

        public Criteria andClTypeLessThanOrEqualTo(String value) {
            addCriterion("cl_type <=", value, "clType");
            return (Criteria) this;
        }

        public Criteria andClTypeLike(String value) {
            addCriterion("cl_type like", value, "clType");
            return (Criteria) this;
        }

        public Criteria andClTypeNotLike(String value) {
            addCriterion("cl_type not like", value, "clType");
            return (Criteria) this;
        }

        public Criteria andClTypeIn(List<String> values) {
            addCriterion("cl_type in", values, "clType");
            return (Criteria) this;
        }

        public Criteria andClTypeNotIn(List<String> values) {
            addCriterion("cl_type not in", values, "clType");
            return (Criteria) this;
        }

        public Criteria andClTypeBetween(String value1, String value2) {
            addCriterion("cl_type between", value1, value2, "clType");
            return (Criteria) this;
        }

        public Criteria andClTypeNotBetween(String value1, String value2) {
            addCriterion("cl_type not between", value1, value2, "clType");
            return (Criteria) this;
        }

        public Criteria andClValidStarttimeIsNull() {
            addCriterion("cl_valid_starttime is null");
            return (Criteria) this;
        }

        public Criteria andClValidStarttimeIsNotNull() {
            addCriterion("cl_valid_starttime is not null");
            return (Criteria) this;
        }

        public Criteria andClValidStarttimeEqualTo(Date value) {
            addCriterion("cl_valid_starttime =", value, "clValidStarttime");
            return (Criteria) this;
        }

        public Criteria andClValidStarttimeNotEqualTo(Date value) {
            addCriterion("cl_valid_starttime <>", value, "clValidStarttime");
            return (Criteria) this;
        }

        public Criteria andClValidStarttimeGreaterThan(Date value) {
            addCriterion("cl_valid_starttime >", value, "clValidStarttime");
            return (Criteria) this;
        }

        public Criteria andClValidStarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cl_valid_starttime >=", value, "clValidStarttime");
            return (Criteria) this;
        }

        public Criteria andClValidStarttimeLessThan(Date value) {
            addCriterion("cl_valid_starttime <", value, "clValidStarttime");
            return (Criteria) this;
        }

        public Criteria andClValidStarttimeLessThanOrEqualTo(Date value) {
            addCriterion("cl_valid_starttime <=", value, "clValidStarttime");
            return (Criteria) this;
        }

        public Criteria andClValidStarttimeIn(List<Date> values) {
            addCriterion("cl_valid_starttime in", values, "clValidStarttime");
            return (Criteria) this;
        }

        public Criteria andClValidStarttimeNotIn(List<Date> values) {
            addCriterion("cl_valid_starttime not in", values, "clValidStarttime");
            return (Criteria) this;
        }

        public Criteria andClValidStarttimeBetween(Date value1, Date value2) {
            addCriterion("cl_valid_starttime between", value1, value2, "clValidStarttime");
            return (Criteria) this;
        }

        public Criteria andClValidStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("cl_valid_starttime not between", value1, value2, "clValidStarttime");
            return (Criteria) this;
        }

        public Criteria andClValidEndtimeIsNull() {
            addCriterion("cl_valid_endtime is null");
            return (Criteria) this;
        }

        public Criteria andClValidEndtimeIsNotNull() {
            addCriterion("cl_valid_endtime is not null");
            return (Criteria) this;
        }

        public Criteria andClValidEndtimeEqualTo(Date value) {
            addCriterion("cl_valid_endtime =", value, "clValidEndtime");
            return (Criteria) this;
        }

        public Criteria andClValidEndtimeNotEqualTo(Date value) {
            addCriterion("cl_valid_endtime <>", value, "clValidEndtime");
            return (Criteria) this;
        }

        public Criteria andClValidEndtimeGreaterThan(Date value) {
            addCriterion("cl_valid_endtime >", value, "clValidEndtime");
            return (Criteria) this;
        }

        public Criteria andClValidEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cl_valid_endtime >=", value, "clValidEndtime");
            return (Criteria) this;
        }

        public Criteria andClValidEndtimeLessThan(Date value) {
            addCriterion("cl_valid_endtime <", value, "clValidEndtime");
            return (Criteria) this;
        }

        public Criteria andClValidEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("cl_valid_endtime <=", value, "clValidEndtime");
            return (Criteria) this;
        }

        public Criteria andClValidEndtimeIn(List<Date> values) {
            addCriterion("cl_valid_endtime in", values, "clValidEndtime");
            return (Criteria) this;
        }

        public Criteria andClValidEndtimeNotIn(List<Date> values) {
            addCriterion("cl_valid_endtime not in", values, "clValidEndtime");
            return (Criteria) this;
        }

        public Criteria andClValidEndtimeBetween(Date value1, Date value2) {
            addCriterion("cl_valid_endtime between", value1, value2, "clValidEndtime");
            return (Criteria) this;
        }

        public Criteria andClValidEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("cl_valid_endtime not between", value1, value2, "clValidEndtime");
            return (Criteria) this;
        }

        public Criteria andClPublisherIsNull() {
            addCriterion("cl_publisher is null");
            return (Criteria) this;
        }

        public Criteria andClPublisherIsNotNull() {
            addCriterion("cl_publisher is not null");
            return (Criteria) this;
        }

        public Criteria andClPublisherEqualTo(String value) {
            addCriterion("cl_publisher =", value, "clPublisher");
            return (Criteria) this;
        }

        public Criteria andClPublisherNotEqualTo(String value) {
            addCriterion("cl_publisher <>", value, "clPublisher");
            return (Criteria) this;
        }

        public Criteria andClPublisherGreaterThan(String value) {
            addCriterion("cl_publisher >", value, "clPublisher");
            return (Criteria) this;
        }

        public Criteria andClPublisherGreaterThanOrEqualTo(String value) {
            addCriterion("cl_publisher >=", value, "clPublisher");
            return (Criteria) this;
        }

        public Criteria andClPublisherLessThan(String value) {
            addCriterion("cl_publisher <", value, "clPublisher");
            return (Criteria) this;
        }

        public Criteria andClPublisherLessThanOrEqualTo(String value) {
            addCriterion("cl_publisher <=", value, "clPublisher");
            return (Criteria) this;
        }

        public Criteria andClPublisherLike(String value) {
            addCriterion("cl_publisher like", value, "clPublisher");
            return (Criteria) this;
        }

        public Criteria andClPublisherNotLike(String value) {
            addCriterion("cl_publisher not like", value, "clPublisher");
            return (Criteria) this;
        }

        public Criteria andClPublisherIn(List<String> values) {
            addCriterion("cl_publisher in", values, "clPublisher");
            return (Criteria) this;
        }

        public Criteria andClPublisherNotIn(List<String> values) {
            addCriterion("cl_publisher not in", values, "clPublisher");
            return (Criteria) this;
        }

        public Criteria andClPublisherBetween(String value1, String value2) {
            addCriterion("cl_publisher between", value1, value2, "clPublisher");
            return (Criteria) this;
        }

        public Criteria andClPublisherNotBetween(String value1, String value2) {
            addCriterion("cl_publisher not between", value1, value2, "clPublisher");
            return (Criteria) this;
        }

        public Criteria andClPublisherIdIsNull() {
            addCriterion("cl_publisher_id is null");
            return (Criteria) this;
        }

        public Criteria andClPublisherIdIsNotNull() {
            addCriterion("cl_publisher_id is not null");
            return (Criteria) this;
        }

        public Criteria andClPublisherIdEqualTo(String value) {
            addCriterion("cl_publisher_id =", value, "clPublisherId");
            return (Criteria) this;
        }

        public Criteria andClPublisherIdNotEqualTo(String value) {
            addCriterion("cl_publisher_id <>", value, "clPublisherId");
            return (Criteria) this;
        }

        public Criteria andClPublisherIdGreaterThan(String value) {
            addCriterion("cl_publisher_id >", value, "clPublisherId");
            return (Criteria) this;
        }

        public Criteria andClPublisherIdGreaterThanOrEqualTo(String value) {
            addCriterion("cl_publisher_id >=", value, "clPublisherId");
            return (Criteria) this;
        }

        public Criteria andClPublisherIdLessThan(String value) {
            addCriterion("cl_publisher_id <", value, "clPublisherId");
            return (Criteria) this;
        }

        public Criteria andClPublisherIdLessThanOrEqualTo(String value) {
            addCriterion("cl_publisher_id <=", value, "clPublisherId");
            return (Criteria) this;
        }

        public Criteria andClPublisherIdLike(String value) {
            addCriterion("cl_publisher_id like", value, "clPublisherId");
            return (Criteria) this;
        }

        public Criteria andClPublisherIdNotLike(String value) {
            addCriterion("cl_publisher_id not like", value, "clPublisherId");
            return (Criteria) this;
        }

        public Criteria andClPublisherIdIn(List<String> values) {
            addCriterion("cl_publisher_id in", values, "clPublisherId");
            return (Criteria) this;
        }

        public Criteria andClPublisherIdNotIn(List<String> values) {
            addCriterion("cl_publisher_id not in", values, "clPublisherId");
            return (Criteria) this;
        }

        public Criteria andClPublisherIdBetween(String value1, String value2) {
            addCriterion("cl_publisher_id between", value1, value2, "clPublisherId");
            return (Criteria) this;
        }

        public Criteria andClPublisherIdNotBetween(String value1, String value2) {
            addCriterion("cl_publisher_id not between", value1, value2, "clPublisherId");
            return (Criteria) this;
        }

        public Criteria andClPublishStatusIsNull() {
            addCriterion("cl_publish_status is null");
            return (Criteria) this;
        }

        public Criteria andClPublishStatusIsNotNull() {
            addCriterion("cl_publish_status is not null");
            return (Criteria) this;
        }

        public Criteria andClPublishStatusEqualTo(Short value) {
            addCriterion("cl_publish_status =", value, "clPublishStatus");
            return (Criteria) this;
        }

        public Criteria andClPublishStatusNotEqualTo(Short value) {
            addCriterion("cl_publish_status <>", value, "clPublishStatus");
            return (Criteria) this;
        }

        public Criteria andClPublishStatusGreaterThan(Short value) {
            addCriterion("cl_publish_status >", value, "clPublishStatus");
            return (Criteria) this;
        }

        public Criteria andClPublishStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("cl_publish_status >=", value, "clPublishStatus");
            return (Criteria) this;
        }

        public Criteria andClPublishStatusLessThan(Short value) {
            addCriterion("cl_publish_status <", value, "clPublishStatus");
            return (Criteria) this;
        }

        public Criteria andClPublishStatusLessThanOrEqualTo(Short value) {
            addCriterion("cl_publish_status <=", value, "clPublishStatus");
            return (Criteria) this;
        }

        public Criteria andClPublishStatusIn(List<Short> values) {
            addCriterion("cl_publish_status in", values, "clPublishStatus");
            return (Criteria) this;
        }

        public Criteria andClPublishStatusNotIn(List<Short> values) {
            addCriterion("cl_publish_status not in", values, "clPublishStatus");
            return (Criteria) this;
        }

        public Criteria andClPublishStatusBetween(Short value1, Short value2) {
            addCriterion("cl_publish_status between", value1, value2, "clPublishStatus");
            return (Criteria) this;
        }

        public Criteria andClPublishStatusNotBetween(Short value1, Short value2) {
            addCriterion("cl_publish_status not between", value1, value2, "clPublishStatus");
            return (Criteria) this;
        }

        public Criteria andClPublishTimeIsNull() {
            addCriterion("cl_publish_time is null");
            return (Criteria) this;
        }

        public Criteria andClPublishTimeIsNotNull() {
            addCriterion("cl_publish_time is not null");
            return (Criteria) this;
        }

        public Criteria andClPublishTimeEqualTo(Date value) {
            addCriterion("cl_publish_time =", value, "clPublishTime");
            return (Criteria) this;
        }

        public Criteria andClPublishTimeNotEqualTo(Date value) {
            addCriterion("cl_publish_time <>", value, "clPublishTime");
            return (Criteria) this;
        }

        public Criteria andClPublishTimeGreaterThan(Date value) {
            addCriterion("cl_publish_time >", value, "clPublishTime");
            return (Criteria) this;
        }

        public Criteria andClPublishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cl_publish_time >=", value, "clPublishTime");
            return (Criteria) this;
        }

        public Criteria andClPublishTimeLessThan(Date value) {
            addCriterion("cl_publish_time <", value, "clPublishTime");
            return (Criteria) this;
        }

        public Criteria andClPublishTimeLessThanOrEqualTo(Date value) {
            addCriterion("cl_publish_time <=", value, "clPublishTime");
            return (Criteria) this;
        }

        public Criteria andClPublishTimeIn(List<Date> values) {
            addCriterion("cl_publish_time in", values, "clPublishTime");
            return (Criteria) this;
        }

        public Criteria andClPublishTimeNotIn(List<Date> values) {
            addCriterion("cl_publish_time not in", values, "clPublishTime");
            return (Criteria) this;
        }

        public Criteria andClPublishTimeBetween(Date value1, Date value2) {
            addCriterion("cl_publish_time between", value1, value2, "clPublishTime");
            return (Criteria) this;
        }

        public Criteria andClPublishTimeNotBetween(Date value1, Date value2) {
            addCriterion("cl_publish_time not between", value1, value2, "clPublishTime");
            return (Criteria) this;
        }

        public Criteria andClGrpIdIsNull() {
            addCriterion("cl_grp_id is null");
            return (Criteria) this;
        }

        public Criteria andClGrpIdIsNotNull() {
            addCriterion("cl_grp_id is not null");
            return (Criteria) this;
        }

        public Criteria andClGrpIdEqualTo(String value) {
            addCriterion("cl_grp_id =", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdNotEqualTo(String value) {
            addCriterion("cl_grp_id <>", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdGreaterThan(String value) {
            addCriterion("cl_grp_id >", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdGreaterThanOrEqualTo(String value) {
            addCriterion("cl_grp_id >=", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdLessThan(String value) {
            addCriterion("cl_grp_id <", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdLessThanOrEqualTo(String value) {
            addCriterion("cl_grp_id <=", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdLike(String value) {
            addCriterion("cl_grp_id like", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdNotLike(String value) {
            addCriterion("cl_grp_id not like", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdIn(List<String> values) {
            addCriterion("cl_grp_id in", values, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdNotIn(List<String> values) {
            addCriterion("cl_grp_id not in", values, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdBetween(String value1, String value2) {
            addCriterion("cl_grp_id between", value1, value2, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdNotBetween(String value1, String value2) {
            addCriterion("cl_grp_id not between", value1, value2, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdIsNull() {
            addCriterion("cl_hotel_id is null");
            return (Criteria) this;
        }

        public Criteria andClHotelIdIsNotNull() {
            addCriterion("cl_hotel_id is not null");
            return (Criteria) this;
        }

        public Criteria andClHotelIdEqualTo(String value) {
            addCriterion("cl_hotel_id =", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdNotEqualTo(String value) {
            addCriterion("cl_hotel_id <>", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdGreaterThan(String value) {
            addCriterion("cl_hotel_id >", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdGreaterThanOrEqualTo(String value) {
            addCriterion("cl_hotel_id >=", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdLessThan(String value) {
            addCriterion("cl_hotel_id <", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdLessThanOrEqualTo(String value) {
            addCriterion("cl_hotel_id <=", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdLike(String value) {
            addCriterion("cl_hotel_id like", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdNotLike(String value) {
            addCriterion("cl_hotel_id not like", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdIn(List<String> values) {
            addCriterion("cl_hotel_id in", values, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdNotIn(List<String> values) {
            addCriterion("cl_hotel_id not in", values, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdBetween(String value1, String value2) {
            addCriterion("cl_hotel_id between", value1, value2, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdNotBetween(String value1, String value2) {
            addCriterion("cl_hotel_id not between", value1, value2, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdIsNull() {
            addCriterion("cl_create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdIsNotNull() {
            addCriterion("cl_create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdEqualTo(String value) {
            addCriterion("cl_create_user_id =", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdNotEqualTo(String value) {
            addCriterion("cl_create_user_id <>", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdGreaterThan(String value) {
            addCriterion("cl_create_user_id >", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("cl_create_user_id >=", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdLessThan(String value) {
            addCriterion("cl_create_user_id <", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("cl_create_user_id <=", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdLike(String value) {
            addCriterion("cl_create_user_id like", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdNotLike(String value) {
            addCriterion("cl_create_user_id not like", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdIn(List<String> values) {
            addCriterion("cl_create_user_id in", values, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdNotIn(List<String> values) {
            addCriterion("cl_create_user_id not in", values, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdBetween(String value1, String value2) {
            addCriterion("cl_create_user_id between", value1, value2, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("cl_create_user_id not between", value1, value2, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeIsNull() {
            addCriterion("cl_create_time is null");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeIsNotNull() {
            addCriterion("cl_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeEqualTo(Date value) {
            addCriterion("cl_create_time =", value, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeNotEqualTo(Date value) {
            addCriterion("cl_create_time <>", value, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeGreaterThan(Date value) {
            addCriterion("cl_create_time >", value, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cl_create_time >=", value, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeLessThan(Date value) {
            addCriterion("cl_create_time <", value, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("cl_create_time <=", value, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeIn(List<Date> values) {
            addCriterion("cl_create_time in", values, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeNotIn(List<Date> values) {
            addCriterion("cl_create_time not in", values, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeBetween(Date value1, Date value2) {
            addCriterion("cl_create_time between", value1, value2, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("cl_create_time not between", value1, value2, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdIsNull() {
            addCriterion("cl_update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdIsNotNull() {
            addCriterion("cl_update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdEqualTo(String value) {
            addCriterion("cl_update_user_id =", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdNotEqualTo(String value) {
            addCriterion("cl_update_user_id <>", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdGreaterThan(String value) {
            addCriterion("cl_update_user_id >", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("cl_update_user_id >=", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdLessThan(String value) {
            addCriterion("cl_update_user_id <", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("cl_update_user_id <=", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdLike(String value) {
            addCriterion("cl_update_user_id like", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdNotLike(String value) {
            addCriterion("cl_update_user_id not like", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdIn(List<String> values) {
            addCriterion("cl_update_user_id in", values, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdNotIn(List<String> values) {
            addCriterion("cl_update_user_id not in", values, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdBetween(String value1, String value2) {
            addCriterion("cl_update_user_id between", value1, value2, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("cl_update_user_id not between", value1, value2, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeIsNull() {
            addCriterion("cl_update_time is null");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeIsNotNull() {
            addCriterion("cl_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeEqualTo(Date value) {
            addCriterion("cl_update_time =", value, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeNotEqualTo(Date value) {
            addCriterion("cl_update_time <>", value, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeGreaterThan(Date value) {
            addCriterion("cl_update_time >", value, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cl_update_time >=", value, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeLessThan(Date value) {
            addCriterion("cl_update_time <", value, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("cl_update_time <=", value, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeIn(List<Date> values) {
            addCriterion("cl_update_time in", values, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeNotIn(List<Date> values) {
            addCriterion("cl_update_time not in", values, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("cl_update_time between", value1, value2, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("cl_update_time not between", value1, value2, "clUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated do_not_delete_during_merge Wed May 09 16:16:08 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table perms.perms_t_notice
     *
     * @mbggenerated Wed May 09 16:16:08 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}