package com.sstc.hmis.permission.dbaccess.data;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PermsTGroupHotelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public PermsTGroupHotelExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andClIdIsNull() {
			addCriterion("cl_id is null");
			return (Criteria) this;
		}

		public Criteria andClIdIsNotNull() {
			addCriterion("cl_id is not null");
			return (Criteria) this;
		}

		public Criteria andClIdEqualTo(String value) {
			addCriterion("cl_id =", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdNotEqualTo(String value) {
			addCriterion("cl_id <>", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdGreaterThan(String value) {
			addCriterion("cl_id >", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdGreaterThanOrEqualTo(String value) {
			addCriterion("cl_id >=", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdLessThan(String value) {
			addCriterion("cl_id <", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdLessThanOrEqualTo(String value) {
			addCriterion("cl_id <=", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdLike(String value) {
			addCriterion("cl_id like", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdNotLike(String value) {
			addCriterion("cl_id not like", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdIn(List<String> values) {
			addCriterion("cl_id in", values, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdNotIn(List<String> values) {
			addCriterion("cl_id not in", values, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdBetween(String value1, String value2) {
			addCriterion("cl_id between", value1, value2, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdNotBetween(String value1, String value2) {
			addCriterion("cl_id not between", value1, value2, "clId");
			return (Criteria) this;
		}

		public Criteria andClNameIsNull() {
			addCriterion("cl_name is null");
			return (Criteria) this;
		}

		public Criteria andClNameIsNotNull() {
			addCriterion("cl_name is not null");
			return (Criteria) this;
		}

		public Criteria andClNameEqualTo(String value) {
			addCriterion("cl_name =", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameNotEqualTo(String value) {
			addCriterion("cl_name <>", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameGreaterThan(String value) {
			addCriterion("cl_name >", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameGreaterThanOrEqualTo(String value) {
			addCriterion("cl_name >=", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameLessThan(String value) {
			addCriterion("cl_name <", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameLessThanOrEqualTo(String value) {
			addCriterion("cl_name <=", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameLike(String value) {
			addCriterion("cl_name like", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameNotLike(String value) {
			addCriterion("cl_name not like", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameIn(List<String> values) {
			addCriterion("cl_name in", values, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameNotIn(List<String> values) {
			addCriterion("cl_name not in", values, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameBetween(String value1, String value2) {
			addCriterion("cl_name between", value1, value2, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameNotBetween(String value1, String value2) {
			addCriterion("cl_name not between", value1, value2, "clName");
			return (Criteria) this;
		}

		public Criteria andClEnglishNameIsNull() {
			addCriterion("cl_english_name is null");
			return (Criteria) this;
		}

		public Criteria andClEnglishNameIsNotNull() {
			addCriterion("cl_english_name is not null");
			return (Criteria) this;
		}

		public Criteria andClEnglishNameEqualTo(String value) {
			addCriterion("cl_english_name =", value, "clEnglishName");
			return (Criteria) this;
		}

		public Criteria andClEnglishNameNotEqualTo(String value) {
			addCriterion("cl_english_name <>", value, "clEnglishName");
			return (Criteria) this;
		}

		public Criteria andClEnglishNameGreaterThan(String value) {
			addCriterion("cl_english_name >", value, "clEnglishName");
			return (Criteria) this;
		}

		public Criteria andClEnglishNameGreaterThanOrEqualTo(String value) {
			addCriterion("cl_english_name >=", value, "clEnglishName");
			return (Criteria) this;
		}

		public Criteria andClEnglishNameLessThan(String value) {
			addCriterion("cl_english_name <", value, "clEnglishName");
			return (Criteria) this;
		}

		public Criteria andClEnglishNameLessThanOrEqualTo(String value) {
			addCriterion("cl_english_name <=", value, "clEnglishName");
			return (Criteria) this;
		}

		public Criteria andClEnglishNameLike(String value) {
			addCriterion("cl_english_name like", value, "clEnglishName");
			return (Criteria) this;
		}

		public Criteria andClEnglishNameNotLike(String value) {
			addCriterion("cl_english_name not like", value, "clEnglishName");
			return (Criteria) this;
		}

		public Criteria andClEnglishNameIn(List<String> values) {
			addCriterion("cl_english_name in", values, "clEnglishName");
			return (Criteria) this;
		}

		public Criteria andClEnglishNameNotIn(List<String> values) {
			addCriterion("cl_english_name not in", values, "clEnglishName");
			return (Criteria) this;
		}

		public Criteria andClEnglishNameBetween(String value1, String value2) {
			addCriterion("cl_english_name between", value1, value2, "clEnglishName");
			return (Criteria) this;
		}

		public Criteria andClEnglishNameNotBetween(String value1, String value2) {
			addCriterion("cl_english_name not between", value1, value2, "clEnglishName");
			return (Criteria) this;
		}

		public Criteria andClCodeIsNull() {
			addCriterion("cl_code is null");
			return (Criteria) this;
		}

		public Criteria andClCodeIsNotNull() {
			addCriterion("cl_code is not null");
			return (Criteria) this;
		}

		public Criteria andClCodeEqualTo(String value) {
			addCriterion("cl_code =", value, "clCode");
			return (Criteria) this;
		}

		public Criteria andClCodeNotEqualTo(String value) {
			addCriterion("cl_code <>", value, "clCode");
			return (Criteria) this;
		}

		public Criteria andClCodeGreaterThan(String value) {
			addCriterion("cl_code >", value, "clCode");
			return (Criteria) this;
		}

		public Criteria andClCodeGreaterThanOrEqualTo(String value) {
			addCriterion("cl_code >=", value, "clCode");
			return (Criteria) this;
		}

		public Criteria andClCodeLessThan(String value) {
			addCriterion("cl_code <", value, "clCode");
			return (Criteria) this;
		}

		public Criteria andClCodeLessThanOrEqualTo(String value) {
			addCriterion("cl_code <=", value, "clCode");
			return (Criteria) this;
		}

		public Criteria andClCodeLike(String value) {
			addCriterion("cl_code like", value, "clCode");
			return (Criteria) this;
		}

		public Criteria andClCodeNotLike(String value) {
			addCriterion("cl_code not like", value, "clCode");
			return (Criteria) this;
		}

		public Criteria andClCodeIn(List<String> values) {
			addCriterion("cl_code in", values, "clCode");
			return (Criteria) this;
		}

		public Criteria andClCodeNotIn(List<String> values) {
			addCriterion("cl_code not in", values, "clCode");
			return (Criteria) this;
		}

		public Criteria andClCodeBetween(String value1, String value2) {
			addCriterion("cl_code between", value1, value2, "clCode");
			return (Criteria) this;
		}

		public Criteria andClCodeNotBetween(String value1, String value2) {
			addCriterion("cl_code not between", value1, value2, "clCode");
			return (Criteria) this;
		}

		public Criteria andClStatusIsNull() {
			addCriterion("cl_status is null");
			return (Criteria) this;
		}

		public Criteria andClStatusIsNotNull() {
			addCriterion("cl_status is not null");
			return (Criteria) this;
		}

		public Criteria andClStatusEqualTo(Short value) {
			addCriterion("cl_status =", value, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusNotEqualTo(Short value) {
			addCriterion("cl_status <>", value, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusGreaterThan(Short value) {
			addCriterion("cl_status >", value, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("cl_status >=", value, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusLessThan(Short value) {
			addCriterion("cl_status <", value, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusLessThanOrEqualTo(Short value) {
			addCriterion("cl_status <=", value, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusIn(List<Short> values) {
			addCriterion("cl_status in", values, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusNotIn(List<Short> values) {
			addCriterion("cl_status not in", values, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusBetween(Short value1, Short value2) {
			addCriterion("cl_status between", value1, value2, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusNotBetween(Short value1, Short value2) {
			addCriterion("cl_status not between", value1, value2, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClBlockupIsNull() {
			addCriterion("cl_blockup is null");
			return (Criteria) this;
		}

		public Criteria andClBlockupIsNotNull() {
			addCriterion("cl_blockup is not null");
			return (Criteria) this;
		}

		public Criteria andClBlockupEqualTo(Short value) {
			addCriterion("cl_blockup =", value, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupNotEqualTo(Short value) {
			addCriterion("cl_blockup <>", value, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupGreaterThan(Short value) {
			addCriterion("cl_blockup >", value, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupGreaterThanOrEqualTo(Short value) {
			addCriterion("cl_blockup >=", value, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupLessThan(Short value) {
			addCriterion("cl_blockup <", value, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupLessThanOrEqualTo(Short value) {
			addCriterion("cl_blockup <=", value, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupIn(List<Short> values) {
			addCriterion("cl_blockup in", values, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupNotIn(List<Short> values) {
			addCriterion("cl_blockup not in", values, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupBetween(Short value1, Short value2) {
			addCriterion("cl_blockup between", value1, value2, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupNotBetween(Short value1, Short value2) {
			addCriterion("cl_blockup not between", value1, value2, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClTypeIsNull() {
			addCriterion("cl_type is null");
			return (Criteria) this;
		}

		public Criteria andClTypeIsNotNull() {
			addCriterion("cl_type is not null");
			return (Criteria) this;
		}

		public Criteria andClTypeEqualTo(Short value) {
			addCriterion("cl_type =", value, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeNotEqualTo(Short value) {
			addCriterion("cl_type <>", value, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeGreaterThan(Short value) {
			addCriterion("cl_type >", value, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeGreaterThanOrEqualTo(Short value) {
			addCriterion("cl_type >=", value, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeLessThan(Short value) {
			addCriterion("cl_type <", value, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeLessThanOrEqualTo(Short value) {
			addCriterion("cl_type <=", value, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeIn(List<Short> values) {
			addCriterion("cl_type in", values, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeNotIn(List<Short> values) {
			addCriterion("cl_type not in", values, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeBetween(Short value1, Short value2) {
			addCriterion("cl_type between", value1, value2, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeNotBetween(Short value1, Short value2) {
			addCriterion("cl_type not between", value1, value2, "clType");
			return (Criteria) this;
		}

		public Criteria andClLevelIsNull() {
			addCriterion("cl_level is null");
			return (Criteria) this;
		}

		public Criteria andClLevelIsNotNull() {
			addCriterion("cl_level is not null");
			return (Criteria) this;
		}

		public Criteria andClLevelEqualTo(Short value) {
			addCriterion("cl_level =", value, "clLevel");
			return (Criteria) this;
		}

		public Criteria andClLevelNotEqualTo(Short value) {
			addCriterion("cl_level <>", value, "clLevel");
			return (Criteria) this;
		}

		public Criteria andClLevelGreaterThan(Short value) {
			addCriterion("cl_level >", value, "clLevel");
			return (Criteria) this;
		}

		public Criteria andClLevelGreaterThanOrEqualTo(Short value) {
			addCriterion("cl_level >=", value, "clLevel");
			return (Criteria) this;
		}

		public Criteria andClLevelLessThan(Short value) {
			addCriterion("cl_level <", value, "clLevel");
			return (Criteria) this;
		}

		public Criteria andClLevelLessThanOrEqualTo(Short value) {
			addCriterion("cl_level <=", value, "clLevel");
			return (Criteria) this;
		}

		public Criteria andClLevelIn(List<Short> values) {
			addCriterion("cl_level in", values, "clLevel");
			return (Criteria) this;
		}

		public Criteria andClLevelNotIn(List<Short> values) {
			addCriterion("cl_level not in", values, "clLevel");
			return (Criteria) this;
		}

		public Criteria andClLevelBetween(Short value1, Short value2) {
			addCriterion("cl_level between", value1, value2, "clLevel");
			return (Criteria) this;
		}

		public Criteria andClLevelNotBetween(Short value1, Short value2) {
			addCriterion("cl_level not between", value1, value2, "clLevel");
			return (Criteria) this;
		}

		public Criteria andClMaxHotelIsNull() {
			addCriterion("cl_max_hotel is null");
			return (Criteria) this;
		}

		public Criteria andClMaxHotelIsNotNull() {
			addCriterion("cl_max_hotel is not null");
			return (Criteria) this;
		}

		public Criteria andClMaxHotelEqualTo(Integer value) {
			addCriterion("cl_max_hotel =", value, "clMaxHotel");
			return (Criteria) this;
		}

		public Criteria andClMaxHotelNotEqualTo(Integer value) {
			addCriterion("cl_max_hotel <>", value, "clMaxHotel");
			return (Criteria) this;
		}

		public Criteria andClMaxHotelGreaterThan(Integer value) {
			addCriterion("cl_max_hotel >", value, "clMaxHotel");
			return (Criteria) this;
		}

		public Criteria andClMaxHotelGreaterThanOrEqualTo(Integer value) {
			addCriterion("cl_max_hotel >=", value, "clMaxHotel");
			return (Criteria) this;
		}

		public Criteria andClMaxHotelLessThan(Integer value) {
			addCriterion("cl_max_hotel <", value, "clMaxHotel");
			return (Criteria) this;
		}

		public Criteria andClMaxHotelLessThanOrEqualTo(Integer value) {
			addCriterion("cl_max_hotel <=", value, "clMaxHotel");
			return (Criteria) this;
		}

		public Criteria andClMaxHotelIn(List<Integer> values) {
			addCriterion("cl_max_hotel in", values, "clMaxHotel");
			return (Criteria) this;
		}

		public Criteria andClMaxHotelNotIn(List<Integer> values) {
			addCriterion("cl_max_hotel not in", values, "clMaxHotel");
			return (Criteria) this;
		}

		public Criteria andClMaxHotelBetween(Integer value1, Integer value2) {
			addCriterion("cl_max_hotel between", value1, value2, "clMaxHotel");
			return (Criteria) this;
		}

		public Criteria andClMaxHotelNotBetween(Integer value1, Integer value2) {
			addCriterion("cl_max_hotel not between", value1, value2, "clMaxHotel");
			return (Criteria) this;
		}

		public Criteria andClPidIsNull() {
			addCriterion("cl_pid is null");
			return (Criteria) this;
		}

		public Criteria andClPidIsNotNull() {
			addCriterion("cl_pid is not null");
			return (Criteria) this;
		}

		public Criteria andClPidEqualTo(String value) {
			addCriterion("cl_pid =", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidNotEqualTo(String value) {
			addCriterion("cl_pid <>", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidGreaterThan(String value) {
			addCriterion("cl_pid >", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidGreaterThanOrEqualTo(String value) {
			addCriterion("cl_pid >=", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidLessThan(String value) {
			addCriterion("cl_pid <", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidLessThanOrEqualTo(String value) {
			addCriterion("cl_pid <=", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidLike(String value) {
			addCriterion("cl_pid like", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidNotLike(String value) {
			addCriterion("cl_pid not like", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidIn(List<String> values) {
			addCriterion("cl_pid in", values, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidNotIn(List<String> values) {
			addCriterion("cl_pid not in", values, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidBetween(String value1, String value2) {
			addCriterion("cl_pid between", value1, value2, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidNotBetween(String value1, String value2) {
			addCriterion("cl_pid not between", value1, value2, "clPid");
			return (Criteria) this;
		}

		public Criteria andClCountryIdIsNull() {
			addCriterion("cl_country_id is null");
			return (Criteria) this;
		}

		public Criteria andClCountryIdIsNotNull() {
			addCriterion("cl_country_id is not null");
			return (Criteria) this;
		}

		public Criteria andClCountryIdEqualTo(String value) {
			addCriterion("cl_country_id =", value, "clCountryId");
			return (Criteria) this;
		}

		public Criteria andClCountryIdNotEqualTo(String value) {
			addCriterion("cl_country_id <>", value, "clCountryId");
			return (Criteria) this;
		}

		public Criteria andClCountryIdGreaterThan(String value) {
			addCriterion("cl_country_id >", value, "clCountryId");
			return (Criteria) this;
		}

		public Criteria andClCountryIdGreaterThanOrEqualTo(String value) {
			addCriterion("cl_country_id >=", value, "clCountryId");
			return (Criteria) this;
		}

		public Criteria andClCountryIdLessThan(String value) {
			addCriterion("cl_country_id <", value, "clCountryId");
			return (Criteria) this;
		}

		public Criteria andClCountryIdLessThanOrEqualTo(String value) {
			addCriterion("cl_country_id <=", value, "clCountryId");
			return (Criteria) this;
		}

		public Criteria andClCountryIdLike(String value) {
			addCriterion("cl_country_id like", value, "clCountryId");
			return (Criteria) this;
		}

		public Criteria andClCountryIdNotLike(String value) {
			addCriterion("cl_country_id not like", value, "clCountryId");
			return (Criteria) this;
		}

		public Criteria andClCountryIdIn(List<String> values) {
			addCriterion("cl_country_id in", values, "clCountryId");
			return (Criteria) this;
		}

		public Criteria andClCountryIdNotIn(List<String> values) {
			addCriterion("cl_country_id not in", values, "clCountryId");
			return (Criteria) this;
		}

		public Criteria andClCountryIdBetween(String value1, String value2) {
			addCriterion("cl_country_id between", value1, value2, "clCountryId");
			return (Criteria) this;
		}

		public Criteria andClCountryIdNotBetween(String value1, String value2) {
			addCriterion("cl_country_id not between", value1, value2, "clCountryId");
			return (Criteria) this;
		}

		public Criteria andClProvinceIdIsNull() {
			addCriterion("cl_province_id is null");
			return (Criteria) this;
		}

		public Criteria andClProvinceIdIsNotNull() {
			addCriterion("cl_province_id is not null");
			return (Criteria) this;
		}

		public Criteria andClProvinceIdEqualTo(String value) {
			addCriterion("cl_province_id =", value, "clProvinceId");
			return (Criteria) this;
		}

		public Criteria andClProvinceIdNotEqualTo(String value) {
			addCriterion("cl_province_id <>", value, "clProvinceId");
			return (Criteria) this;
		}

		public Criteria andClProvinceIdGreaterThan(String value) {
			addCriterion("cl_province_id >", value, "clProvinceId");
			return (Criteria) this;
		}

		public Criteria andClProvinceIdGreaterThanOrEqualTo(String value) {
			addCriterion("cl_province_id >=", value, "clProvinceId");
			return (Criteria) this;
		}

		public Criteria andClProvinceIdLessThan(String value) {
			addCriterion("cl_province_id <", value, "clProvinceId");
			return (Criteria) this;
		}

		public Criteria andClProvinceIdLessThanOrEqualTo(String value) {
			addCriterion("cl_province_id <=", value, "clProvinceId");
			return (Criteria) this;
		}

		public Criteria andClProvinceIdLike(String value) {
			addCriterion("cl_province_id like", value, "clProvinceId");
			return (Criteria) this;
		}

		public Criteria andClProvinceIdNotLike(String value) {
			addCriterion("cl_province_id not like", value, "clProvinceId");
			return (Criteria) this;
		}

		public Criteria andClProvinceIdIn(List<String> values) {
			addCriterion("cl_province_id in", values, "clProvinceId");
			return (Criteria) this;
		}

		public Criteria andClProvinceIdNotIn(List<String> values) {
			addCriterion("cl_province_id not in", values, "clProvinceId");
			return (Criteria) this;
		}

		public Criteria andClProvinceIdBetween(String value1, String value2) {
			addCriterion("cl_province_id between", value1, value2, "clProvinceId");
			return (Criteria) this;
		}

		public Criteria andClProvinceIdNotBetween(String value1, String value2) {
			addCriterion("cl_province_id not between", value1, value2, "clProvinceId");
			return (Criteria) this;
		}

		public Criteria andClCityIdIsNull() {
			addCriterion("cl_city_id is null");
			return (Criteria) this;
		}

		public Criteria andClCityIdIsNotNull() {
			addCriterion("cl_city_id is not null");
			return (Criteria) this;
		}

		public Criteria andClCityIdEqualTo(String value) {
			addCriterion("cl_city_id =", value, "clCityId");
			return (Criteria) this;
		}

		public Criteria andClCityIdNotEqualTo(String value) {
			addCriterion("cl_city_id <>", value, "clCityId");
			return (Criteria) this;
		}

		public Criteria andClCityIdGreaterThan(String value) {
			addCriterion("cl_city_id >", value, "clCityId");
			return (Criteria) this;
		}

		public Criteria andClCityIdGreaterThanOrEqualTo(String value) {
			addCriterion("cl_city_id >=", value, "clCityId");
			return (Criteria) this;
		}

		public Criteria andClCityIdLessThan(String value) {
			addCriterion("cl_city_id <", value, "clCityId");
			return (Criteria) this;
		}

		public Criteria andClCityIdLessThanOrEqualTo(String value) {
			addCriterion("cl_city_id <=", value, "clCityId");
			return (Criteria) this;
		}

		public Criteria andClCityIdLike(String value) {
			addCriterion("cl_city_id like", value, "clCityId");
			return (Criteria) this;
		}

		public Criteria andClCityIdNotLike(String value) {
			addCriterion("cl_city_id not like", value, "clCityId");
			return (Criteria) this;
		}

		public Criteria andClCityIdIn(List<String> values) {
			addCriterion("cl_city_id in", values, "clCityId");
			return (Criteria) this;
		}

		public Criteria andClCityIdNotIn(List<String> values) {
			addCriterion("cl_city_id not in", values, "clCityId");
			return (Criteria) this;
		}

		public Criteria andClCityIdBetween(String value1, String value2) {
			addCriterion("cl_city_id between", value1, value2, "clCityId");
			return (Criteria) this;
		}

		public Criteria andClCityIdNotBetween(String value1, String value2) {
			addCriterion("cl_city_id not between", value1, value2, "clCityId");
			return (Criteria) this;
		}

		public Criteria andClDistrictIsNull() {
			addCriterion("cl_district is null");
			return (Criteria) this;
		}

		public Criteria andClDistrictIsNotNull() {
			addCriterion("cl_district is not null");
			return (Criteria) this;
		}

		public Criteria andClDistrictEqualTo(String value) {
			addCriterion("cl_district =", value, "clDistrict");
			return (Criteria) this;
		}

		public Criteria andClDistrictNotEqualTo(String value) {
			addCriterion("cl_district <>", value, "clDistrict");
			return (Criteria) this;
		}

		public Criteria andClDistrictGreaterThan(String value) {
			addCriterion("cl_district >", value, "clDistrict");
			return (Criteria) this;
		}

		public Criteria andClDistrictGreaterThanOrEqualTo(String value) {
			addCriterion("cl_district >=", value, "clDistrict");
			return (Criteria) this;
		}

		public Criteria andClDistrictLessThan(String value) {
			addCriterion("cl_district <", value, "clDistrict");
			return (Criteria) this;
		}

		public Criteria andClDistrictLessThanOrEqualTo(String value) {
			addCriterion("cl_district <=", value, "clDistrict");
			return (Criteria) this;
		}

		public Criteria andClDistrictLike(String value) {
			addCriterion("cl_district like", value, "clDistrict");
			return (Criteria) this;
		}

		public Criteria andClDistrictNotLike(String value) {
			addCriterion("cl_district not like", value, "clDistrict");
			return (Criteria) this;
		}

		public Criteria andClDistrictIn(List<String> values) {
			addCriterion("cl_district in", values, "clDistrict");
			return (Criteria) this;
		}

		public Criteria andClDistrictNotIn(List<String> values) {
			addCriterion("cl_district not in", values, "clDistrict");
			return (Criteria) this;
		}

		public Criteria andClDistrictBetween(String value1, String value2) {
			addCriterion("cl_district between", value1, value2, "clDistrict");
			return (Criteria) this;
		}

		public Criteria andClDistrictNotBetween(String value1, String value2) {
			addCriterion("cl_district not between", value1, value2, "clDistrict");
			return (Criteria) this;
		}

		public Criteria andClAddressIsNull() {
			addCriterion("cl_address is null");
			return (Criteria) this;
		}

		public Criteria andClAddressIsNotNull() {
			addCriterion("cl_address is not null");
			return (Criteria) this;
		}

		public Criteria andClAddressEqualTo(String value) {
			addCriterion("cl_address =", value, "clAddress");
			return (Criteria) this;
		}

		public Criteria andClAddressNotEqualTo(String value) {
			addCriterion("cl_address <>", value, "clAddress");
			return (Criteria) this;
		}

		public Criteria andClAddressGreaterThan(String value) {
			addCriterion("cl_address >", value, "clAddress");
			return (Criteria) this;
		}

		public Criteria andClAddressGreaterThanOrEqualTo(String value) {
			addCriterion("cl_address >=", value, "clAddress");
			return (Criteria) this;
		}

		public Criteria andClAddressLessThan(String value) {
			addCriterion("cl_address <", value, "clAddress");
			return (Criteria) this;
		}

		public Criteria andClAddressLessThanOrEqualTo(String value) {
			addCriterion("cl_address <=", value, "clAddress");
			return (Criteria) this;
		}

		public Criteria andClAddressLike(String value) {
			addCriterion("cl_address like", value, "clAddress");
			return (Criteria) this;
		}

		public Criteria andClAddressNotLike(String value) {
			addCriterion("cl_address not like", value, "clAddress");
			return (Criteria) this;
		}

		public Criteria andClAddressIn(List<String> values) {
			addCriterion("cl_address in", values, "clAddress");
			return (Criteria) this;
		}

		public Criteria andClAddressNotIn(List<String> values) {
			addCriterion("cl_address not in", values, "clAddress");
			return (Criteria) this;
		}

		public Criteria andClAddressBetween(String value1, String value2) {
			addCriterion("cl_address between", value1, value2, "clAddress");
			return (Criteria) this;
		}

		public Criteria andClAddressNotBetween(String value1, String value2) {
			addCriterion("cl_address not between", value1, value2, "clAddress");
			return (Criteria) this;
		}

		public Criteria andClAdminNameIsNull() {
			addCriterion("cl_admin_name is null");
			return (Criteria) this;
		}

		public Criteria andClAdminNameIsNotNull() {
			addCriterion("cl_admin_name is not null");
			return (Criteria) this;
		}

		public Criteria andClAdminNameEqualTo(String value) {
			addCriterion("cl_admin_name =", value, "clAdminName");
			return (Criteria) this;
		}

		public Criteria andClAdminNameNotEqualTo(String value) {
			addCriterion("cl_admin_name <>", value, "clAdminName");
			return (Criteria) this;
		}

		public Criteria andClAdminNameGreaterThan(String value) {
			addCriterion("cl_admin_name >", value, "clAdminName");
			return (Criteria) this;
		}

		public Criteria andClAdminNameGreaterThanOrEqualTo(String value) {
			addCriterion("cl_admin_name >=", value, "clAdminName");
			return (Criteria) this;
		}

		public Criteria andClAdminNameLessThan(String value) {
			addCriterion("cl_admin_name <", value, "clAdminName");
			return (Criteria) this;
		}

		public Criteria andClAdminNameLessThanOrEqualTo(String value) {
			addCriterion("cl_admin_name <=", value, "clAdminName");
			return (Criteria) this;
		}

		public Criteria andClAdminNameLike(String value) {
			addCriterion("cl_admin_name like", value, "clAdminName");
			return (Criteria) this;
		}

		public Criteria andClAdminNameNotLike(String value) {
			addCriterion("cl_admin_name not like", value, "clAdminName");
			return (Criteria) this;
		}

		public Criteria andClAdminNameIn(List<String> values) {
			addCriterion("cl_admin_name in", values, "clAdminName");
			return (Criteria) this;
		}

		public Criteria andClAdminNameNotIn(List<String> values) {
			addCriterion("cl_admin_name not in", values, "clAdminName");
			return (Criteria) this;
		}

		public Criteria andClAdminNameBetween(String value1, String value2) {
			addCriterion("cl_admin_name between", value1, value2, "clAdminName");
			return (Criteria) this;
		}

		public Criteria andClAdminNameNotBetween(String value1, String value2) {
			addCriterion("cl_admin_name not between", value1, value2, "clAdminName");
			return (Criteria) this;
		}

		public Criteria andClZipCodeIsNull() {
			addCriterion("cl_zip_code is null");
			return (Criteria) this;
		}

		public Criteria andClZipCodeIsNotNull() {
			addCriterion("cl_zip_code is not null");
			return (Criteria) this;
		}

		public Criteria andClZipCodeEqualTo(String value) {
			addCriterion("cl_zip_code =", value, "clZipCode");
			return (Criteria) this;
		}

		public Criteria andClZipCodeNotEqualTo(String value) {
			addCriterion("cl_zip_code <>", value, "clZipCode");
			return (Criteria) this;
		}

		public Criteria andClZipCodeGreaterThan(String value) {
			addCriterion("cl_zip_code >", value, "clZipCode");
			return (Criteria) this;
		}

		public Criteria andClZipCodeGreaterThanOrEqualTo(String value) {
			addCriterion("cl_zip_code >=", value, "clZipCode");
			return (Criteria) this;
		}

		public Criteria andClZipCodeLessThan(String value) {
			addCriterion("cl_zip_code <", value, "clZipCode");
			return (Criteria) this;
		}

		public Criteria andClZipCodeLessThanOrEqualTo(String value) {
			addCriterion("cl_zip_code <=", value, "clZipCode");
			return (Criteria) this;
		}

		public Criteria andClZipCodeLike(String value) {
			addCriterion("cl_zip_code like", value, "clZipCode");
			return (Criteria) this;
		}

		public Criteria andClZipCodeNotLike(String value) {
			addCriterion("cl_zip_code not like", value, "clZipCode");
			return (Criteria) this;
		}

		public Criteria andClZipCodeIn(List<String> values) {
			addCriterion("cl_zip_code in", values, "clZipCode");
			return (Criteria) this;
		}

		public Criteria andClZipCodeNotIn(List<String> values) {
			addCriterion("cl_zip_code not in", values, "clZipCode");
			return (Criteria) this;
		}

		public Criteria andClZipCodeBetween(String value1, String value2) {
			addCriterion("cl_zip_code between", value1, value2, "clZipCode");
			return (Criteria) this;
		}

		public Criteria andClZipCodeNotBetween(String value1, String value2) {
			addCriterion("cl_zip_code not between", value1, value2, "clZipCode");
			return (Criteria) this;
		}

		public Criteria andClContacterIsNull() {
			addCriterion("cl_contacter is null");
			return (Criteria) this;
		}

		public Criteria andClContacterIsNotNull() {
			addCriterion("cl_contacter is not null");
			return (Criteria) this;
		}

		public Criteria andClContacterEqualTo(String value) {
			addCriterion("cl_contacter =", value, "clContacter");
			return (Criteria) this;
		}

		public Criteria andClContacterNotEqualTo(String value) {
			addCriterion("cl_contacter <>", value, "clContacter");
			return (Criteria) this;
		}

		public Criteria andClContacterGreaterThan(String value) {
			addCriterion("cl_contacter >", value, "clContacter");
			return (Criteria) this;
		}

		public Criteria andClContacterGreaterThanOrEqualTo(String value) {
			addCriterion("cl_contacter >=", value, "clContacter");
			return (Criteria) this;
		}

		public Criteria andClContacterLessThan(String value) {
			addCriterion("cl_contacter <", value, "clContacter");
			return (Criteria) this;
		}

		public Criteria andClContacterLessThanOrEqualTo(String value) {
			addCriterion("cl_contacter <=", value, "clContacter");
			return (Criteria) this;
		}

		public Criteria andClContacterLike(String value) {
			addCriterion("cl_contacter like", value, "clContacter");
			return (Criteria) this;
		}

		public Criteria andClContacterNotLike(String value) {
			addCriterion("cl_contacter not like", value, "clContacter");
			return (Criteria) this;
		}

		public Criteria andClContacterIn(List<String> values) {
			addCriterion("cl_contacter in", values, "clContacter");
			return (Criteria) this;
		}

		public Criteria andClContacterNotIn(List<String> values) {
			addCriterion("cl_contacter not in", values, "clContacter");
			return (Criteria) this;
		}

		public Criteria andClContacterBetween(String value1, String value2) {
			addCriterion("cl_contacter between", value1, value2, "clContacter");
			return (Criteria) this;
		}

		public Criteria andClContacterNotBetween(String value1, String value2) {
			addCriterion("cl_contacter not between", value1, value2, "clContacter");
			return (Criteria) this;
		}

		public Criteria andClContactNoIsNull() {
			addCriterion("cl_contact_no is null");
			return (Criteria) this;
		}

		public Criteria andClContactNoIsNotNull() {
			addCriterion("cl_contact_no is not null");
			return (Criteria) this;
		}

		public Criteria andClContactNoEqualTo(String value) {
			addCriterion("cl_contact_no =", value, "clContactNo");
			return (Criteria) this;
		}

		public Criteria andClContactNoNotEqualTo(String value) {
			addCriterion("cl_contact_no <>", value, "clContactNo");
			return (Criteria) this;
		}

		public Criteria andClContactNoGreaterThan(String value) {
			addCriterion("cl_contact_no >", value, "clContactNo");
			return (Criteria) this;
		}

		public Criteria andClContactNoGreaterThanOrEqualTo(String value) {
			addCriterion("cl_contact_no >=", value, "clContactNo");
			return (Criteria) this;
		}

		public Criteria andClContactNoLessThan(String value) {
			addCriterion("cl_contact_no <", value, "clContactNo");
			return (Criteria) this;
		}

		public Criteria andClContactNoLessThanOrEqualTo(String value) {
			addCriterion("cl_contact_no <=", value, "clContactNo");
			return (Criteria) this;
		}

		public Criteria andClContactNoLike(String value) {
			addCriterion("cl_contact_no like", value, "clContactNo");
			return (Criteria) this;
		}

		public Criteria andClContactNoNotLike(String value) {
			addCriterion("cl_contact_no not like", value, "clContactNo");
			return (Criteria) this;
		}

		public Criteria andClContactNoIn(List<String> values) {
			addCriterion("cl_contact_no in", values, "clContactNo");
			return (Criteria) this;
		}

		public Criteria andClContactNoNotIn(List<String> values) {
			addCriterion("cl_contact_no not in", values, "clContactNo");
			return (Criteria) this;
		}

		public Criteria andClContactNoBetween(String value1, String value2) {
			addCriterion("cl_contact_no between", value1, value2, "clContactNo");
			return (Criteria) this;
		}

		public Criteria andClContactNoNotBetween(String value1, String value2) {
			addCriterion("cl_contact_no not between", value1, value2, "clContactNo");
			return (Criteria) this;
		}

		public Criteria andClFaxIsNull() {
			addCriterion("cl_fax is null");
			return (Criteria) this;
		}

		public Criteria andClFaxIsNotNull() {
			addCriterion("cl_fax is not null");
			return (Criteria) this;
		}

		public Criteria andClFaxEqualTo(String value) {
			addCriterion("cl_fax =", value, "clFax");
			return (Criteria) this;
		}

		public Criteria andClFaxNotEqualTo(String value) {
			addCriterion("cl_fax <>", value, "clFax");
			return (Criteria) this;
		}

		public Criteria andClFaxGreaterThan(String value) {
			addCriterion("cl_fax >", value, "clFax");
			return (Criteria) this;
		}

		public Criteria andClFaxGreaterThanOrEqualTo(String value) {
			addCriterion("cl_fax >=", value, "clFax");
			return (Criteria) this;
		}

		public Criteria andClFaxLessThan(String value) {
			addCriterion("cl_fax <", value, "clFax");
			return (Criteria) this;
		}

		public Criteria andClFaxLessThanOrEqualTo(String value) {
			addCriterion("cl_fax <=", value, "clFax");
			return (Criteria) this;
		}

		public Criteria andClFaxLike(String value) {
			addCriterion("cl_fax like", value, "clFax");
			return (Criteria) this;
		}

		public Criteria andClFaxNotLike(String value) {
			addCriterion("cl_fax not like", value, "clFax");
			return (Criteria) this;
		}

		public Criteria andClFaxIn(List<String> values) {
			addCriterion("cl_fax in", values, "clFax");
			return (Criteria) this;
		}

		public Criteria andClFaxNotIn(List<String> values) {
			addCriterion("cl_fax not in", values, "clFax");
			return (Criteria) this;
		}

		public Criteria andClFaxBetween(String value1, String value2) {
			addCriterion("cl_fax between", value1, value2, "clFax");
			return (Criteria) this;
		}

		public Criteria andClFaxNotBetween(String value1, String value2) {
			addCriterion("cl_fax not between", value1, value2, "clFax");
			return (Criteria) this;
		}

		public Criteria andClEmailIsNull() {
			addCriterion("cl_email is null");
			return (Criteria) this;
		}

		public Criteria andClEmailIsNotNull() {
			addCriterion("cl_email is not null");
			return (Criteria) this;
		}

		public Criteria andClEmailEqualTo(String value) {
			addCriterion("cl_email =", value, "clEmail");
			return (Criteria) this;
		}

		public Criteria andClEmailNotEqualTo(String value) {
			addCriterion("cl_email <>", value, "clEmail");
			return (Criteria) this;
		}

		public Criteria andClEmailGreaterThan(String value) {
			addCriterion("cl_email >", value, "clEmail");
			return (Criteria) this;
		}

		public Criteria andClEmailGreaterThanOrEqualTo(String value) {
			addCriterion("cl_email >=", value, "clEmail");
			return (Criteria) this;
		}

		public Criteria andClEmailLessThan(String value) {
			addCriterion("cl_email <", value, "clEmail");
			return (Criteria) this;
		}

		public Criteria andClEmailLessThanOrEqualTo(String value) {
			addCriterion("cl_email <=", value, "clEmail");
			return (Criteria) this;
		}

		public Criteria andClEmailLike(String value) {
			addCriterion("cl_email like", value, "clEmail");
			return (Criteria) this;
		}

		public Criteria andClEmailNotLike(String value) {
			addCriterion("cl_email not like", value, "clEmail");
			return (Criteria) this;
		}

		public Criteria andClEmailIn(List<String> values) {
			addCriterion("cl_email in", values, "clEmail");
			return (Criteria) this;
		}

		public Criteria andClEmailNotIn(List<String> values) {
			addCriterion("cl_email not in", values, "clEmail");
			return (Criteria) this;
		}

		public Criteria andClEmailBetween(String value1, String value2) {
			addCriterion("cl_email between", value1, value2, "clEmail");
			return (Criteria) this;
		}

		public Criteria andClEmailNotBetween(String value1, String value2) {
			addCriterion("cl_email not between", value1, value2, "clEmail");
			return (Criteria) this;
		}

		public Criteria andClLegalPersonIsNull() {
			addCriterion("cl_legal_person is null");
			return (Criteria) this;
		}

		public Criteria andClLegalPersonIsNotNull() {
			addCriterion("cl_legal_person is not null");
			return (Criteria) this;
		}

		public Criteria andClLegalPersonEqualTo(String value) {
			addCriterion("cl_legal_person =", value, "clLegalPerson");
			return (Criteria) this;
		}

		public Criteria andClLegalPersonNotEqualTo(String value) {
			addCriterion("cl_legal_person <>", value, "clLegalPerson");
			return (Criteria) this;
		}

		public Criteria andClLegalPersonGreaterThan(String value) {
			addCriterion("cl_legal_person >", value, "clLegalPerson");
			return (Criteria) this;
		}

		public Criteria andClLegalPersonGreaterThanOrEqualTo(String value) {
			addCriterion("cl_legal_person >=", value, "clLegalPerson");
			return (Criteria) this;
		}

		public Criteria andClLegalPersonLessThan(String value) {
			addCriterion("cl_legal_person <", value, "clLegalPerson");
			return (Criteria) this;
		}

		public Criteria andClLegalPersonLessThanOrEqualTo(String value) {
			addCriterion("cl_legal_person <=", value, "clLegalPerson");
			return (Criteria) this;
		}

		public Criteria andClLegalPersonLike(String value) {
			addCriterion("cl_legal_person like", value, "clLegalPerson");
			return (Criteria) this;
		}

		public Criteria andClLegalPersonNotLike(String value) {
			addCriterion("cl_legal_person not like", value, "clLegalPerson");
			return (Criteria) this;
		}

		public Criteria andClLegalPersonIn(List<String> values) {
			addCriterion("cl_legal_person in", values, "clLegalPerson");
			return (Criteria) this;
		}

		public Criteria andClLegalPersonNotIn(List<String> values) {
			addCriterion("cl_legal_person not in", values, "clLegalPerson");
			return (Criteria) this;
		}

		public Criteria andClLegalPersonBetween(String value1, String value2) {
			addCriterion("cl_legal_person between", value1, value2, "clLegalPerson");
			return (Criteria) this;
		}

		public Criteria andClLegalPersonNotBetween(String value1, String value2) {
			addCriterion("cl_legal_person not between", value1, value2, "clLegalPerson");
			return (Criteria) this;
		}

		public Criteria andClIntroIsNull() {
			addCriterion("cl_intro is null");
			return (Criteria) this;
		}

		public Criteria andClIntroIsNotNull() {
			addCriterion("cl_intro is not null");
			return (Criteria) this;
		}

		public Criteria andClIntroEqualTo(String value) {
			addCriterion("cl_intro =", value, "clIntro");
			return (Criteria) this;
		}

		public Criteria andClIntroNotEqualTo(String value) {
			addCriterion("cl_intro <>", value, "clIntro");
			return (Criteria) this;
		}

		public Criteria andClIntroGreaterThan(String value) {
			addCriterion("cl_intro >", value, "clIntro");
			return (Criteria) this;
		}

		public Criteria andClIntroGreaterThanOrEqualTo(String value) {
			addCriterion("cl_intro >=", value, "clIntro");
			return (Criteria) this;
		}

		public Criteria andClIntroLessThan(String value) {
			addCriterion("cl_intro <", value, "clIntro");
			return (Criteria) this;
		}

		public Criteria andClIntroLessThanOrEqualTo(String value) {
			addCriterion("cl_intro <=", value, "clIntro");
			return (Criteria) this;
		}

		public Criteria andClIntroLike(String value) {
			addCriterion("cl_intro like", value, "clIntro");
			return (Criteria) this;
		}

		public Criteria andClIntroNotLike(String value) {
			addCriterion("cl_intro not like", value, "clIntro");
			return (Criteria) this;
		}

		public Criteria andClIntroIn(List<String> values) {
			addCriterion("cl_intro in", values, "clIntro");
			return (Criteria) this;
		}

		public Criteria andClIntroNotIn(List<String> values) {
			addCriterion("cl_intro not in", values, "clIntro");
			return (Criteria) this;
		}

		public Criteria andClIntroBetween(String value1, String value2) {
			addCriterion("cl_intro between", value1, value2, "clIntro");
			return (Criteria) this;
		}

		public Criteria andClIntroNotBetween(String value1, String value2) {
			addCriterion("cl_intro not between", value1, value2, "clIntro");
			return (Criteria) this;
		}

		public Criteria andClRegisteredCapitalIsNull() {
			addCriterion("cl_registered_capital is null");
			return (Criteria) this;
		}

		public Criteria andClRegisteredCapitalIsNotNull() {
			addCriterion("cl_registered_capital is not null");
			return (Criteria) this;
		}

		public Criteria andClRegisteredCapitalEqualTo(BigDecimal value) {
			addCriterion("cl_registered_capital =", value, "clRegisteredCapital");
			return (Criteria) this;
		}

		public Criteria andClRegisteredCapitalNotEqualTo(BigDecimal value) {
			addCriterion("cl_registered_capital <>", value, "clRegisteredCapital");
			return (Criteria) this;
		}

		public Criteria andClRegisteredCapitalGreaterThan(BigDecimal value) {
			addCriterion("cl_registered_capital >", value, "clRegisteredCapital");
			return (Criteria) this;
		}

		public Criteria andClRegisteredCapitalGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("cl_registered_capital >=", value, "clRegisteredCapital");
			return (Criteria) this;
		}

		public Criteria andClRegisteredCapitalLessThan(BigDecimal value) {
			addCriterion("cl_registered_capital <", value, "clRegisteredCapital");
			return (Criteria) this;
		}

		public Criteria andClRegisteredCapitalLessThanOrEqualTo(BigDecimal value) {
			addCriterion("cl_registered_capital <=", value, "clRegisteredCapital");
			return (Criteria) this;
		}

		public Criteria andClRegisteredCapitalIn(List<BigDecimal> values) {
			addCriterion("cl_registered_capital in", values, "clRegisteredCapital");
			return (Criteria) this;
		}

		public Criteria andClRegisteredCapitalNotIn(List<BigDecimal> values) {
			addCriterion("cl_registered_capital not in", values, "clRegisteredCapital");
			return (Criteria) this;
		}

		public Criteria andClRegisteredCapitalBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("cl_registered_capital between", value1, value2, "clRegisteredCapital");
			return (Criteria) this;
		}

		public Criteria andClRegisteredCapitalNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("cl_registered_capital not between", value1, value2, "clRegisteredCapital");
			return (Criteria) this;
		}

		public Criteria andClAssetSizeIsNull() {
			addCriterion("cl_asset_size is null");
			return (Criteria) this;
		}

		public Criteria andClAssetSizeIsNotNull() {
			addCriterion("cl_asset_size is not null");
			return (Criteria) this;
		}

		public Criteria andClAssetSizeEqualTo(BigDecimal value) {
			addCriterion("cl_asset_size =", value, "clAssetSize");
			return (Criteria) this;
		}

		public Criteria andClAssetSizeNotEqualTo(BigDecimal value) {
			addCriterion("cl_asset_size <>", value, "clAssetSize");
			return (Criteria) this;
		}

		public Criteria andClAssetSizeGreaterThan(BigDecimal value) {
			addCriterion("cl_asset_size >", value, "clAssetSize");
			return (Criteria) this;
		}

		public Criteria andClAssetSizeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("cl_asset_size >=", value, "clAssetSize");
			return (Criteria) this;
		}

		public Criteria andClAssetSizeLessThan(BigDecimal value) {
			addCriterion("cl_asset_size <", value, "clAssetSize");
			return (Criteria) this;
		}

		public Criteria andClAssetSizeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("cl_asset_size <=", value, "clAssetSize");
			return (Criteria) this;
		}

		public Criteria andClAssetSizeIn(List<BigDecimal> values) {
			addCriterion("cl_asset_size in", values, "clAssetSize");
			return (Criteria) this;
		}

		public Criteria andClAssetSizeNotIn(List<BigDecimal> values) {
			addCriterion("cl_asset_size not in", values, "clAssetSize");
			return (Criteria) this;
		}

		public Criteria andClAssetSizeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("cl_asset_size between", value1, value2, "clAssetSize");
			return (Criteria) this;
		}

		public Criteria andClAssetSizeNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("cl_asset_size not between", value1, value2, "clAssetSize");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeIsNull() {
			addCriterion("cl_create_time is null");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeIsNotNull() {
			addCriterion("cl_create_time is not null");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeEqualTo(Date value) {
			addCriterion("cl_create_time =", value, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeNotEqualTo(Date value) {
			addCriterion("cl_create_time <>", value, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeGreaterThan(Date value) {
			addCriterion("cl_create_time >", value, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("cl_create_time >=", value, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeLessThan(Date value) {
			addCriterion("cl_create_time <", value, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("cl_create_time <=", value, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeIn(List<Date> values) {
			addCriterion("cl_create_time in", values, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeNotIn(List<Date> values) {
			addCriterion("cl_create_time not in", values, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeBetween(Date value1, Date value2) {
			addCriterion("cl_create_time between", value1, value2, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("cl_create_time not between", value1, value2, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateByIsNull() {
			addCriterion("cl_create_by is null");
			return (Criteria) this;
		}

		public Criteria andClCreateByIsNotNull() {
			addCriterion("cl_create_by is not null");
			return (Criteria) this;
		}

		public Criteria andClCreateByEqualTo(String value) {
			addCriterion("cl_create_by =", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByNotEqualTo(String value) {
			addCriterion("cl_create_by <>", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByGreaterThan(String value) {
			addCriterion("cl_create_by >", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByGreaterThanOrEqualTo(String value) {
			addCriterion("cl_create_by >=", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByLessThan(String value) {
			addCriterion("cl_create_by <", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByLessThanOrEqualTo(String value) {
			addCriterion("cl_create_by <=", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByLike(String value) {
			addCriterion("cl_create_by like", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByNotLike(String value) {
			addCriterion("cl_create_by not like", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByIn(List<String> values) {
			addCriterion("cl_create_by in", values, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByNotIn(List<String> values) {
			addCriterion("cl_create_by not in", values, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByBetween(String value1, String value2) {
			addCriterion("cl_create_by between", value1, value2, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByNotBetween(String value1, String value2) {
			addCriterion("cl_create_by not between", value1, value2, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeIsNull() {
			addCriterion("cl_modify_time is null");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeIsNotNull() {
			addCriterion("cl_modify_time is not null");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeEqualTo(Date value) {
			addCriterion("cl_modify_time =", value, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeNotEqualTo(Date value) {
			addCriterion("cl_modify_time <>", value, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeGreaterThan(Date value) {
			addCriterion("cl_modify_time >", value, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("cl_modify_time >=", value, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeLessThan(Date value) {
			addCriterion("cl_modify_time <", value, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("cl_modify_time <=", value, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeIn(List<Date> values) {
			addCriterion("cl_modify_time in", values, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeNotIn(List<Date> values) {
			addCriterion("cl_modify_time not in", values, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeBetween(Date value1, Date value2) {
			addCriterion("cl_modify_time between", value1, value2, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("cl_modify_time not between", value1, value2, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyByIsNull() {
			addCriterion("cl_modify_by is null");
			return (Criteria) this;
		}

		public Criteria andClModifyByIsNotNull() {
			addCriterion("cl_modify_by is not null");
			return (Criteria) this;
		}

		public Criteria andClModifyByEqualTo(String value) {
			addCriterion("cl_modify_by =", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByNotEqualTo(String value) {
			addCriterion("cl_modify_by <>", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByGreaterThan(String value) {
			addCriterion("cl_modify_by >", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByGreaterThanOrEqualTo(String value) {
			addCriterion("cl_modify_by >=", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByLessThan(String value) {
			addCriterion("cl_modify_by <", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByLessThanOrEqualTo(String value) {
			addCriterion("cl_modify_by <=", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByLike(String value) {
			addCriterion("cl_modify_by like", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByNotLike(String value) {
			addCriterion("cl_modify_by not like", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByIn(List<String> values) {
			addCriterion("cl_modify_by in", values, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByNotIn(List<String> values) {
			addCriterion("cl_modify_by not in", values, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByBetween(String value1, String value2) {
			addCriterion("cl_modify_by between", value1, value2, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByNotBetween(String value1, String value2) {
			addCriterion("cl_modify_by not between", value1, value2, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClLogoIsNull() {
			addCriterion("cl_logo is null");
			return (Criteria) this;
		}

		public Criteria andClLogoIsNotNull() {
			addCriterion("cl_logo is not null");
			return (Criteria) this;
		}

		public Criteria andClLogoEqualTo(String value) {
			addCriterion("cl_logo =", value, "clLogo");
			return (Criteria) this;
		}

		public Criteria andClLogoNotEqualTo(String value) {
			addCriterion("cl_logo <>", value, "clLogo");
			return (Criteria) this;
		}

		public Criteria andClLogoGreaterThan(String value) {
			addCriterion("cl_logo >", value, "clLogo");
			return (Criteria) this;
		}

		public Criteria andClLogoGreaterThanOrEqualTo(String value) {
			addCriterion("cl_logo >=", value, "clLogo");
			return (Criteria) this;
		}

		public Criteria andClLogoLessThan(String value) {
			addCriterion("cl_logo <", value, "clLogo");
			return (Criteria) this;
		}

		public Criteria andClLogoLessThanOrEqualTo(String value) {
			addCriterion("cl_logo <=", value, "clLogo");
			return (Criteria) this;
		}

		public Criteria andClLogoLike(String value) {
			addCriterion("cl_logo like", value, "clLogo");
			return (Criteria) this;
		}

		public Criteria andClLogoNotLike(String value) {
			addCriterion("cl_logo not like", value, "clLogo");
			return (Criteria) this;
		}

		public Criteria andClLogoIn(List<String> values) {
			addCriterion("cl_logo in", values, "clLogo");
			return (Criteria) this;
		}

		public Criteria andClLogoNotIn(List<String> values) {
			addCriterion("cl_logo not in", values, "clLogo");
			return (Criteria) this;
		}

		public Criteria andClLogoBetween(String value1, String value2) {
			addCriterion("cl_logo between", value1, value2, "clLogo");
			return (Criteria) this;
		}

		public Criteria andClLogoNotBetween(String value1, String value2) {
			addCriterion("cl_logo not between", value1, value2, "clLogo");
			return (Criteria) this;
		}

		public Criteria andClCountryCodeIsNull() {
			addCriterion("cl_country_code is null");
			return (Criteria) this;
		}

		public Criteria andClCountryCodeIsNotNull() {
			addCriterion("cl_country_code is not null");
			return (Criteria) this;
		}

		public Criteria andClCountryCodeEqualTo(String value) {
			addCriterion("cl_country_code =", value, "clCountryCode");
			return (Criteria) this;
		}

		public Criteria andClCountryCodeNotEqualTo(String value) {
			addCriterion("cl_country_code <>", value, "clCountryCode");
			return (Criteria) this;
		}

		public Criteria andClCountryCodeGreaterThan(String value) {
			addCriterion("cl_country_code >", value, "clCountryCode");
			return (Criteria) this;
		}

		public Criteria andClCountryCodeGreaterThanOrEqualTo(String value) {
			addCriterion("cl_country_code >=", value, "clCountryCode");
			return (Criteria) this;
		}

		public Criteria andClCountryCodeLessThan(String value) {
			addCriterion("cl_country_code <", value, "clCountryCode");
			return (Criteria) this;
		}

		public Criteria andClCountryCodeLessThanOrEqualTo(String value) {
			addCriterion("cl_country_code <=", value, "clCountryCode");
			return (Criteria) this;
		}

		public Criteria andClCountryCodeLike(String value) {
			addCriterion("cl_country_code like", value, "clCountryCode");
			return (Criteria) this;
		}

		public Criteria andClCountryCodeNotLike(String value) {
			addCriterion("cl_country_code not like", value, "clCountryCode");
			return (Criteria) this;
		}

		public Criteria andClCountryCodeIn(List<String> values) {
			addCriterion("cl_country_code in", values, "clCountryCode");
			return (Criteria) this;
		}

		public Criteria andClCountryCodeNotIn(List<String> values) {
			addCriterion("cl_country_code not in", values, "clCountryCode");
			return (Criteria) this;
		}

		public Criteria andClCountryCodeBetween(String value1, String value2) {
			addCriterion("cl_country_code between", value1, value2, "clCountryCode");
			return (Criteria) this;
		}

		public Criteria andClCountryCodeNotBetween(String value1, String value2) {
			addCriterion("cl_country_code not between", value1, value2, "clCountryCode");
			return (Criteria) this;
		}

		public Criteria andClProvinceCodeIsNull() {
			addCriterion("cl_province_code is null");
			return (Criteria) this;
		}

		public Criteria andClProvinceCodeIsNotNull() {
			addCriterion("cl_province_code is not null");
			return (Criteria) this;
		}

		public Criteria andClProvinceCodeEqualTo(String value) {
			addCriterion("cl_province_code =", value, "clProvinceCode");
			return (Criteria) this;
		}

		public Criteria andClProvinceCodeNotEqualTo(String value) {
			addCriterion("cl_province_code <>", value, "clProvinceCode");
			return (Criteria) this;
		}

		public Criteria andClProvinceCodeGreaterThan(String value) {
			addCriterion("cl_province_code >", value, "clProvinceCode");
			return (Criteria) this;
		}

		public Criteria andClProvinceCodeGreaterThanOrEqualTo(String value) {
			addCriterion("cl_province_code >=", value, "clProvinceCode");
			return (Criteria) this;
		}

		public Criteria andClProvinceCodeLessThan(String value) {
			addCriterion("cl_province_code <", value, "clProvinceCode");
			return (Criteria) this;
		}

		public Criteria andClProvinceCodeLessThanOrEqualTo(String value) {
			addCriterion("cl_province_code <=", value, "clProvinceCode");
			return (Criteria) this;
		}

		public Criteria andClProvinceCodeLike(String value) {
			addCriterion("cl_province_code like", value, "clProvinceCode");
			return (Criteria) this;
		}

		public Criteria andClProvinceCodeNotLike(String value) {
			addCriterion("cl_province_code not like", value, "clProvinceCode");
			return (Criteria) this;
		}

		public Criteria andClProvinceCodeIn(List<String> values) {
			addCriterion("cl_province_code in", values, "clProvinceCode");
			return (Criteria) this;
		}

		public Criteria andClProvinceCodeNotIn(List<String> values) {
			addCriterion("cl_province_code not in", values, "clProvinceCode");
			return (Criteria) this;
		}

		public Criteria andClProvinceCodeBetween(String value1, String value2) {
			addCriterion("cl_province_code between", value1, value2, "clProvinceCode");
			return (Criteria) this;
		}

		public Criteria andClProvinceCodeNotBetween(String value1, String value2) {
			addCriterion("cl_province_code not between", value1, value2, "clProvinceCode");
			return (Criteria) this;
		}

		public Criteria andClCityCodeIsNull() {
			addCriterion("cl_city_code is null");
			return (Criteria) this;
		}

		public Criteria andClCityCodeIsNotNull() {
			addCriterion("cl_city_code is not null");
			return (Criteria) this;
		}

		public Criteria andClCityCodeEqualTo(String value) {
			addCriterion("cl_city_code =", value, "clCityCode");
			return (Criteria) this;
		}

		public Criteria andClCityCodeNotEqualTo(String value) {
			addCriterion("cl_city_code <>", value, "clCityCode");
			return (Criteria) this;
		}

		public Criteria andClCityCodeGreaterThan(String value) {
			addCriterion("cl_city_code >", value, "clCityCode");
			return (Criteria) this;
		}

		public Criteria andClCityCodeGreaterThanOrEqualTo(String value) {
			addCriterion("cl_city_code >=", value, "clCityCode");
			return (Criteria) this;
		}

		public Criteria andClCityCodeLessThan(String value) {
			addCriterion("cl_city_code <", value, "clCityCode");
			return (Criteria) this;
		}

		public Criteria andClCityCodeLessThanOrEqualTo(String value) {
			addCriterion("cl_city_code <=", value, "clCityCode");
			return (Criteria) this;
		}

		public Criteria andClCityCodeLike(String value) {
			addCriterion("cl_city_code like", value, "clCityCode");
			return (Criteria) this;
		}

		public Criteria andClCityCodeNotLike(String value) {
			addCriterion("cl_city_code not like", value, "clCityCode");
			return (Criteria) this;
		}

		public Criteria andClCityCodeIn(List<String> values) {
			addCriterion("cl_city_code in", values, "clCityCode");
			return (Criteria) this;
		}

		public Criteria andClCityCodeNotIn(List<String> values) {
			addCriterion("cl_city_code not in", values, "clCityCode");
			return (Criteria) this;
		}

		public Criteria andClCityCodeBetween(String value1, String value2) {
			addCriterion("cl_city_code between", value1, value2, "clCityCode");
			return (Criteria) this;
		}

		public Criteria andClCityCodeNotBetween(String value1, String value2) {
			addCriterion("cl_city_code not between", value1, value2, "clCityCode");
			return (Criteria) this;
		}

		public Criteria andClRegionIsNull() {
			addCriterion("cl_region is null");
			return (Criteria) this;
		}

		public Criteria andClRegionIsNotNull() {
			addCriterion("cl_region is not null");
			return (Criteria) this;
		}

		public Criteria andClRegionEqualTo(String value) {
			addCriterion("cl_region =", value, "clRegion");
			return (Criteria) this;
		}

		public Criteria andClRegionNotEqualTo(String value) {
			addCriterion("cl_region <>", value, "clRegion");
			return (Criteria) this;
		}

		public Criteria andClRegionGreaterThan(String value) {
			addCriterion("cl_region >", value, "clRegion");
			return (Criteria) this;
		}

		public Criteria andClRegionGreaterThanOrEqualTo(String value) {
			addCriterion("cl_region >=", value, "clRegion");
			return (Criteria) this;
		}

		public Criteria andClRegionLessThan(String value) {
			addCriterion("cl_region <", value, "clRegion");
			return (Criteria) this;
		}

		public Criteria andClRegionLessThanOrEqualTo(String value) {
			addCriterion("cl_region <=", value, "clRegion");
			return (Criteria) this;
		}

		public Criteria andClRegionLike(String value) {
			addCriterion("cl_region like", value, "clRegion");
			return (Criteria) this;
		}

		public Criteria andClRegionNotLike(String value) {
			addCriterion("cl_region not like", value, "clRegion");
			return (Criteria) this;
		}

		public Criteria andClRegionIn(List<String> values) {
			addCriterion("cl_region in", values, "clRegion");
			return (Criteria) this;
		}

		public Criteria andClRegionNotIn(List<String> values) {
			addCriterion("cl_region not in", values, "clRegion");
			return (Criteria) this;
		}

		public Criteria andClRegionBetween(String value1, String value2) {
			addCriterion("cl_region between", value1, value2, "clRegion");
			return (Criteria) this;
		}

		public Criteria andClRegionNotBetween(String value1, String value2) {
			addCriterion("cl_region not between", value1, value2, "clRegion");
			return (Criteria) this;
		}

		public Criteria andClWebsiteIsNull() {
			addCriterion("cl_website is null");
			return (Criteria) this;
		}

		public Criteria andClWebsiteIsNotNull() {
			addCriterion("cl_website is not null");
			return (Criteria) this;
		}

		public Criteria andClWebsiteEqualTo(String value) {
			addCriterion("cl_website =", value, "clWebsite");
			return (Criteria) this;
		}

		public Criteria andClWebsiteNotEqualTo(String value) {
			addCriterion("cl_website <>", value, "clWebsite");
			return (Criteria) this;
		}

		public Criteria andClWebsiteGreaterThan(String value) {
			addCriterion("cl_website >", value, "clWebsite");
			return (Criteria) this;
		}

		public Criteria andClWebsiteGreaterThanOrEqualTo(String value) {
			addCriterion("cl_website >=", value, "clWebsite");
			return (Criteria) this;
		}

		public Criteria andClWebsiteLessThan(String value) {
			addCriterion("cl_website <", value, "clWebsite");
			return (Criteria) this;
		}

		public Criteria andClWebsiteLessThanOrEqualTo(String value) {
			addCriterion("cl_website <=", value, "clWebsite");
			return (Criteria) this;
		}

		public Criteria andClWebsiteLike(String value) {
			addCriterion("cl_website like", value, "clWebsite");
			return (Criteria) this;
		}

		public Criteria andClWebsiteNotLike(String value) {
			addCriterion("cl_website not like", value, "clWebsite");
			return (Criteria) this;
		}

		public Criteria andClWebsiteIn(List<String> values) {
			addCriterion("cl_website in", values, "clWebsite");
			return (Criteria) this;
		}

		public Criteria andClWebsiteNotIn(List<String> values) {
			addCriterion("cl_website not in", values, "clWebsite");
			return (Criteria) this;
		}

		public Criteria andClWebsiteBetween(String value1, String value2) {
			addCriterion("cl_website between", value1, value2, "clWebsite");
			return (Criteria) this;
		}

		public Criteria andClWebsiteNotBetween(String value1, String value2) {
			addCriterion("cl_website not between", value1, value2, "clWebsite");
			return (Criteria) this;
		}

		public Criteria andClAddrEnIsNull() {
			addCriterion("cl_addr_en is null");
			return (Criteria) this;
		}

		public Criteria andClAddrEnIsNotNull() {
			addCriterion("cl_addr_en is not null");
			return (Criteria) this;
		}

		public Criteria andClAddrEnEqualTo(String value) {
			addCriterion("cl_addr_en =", value, "clAddrEn");
			return (Criteria) this;
		}

		public Criteria andClAddrEnNotEqualTo(String value) {
			addCriterion("cl_addr_en <>", value, "clAddrEn");
			return (Criteria) this;
		}

		public Criteria andClAddrEnGreaterThan(String value) {
			addCriterion("cl_addr_en >", value, "clAddrEn");
			return (Criteria) this;
		}

		public Criteria andClAddrEnGreaterThanOrEqualTo(String value) {
			addCriterion("cl_addr_en >=", value, "clAddrEn");
			return (Criteria) this;
		}

		public Criteria andClAddrEnLessThan(String value) {
			addCriterion("cl_addr_en <", value, "clAddrEn");
			return (Criteria) this;
		}

		public Criteria andClAddrEnLessThanOrEqualTo(String value) {
			addCriterion("cl_addr_en <=", value, "clAddrEn");
			return (Criteria) this;
		}

		public Criteria andClAddrEnLike(String value) {
			addCriterion("cl_addr_en like", value, "clAddrEn");
			return (Criteria) this;
		}

		public Criteria andClAddrEnNotLike(String value) {
			addCriterion("cl_addr_en not like", value, "clAddrEn");
			return (Criteria) this;
		}

		public Criteria andClAddrEnIn(List<String> values) {
			addCriterion("cl_addr_en in", values, "clAddrEn");
			return (Criteria) this;
		}

		public Criteria andClAddrEnNotIn(List<String> values) {
			addCriterion("cl_addr_en not in", values, "clAddrEn");
			return (Criteria) this;
		}

		public Criteria andClAddrEnBetween(String value1, String value2) {
			addCriterion("cl_addr_en between", value1, value2, "clAddrEn");
			return (Criteria) this;
		}

		public Criteria andClAddrEnNotBetween(String value1, String value2) {
			addCriterion("cl_addr_en not between", value1, value2, "clAddrEn");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table perms.perms_t_group_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table perms.perms_t_group_hotel
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 30 11:00:16 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}