package com.sstc.hmis.permission.dbaccess.data;

import java.math.BigDecimal;
import java.util.Date;

public class PermsTGroupHotel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_id
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_name
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_english_name
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clEnglishName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_status
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private Short clStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_blockup
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private Short clBlockup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_type
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private Short clType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_level
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private Short clLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_max_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private Integer clMaxHotel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_pid
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clPid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_country_id
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clCountryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_province_id
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clProvinceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_city_id
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clCityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_district
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clDistrict;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_address
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_admin_name
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clAdminName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_zip_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clZipCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_contacter
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clContacter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_contact_no
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clContactNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_fax
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clFax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_email
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_legal_person
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clLegalPerson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_intro
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clIntro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_registered_capital
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private BigDecimal clRegisteredCapital;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_asset_size
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private BigDecimal clAssetSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_create_time
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private Date clCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_create_by
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clCreateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_modify_time
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private Date clModifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_modify_by
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clModifyBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_logo
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clLogo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_country_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clCountryCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_province_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clProvinceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_city_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clCityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_region
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clRegion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_website
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clWebsite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_group_hotel.cl_addr_en
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	private String clAddrEn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_id
	 * @return  the value of perms.perms_t_group_hotel.cl_id
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClId() {
		return clId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_id
	 * @param clId  the value for perms.perms_t_group_hotel.cl_id
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClId(String clId) {
		this.clId = clId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_name
	 * @return  the value of perms.perms_t_group_hotel.cl_name
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClName() {
		return clName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_name
	 * @param clName  the value for perms.perms_t_group_hotel.cl_name
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClName(String clName) {
		this.clName = clName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_english_name
	 * @return  the value of perms.perms_t_group_hotel.cl_english_name
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClEnglishName() {
		return clEnglishName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_english_name
	 * @param clEnglishName  the value for perms.perms_t_group_hotel.cl_english_name
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClEnglishName(String clEnglishName) {
		this.clEnglishName = clEnglishName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_code
	 * @return  the value of perms.perms_t_group_hotel.cl_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClCode() {
		return clCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_code
	 * @param clCode  the value for perms.perms_t_group_hotel.cl_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClCode(String clCode) {
		this.clCode = clCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_status
	 * @return  the value of perms.perms_t_group_hotel.cl_status
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public Short getClStatus() {
		return clStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_status
	 * @param clStatus  the value for perms.perms_t_group_hotel.cl_status
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClStatus(Short clStatus) {
		this.clStatus = clStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_blockup
	 * @return  the value of perms.perms_t_group_hotel.cl_blockup
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public Short getClBlockup() {
		return clBlockup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_blockup
	 * @param clBlockup  the value for perms.perms_t_group_hotel.cl_blockup
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClBlockup(Short clBlockup) {
		this.clBlockup = clBlockup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_type
	 * @return  the value of perms.perms_t_group_hotel.cl_type
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public Short getClType() {
		return clType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_type
	 * @param clType  the value for perms.perms_t_group_hotel.cl_type
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClType(Short clType) {
		this.clType = clType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_level
	 * @return  the value of perms.perms_t_group_hotel.cl_level
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public Short getClLevel() {
		return clLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_level
	 * @param clLevel  the value for perms.perms_t_group_hotel.cl_level
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClLevel(Short clLevel) {
		this.clLevel = clLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_max_hotel
	 * @return  the value of perms.perms_t_group_hotel.cl_max_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public Integer getClMaxHotel() {
		return clMaxHotel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_max_hotel
	 * @param clMaxHotel  the value for perms.perms_t_group_hotel.cl_max_hotel
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClMaxHotel(Integer clMaxHotel) {
		this.clMaxHotel = clMaxHotel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_pid
	 * @return  the value of perms.perms_t_group_hotel.cl_pid
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClPid() {
		return clPid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_pid
	 * @param clPid  the value for perms.perms_t_group_hotel.cl_pid
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClPid(String clPid) {
		this.clPid = clPid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_country_id
	 * @return  the value of perms.perms_t_group_hotel.cl_country_id
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClCountryId() {
		return clCountryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_country_id
	 * @param clCountryId  the value for perms.perms_t_group_hotel.cl_country_id
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClCountryId(String clCountryId) {
		this.clCountryId = clCountryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_province_id
	 * @return  the value of perms.perms_t_group_hotel.cl_province_id
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClProvinceId() {
		return clProvinceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_province_id
	 * @param clProvinceId  the value for perms.perms_t_group_hotel.cl_province_id
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClProvinceId(String clProvinceId) {
		this.clProvinceId = clProvinceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_city_id
	 * @return  the value of perms.perms_t_group_hotel.cl_city_id
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClCityId() {
		return clCityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_city_id
	 * @param clCityId  the value for perms.perms_t_group_hotel.cl_city_id
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClCityId(String clCityId) {
		this.clCityId = clCityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_district
	 * @return  the value of perms.perms_t_group_hotel.cl_district
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClDistrict() {
		return clDistrict;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_district
	 * @param clDistrict  the value for perms.perms_t_group_hotel.cl_district
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClDistrict(String clDistrict) {
		this.clDistrict = clDistrict;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_address
	 * @return  the value of perms.perms_t_group_hotel.cl_address
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClAddress() {
		return clAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_address
	 * @param clAddress  the value for perms.perms_t_group_hotel.cl_address
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClAddress(String clAddress) {
		this.clAddress = clAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_admin_name
	 * @return  the value of perms.perms_t_group_hotel.cl_admin_name
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClAdminName() {
		return clAdminName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_admin_name
	 * @param clAdminName  the value for perms.perms_t_group_hotel.cl_admin_name
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClAdminName(String clAdminName) {
		this.clAdminName = clAdminName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_zip_code
	 * @return  the value of perms.perms_t_group_hotel.cl_zip_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClZipCode() {
		return clZipCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_zip_code
	 * @param clZipCode  the value for perms.perms_t_group_hotel.cl_zip_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClZipCode(String clZipCode) {
		this.clZipCode = clZipCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_contacter
	 * @return  the value of perms.perms_t_group_hotel.cl_contacter
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClContacter() {
		return clContacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_contacter
	 * @param clContacter  the value for perms.perms_t_group_hotel.cl_contacter
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClContacter(String clContacter) {
		this.clContacter = clContacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_contact_no
	 * @return  the value of perms.perms_t_group_hotel.cl_contact_no
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClContactNo() {
		return clContactNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_contact_no
	 * @param clContactNo  the value for perms.perms_t_group_hotel.cl_contact_no
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClContactNo(String clContactNo) {
		this.clContactNo = clContactNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_fax
	 * @return  the value of perms.perms_t_group_hotel.cl_fax
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClFax() {
		return clFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_fax
	 * @param clFax  the value for perms.perms_t_group_hotel.cl_fax
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClFax(String clFax) {
		this.clFax = clFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_email
	 * @return  the value of perms.perms_t_group_hotel.cl_email
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClEmail() {
		return clEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_email
	 * @param clEmail  the value for perms.perms_t_group_hotel.cl_email
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClEmail(String clEmail) {
		this.clEmail = clEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_legal_person
	 * @return  the value of perms.perms_t_group_hotel.cl_legal_person
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClLegalPerson() {
		return clLegalPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_legal_person
	 * @param clLegalPerson  the value for perms.perms_t_group_hotel.cl_legal_person
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClLegalPerson(String clLegalPerson) {
		this.clLegalPerson = clLegalPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_intro
	 * @return  the value of perms.perms_t_group_hotel.cl_intro
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClIntro() {
		return clIntro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_intro
	 * @param clIntro  the value for perms.perms_t_group_hotel.cl_intro
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClIntro(String clIntro) {
		this.clIntro = clIntro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_registered_capital
	 * @return  the value of perms.perms_t_group_hotel.cl_registered_capital
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public BigDecimal getClRegisteredCapital() {
		return clRegisteredCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_registered_capital
	 * @param clRegisteredCapital  the value for perms.perms_t_group_hotel.cl_registered_capital
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClRegisteredCapital(BigDecimal clRegisteredCapital) {
		this.clRegisteredCapital = clRegisteredCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_asset_size
	 * @return  the value of perms.perms_t_group_hotel.cl_asset_size
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public BigDecimal getClAssetSize() {
		return clAssetSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_asset_size
	 * @param clAssetSize  the value for perms.perms_t_group_hotel.cl_asset_size
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClAssetSize(BigDecimal clAssetSize) {
		this.clAssetSize = clAssetSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_create_time
	 * @return  the value of perms.perms_t_group_hotel.cl_create_time
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public Date getClCreateTime() {
		return clCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_create_time
	 * @param clCreateTime  the value for perms.perms_t_group_hotel.cl_create_time
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClCreateTime(Date clCreateTime) {
		this.clCreateTime = clCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_create_by
	 * @return  the value of perms.perms_t_group_hotel.cl_create_by
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClCreateBy() {
		return clCreateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_create_by
	 * @param clCreateBy  the value for perms.perms_t_group_hotel.cl_create_by
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClCreateBy(String clCreateBy) {
		this.clCreateBy = clCreateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_modify_time
	 * @return  the value of perms.perms_t_group_hotel.cl_modify_time
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public Date getClModifyTime() {
		return clModifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_modify_time
	 * @param clModifyTime  the value for perms.perms_t_group_hotel.cl_modify_time
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClModifyTime(Date clModifyTime) {
		this.clModifyTime = clModifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_modify_by
	 * @return  the value of perms.perms_t_group_hotel.cl_modify_by
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClModifyBy() {
		return clModifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_modify_by
	 * @param clModifyBy  the value for perms.perms_t_group_hotel.cl_modify_by
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClModifyBy(String clModifyBy) {
		this.clModifyBy = clModifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_logo
	 * @return  the value of perms.perms_t_group_hotel.cl_logo
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClLogo() {
		return clLogo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_logo
	 * @param clLogo  the value for perms.perms_t_group_hotel.cl_logo
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClLogo(String clLogo) {
		this.clLogo = clLogo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_country_code
	 * @return  the value of perms.perms_t_group_hotel.cl_country_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClCountryCode() {
		return clCountryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_country_code
	 * @param clCountryCode  the value for perms.perms_t_group_hotel.cl_country_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClCountryCode(String clCountryCode) {
		this.clCountryCode = clCountryCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_province_code
	 * @return  the value of perms.perms_t_group_hotel.cl_province_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClProvinceCode() {
		return clProvinceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_province_code
	 * @param clProvinceCode  the value for perms.perms_t_group_hotel.cl_province_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClProvinceCode(String clProvinceCode) {
		this.clProvinceCode = clProvinceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_city_code
	 * @return  the value of perms.perms_t_group_hotel.cl_city_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClCityCode() {
		return clCityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_city_code
	 * @param clCityCode  the value for perms.perms_t_group_hotel.cl_city_code
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClCityCode(String clCityCode) {
		this.clCityCode = clCityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_region
	 * @return  the value of perms.perms_t_group_hotel.cl_region
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClRegion() {
		return clRegion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_region
	 * @param clRegion  the value for perms.perms_t_group_hotel.cl_region
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClRegion(String clRegion) {
		this.clRegion = clRegion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_website
	 * @return  the value of perms.perms_t_group_hotel.cl_website
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClWebsite() {
		return clWebsite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_website
	 * @param clWebsite  the value for perms.perms_t_group_hotel.cl_website
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClWebsite(String clWebsite) {
		this.clWebsite = clWebsite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_group_hotel.cl_addr_en
	 * @return  the value of perms.perms_t_group_hotel.cl_addr_en
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public String getClAddrEn() {
		return clAddrEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_group_hotel.cl_addr_en
	 * @param clAddrEn  the value for perms.perms_t_group_hotel.cl_addr_en
	 * @mbggenerated  Tue Nov 28 13:49:21 CST 2017
	 */
	public void setClAddrEn(String clAddrEn) {
		this.clAddrEn = clAddrEn;
	}
}