package com.sstc.hmis.permission.dbaccess.data;

import java.util.Date;
import java.util.List;

public class PermsTRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_role.cl_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	private String clId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_role.cl_name
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	private String clName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_role.cl_english_name
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	private String clEnglishName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_role.cl_status
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	private Short clStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_role.cl_blockup
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	private Short clBlockup;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_role.cl_belong_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	private String clBelongId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_role.cl_grp_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	private String clGrpId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_role.cl_hotel_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	private String clHotelId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_role.cl_org_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	private String clOrgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_role.cl_create_time
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	private Date clCreateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_role.cl_create_by
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	private String clCreateBy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_role.cl_modify_time
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	private Date clModifyTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_role.cl_modify_by
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	private String clModifyBy;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_role.cl_disaccount_rate
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	private Short clDisaccountRate;




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_role.cl_id
	 * @return  the value of perms.perms_t_role.cl_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public String getClId() {
		return clId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_role.cl_id
	 * @param clId  the value for perms.perms_t_role.cl_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setClId(String clId) {
		this.clId = clId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_role.cl_name
	 * @return  the value of perms.perms_t_role.cl_name
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public String getClName() {
		return clName;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_role.cl_name
	 * @param clName  the value for perms.perms_t_role.cl_name
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setClName(String clName) {
		this.clName = clName;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_role.cl_english_name
	 * @return  the value of perms.perms_t_role.cl_english_name
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public String getClEnglishName() {
		return clEnglishName;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_role.cl_english_name
	 * @param clEnglishName  the value for perms.perms_t_role.cl_english_name
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setClEnglishName(String clEnglishName) {
		this.clEnglishName = clEnglishName;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_role.cl_status
	 * @return  the value of perms.perms_t_role.cl_status
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public Short getClStatus() {
		return clStatus;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_role.cl_status
	 * @param clStatus  the value for perms.perms_t_role.cl_status
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setClStatus(Short clStatus) {
		this.clStatus = clStatus;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_role.cl_blockup
	 * @return  the value of perms.perms_t_role.cl_blockup
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public Short getClBlockup() {
		return clBlockup;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_role.cl_blockup
	 * @param clBlockup  the value for perms.perms_t_role.cl_blockup
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setClBlockup(Short clBlockup) {
		this.clBlockup = clBlockup;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_role.cl_belong_id
	 * @return  the value of perms.perms_t_role.cl_belong_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public String getClBelongId() {
		return clBelongId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_role.cl_belong_id
	 * @param clBelongId  the value for perms.perms_t_role.cl_belong_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setClBelongId(String clBelongId) {
		this.clBelongId = clBelongId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_role.cl_grp_id
	 * @return  the value of perms.perms_t_role.cl_grp_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public String getClGrpId() {
		return clGrpId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_role.cl_grp_id
	 * @param clGrpId  the value for perms.perms_t_role.cl_grp_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setClGrpId(String clGrpId) {
		this.clGrpId = clGrpId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_role.cl_hotel_id
	 * @return  the value of perms.perms_t_role.cl_hotel_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public String getClHotelId() {
		return clHotelId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_role.cl_hotel_id
	 * @param clHotelId  the value for perms.perms_t_role.cl_hotel_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setClHotelId(String clHotelId) {
		this.clHotelId = clHotelId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_role.cl_org_id
	 * @return  the value of perms.perms_t_role.cl_org_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public String getClOrgId() {
		return clOrgId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_role.cl_org_id
	 * @param clOrgId  the value for perms.perms_t_role.cl_org_id
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setClOrgId(String clOrgId) {
		this.clOrgId = clOrgId;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_role.cl_create_time
	 * @return  the value of perms.perms_t_role.cl_create_time
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public Date getClCreateTime() {
		return clCreateTime;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_role.cl_create_time
	 * @param clCreateTime  the value for perms.perms_t_role.cl_create_time
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setClCreateTime(Date clCreateTime) {
		this.clCreateTime = clCreateTime;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_role.cl_create_by
	 * @return  the value of perms.perms_t_role.cl_create_by
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public String getClCreateBy() {
		return clCreateBy;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_role.cl_create_by
	 * @param clCreateBy  the value for perms.perms_t_role.cl_create_by
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setClCreateBy(String clCreateBy) {
		this.clCreateBy = clCreateBy;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_role.cl_modify_time
	 * @return  the value of perms.perms_t_role.cl_modify_time
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public Date getClModifyTime() {
		return clModifyTime;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_role.cl_modify_time
	 * @param clModifyTime  the value for perms.perms_t_role.cl_modify_time
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setClModifyTime(Date clModifyTime) {
		this.clModifyTime = clModifyTime;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_role.cl_modify_by
	 * @return  the value of perms.perms_t_role.cl_modify_by
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public String getClModifyBy() {
		return clModifyBy;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_role.cl_modify_by
	 * @param clModifyBy  the value for perms.perms_t_role.cl_modify_by
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setClModifyBy(String clModifyBy) {
		this.clModifyBy = clModifyBy;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_role.cl_disaccount_rate
	 * @return  the value of perms.perms_t_role.cl_disaccount_rate
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public Short getClDisaccountRate() {
		return clDisaccountRate;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_role.cl_disaccount_rate
	 * @param clDisaccountRate  the value for perms.perms_t_role.cl_disaccount_rate
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setClDisaccountRate(Short clDisaccountRate) {
		this.clDisaccountRate = clDisaccountRate;
	}

	private String clCondition;
	
	private List<String> ids;
	
	private List<String> clStaffIdList;
	
	
	

	public List<String> getClStaffIdList() {
		return clStaffIdList;
	}


	public void setClStaffIdList(List<String> clStaffIdList) {
		this.clStaffIdList = clStaffIdList;
	}


	public List<String> getIds() {
		return ids;
	}


	public void setIds(List<String> ids) {
		this.ids = ids;
	}

	private String clBelongId2;
	
	
	public String getClBelongId2() {
		return clBelongId2;
	}


	public void setClBelongId2(String clBelongId2) {
		this.clBelongId2 = clBelongId2;
	}

	public String getClCondition() {
		return clCondition;
	}

	public void setClCondition(String clCondition) {
		this.clCondition = clCondition;
	}
}