package com.sstc.hmis.permission.dbaccess.data;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PermsTPermissionExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public PermsTPermissionExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> clSubUrlCriteria;
		protected List<Criterion> allCriteria;
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
			clSubUrlCriteria = new ArrayList<Criterion>();
		}

		public List<Criterion> getClSubUrlCriteria() {
			return clSubUrlCriteria;
		}

		protected void addClSubUrlCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			clSubUrlCriteria.add(new Criterion(condition, value, "com.sstc.hmis.dbaccess.mybatis.ArrayTypeHandler"));
			allCriteria = null;
		}

		protected void addClSubUrlCriterion(String condition, String[] value1, String[] value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			clSubUrlCriteria
					.add(new Criterion(condition, value1, value2, "com.sstc.hmis.dbaccess.mybatis.ArrayTypeHandler"));
			allCriteria = null;
		}

		public boolean isValid() {
			return criteria.size() > 0 || clSubUrlCriteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			if (allCriteria == null) {
				allCriteria = new ArrayList<Criterion>();
				allCriteria.addAll(criteria);
				allCriteria.addAll(clSubUrlCriteria);
			}
			return allCriteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
			allCriteria = null;
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
			allCriteria = null;
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
			allCriteria = null;
		}

		public Criteria andClIdIsNull() {
			addCriterion("cl_id is null");
			return (Criteria) this;
		}

		public Criteria andClIdIsNotNull() {
			addCriterion("cl_id is not null");
			return (Criteria) this;
		}

		public Criteria andClIdEqualTo(String value) {
			addCriterion("cl_id =", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdNotEqualTo(String value) {
			addCriterion("cl_id <>", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdGreaterThan(String value) {
			addCriterion("cl_id >", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdGreaterThanOrEqualTo(String value) {
			addCriterion("cl_id >=", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdLessThan(String value) {
			addCriterion("cl_id <", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdLessThanOrEqualTo(String value) {
			addCriterion("cl_id <=", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdLike(String value) {
			addCriterion("cl_id like", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdNotLike(String value) {
			addCriterion("cl_id not like", value, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdIn(List<String> values) {
			addCriterion("cl_id in", values, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdNotIn(List<String> values) {
			addCriterion("cl_id not in", values, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdBetween(String value1, String value2) {
			addCriterion("cl_id between", value1, value2, "clId");
			return (Criteria) this;
		}

		public Criteria andClIdNotBetween(String value1, String value2) {
			addCriterion("cl_id not between", value1, value2, "clId");
			return (Criteria) this;
		}

		public Criteria andClNameIsNull() {
			addCriterion("cl_name is null");
			return (Criteria) this;
		}

		public Criteria andClNameIsNotNull() {
			addCriterion("cl_name is not null");
			return (Criteria) this;
		}

		public Criteria andClNameEqualTo(String value) {
			addCriterion("cl_name =", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameNotEqualTo(String value) {
			addCriterion("cl_name <>", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameGreaterThan(String value) {
			addCriterion("cl_name >", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameGreaterThanOrEqualTo(String value) {
			addCriterion("cl_name >=", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameLessThan(String value) {
			addCriterion("cl_name <", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameLessThanOrEqualTo(String value) {
			addCriterion("cl_name <=", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameLike(String value) {
			addCriterion("cl_name like", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameNotLike(String value) {
			addCriterion("cl_name not like", value, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameIn(List<String> values) {
			addCriterion("cl_name in", values, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameNotIn(List<String> values) {
			addCriterion("cl_name not in", values, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameBetween(String value1, String value2) {
			addCriterion("cl_name between", value1, value2, "clName");
			return (Criteria) this;
		}

		public Criteria andClNameNotBetween(String value1, String value2) {
			addCriterion("cl_name not between", value1, value2, "clName");
			return (Criteria) this;
		}

		public Criteria andClTypeIsNull() {
			addCriterion("cl_type is null");
			return (Criteria) this;
		}

		public Criteria andClTypeIsNotNull() {
			addCriterion("cl_type is not null");
			return (Criteria) this;
		}

		public Criteria andClTypeEqualTo(Short value) {
			addCriterion("cl_type =", value, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeNotEqualTo(Short value) {
			addCriterion("cl_type <>", value, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeGreaterThan(Short value) {
			addCriterion("cl_type >", value, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeGreaterThanOrEqualTo(Short value) {
			addCriterion("cl_type >=", value, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeLessThan(Short value) {
			addCriterion("cl_type <", value, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeLessThanOrEqualTo(Short value) {
			addCriterion("cl_type <=", value, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeIn(List<Short> values) {
			addCriterion("cl_type in", values, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeNotIn(List<Short> values) {
			addCriterion("cl_type not in", values, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeBetween(Short value1, Short value2) {
			addCriterion("cl_type between", value1, value2, "clType");
			return (Criteria) this;
		}

		public Criteria andClTypeNotBetween(Short value1, Short value2) {
			addCriterion("cl_type not between", value1, value2, "clType");
			return (Criteria) this;
		}

		public Criteria andClStatusIsNull() {
			addCriterion("cl_status is null");
			return (Criteria) this;
		}

		public Criteria andClStatusIsNotNull() {
			addCriterion("cl_status is not null");
			return (Criteria) this;
		}

		public Criteria andClStatusEqualTo(Short value) {
			addCriterion("cl_status =", value, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusNotEqualTo(Short value) {
			addCriterion("cl_status <>", value, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusGreaterThan(Short value) {
			addCriterion("cl_status >", value, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("cl_status >=", value, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusLessThan(Short value) {
			addCriterion("cl_status <", value, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusLessThanOrEqualTo(Short value) {
			addCriterion("cl_status <=", value, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusIn(List<Short> values) {
			addCriterion("cl_status in", values, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusNotIn(List<Short> values) {
			addCriterion("cl_status not in", values, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusBetween(Short value1, Short value2) {
			addCriterion("cl_status between", value1, value2, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClStatusNotBetween(Short value1, Short value2) {
			addCriterion("cl_status not between", value1, value2, "clStatus");
			return (Criteria) this;
		}

		public Criteria andClBlockupIsNull() {
			addCriterion("cl_blockup is null");
			return (Criteria) this;
		}

		public Criteria andClBlockupIsNotNull() {
			addCriterion("cl_blockup is not null");
			return (Criteria) this;
		}

		public Criteria andClBlockupEqualTo(Short value) {
			addCriterion("cl_blockup =", value, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupNotEqualTo(Short value) {
			addCriterion("cl_blockup <>", value, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupGreaterThan(Short value) {
			addCriterion("cl_blockup >", value, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupGreaterThanOrEqualTo(Short value) {
			addCriterion("cl_blockup >=", value, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupLessThan(Short value) {
			addCriterion("cl_blockup <", value, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupLessThanOrEqualTo(Short value) {
			addCriterion("cl_blockup <=", value, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupIn(List<Short> values) {
			addCriterion("cl_blockup in", values, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupNotIn(List<Short> values) {
			addCriterion("cl_blockup not in", values, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupBetween(Short value1, Short value2) {
			addCriterion("cl_blockup between", value1, value2, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClBlockupNotBetween(Short value1, Short value2) {
			addCriterion("cl_blockup not between", value1, value2, "clBlockup");
			return (Criteria) this;
		}

		public Criteria andClUrlIsNull() {
			addCriterion("cl_url is null");
			return (Criteria) this;
		}

		public Criteria andClUrlIsNotNull() {
			addCriterion("cl_url is not null");
			return (Criteria) this;
		}

		public Criteria andClUrlEqualTo(String value) {
			addCriterion("cl_url =", value, "clUrl");
			return (Criteria) this;
		}

		public Criteria andClUrlNotEqualTo(String value) {
			addCriterion("cl_url <>", value, "clUrl");
			return (Criteria) this;
		}

		public Criteria andClUrlGreaterThan(String value) {
			addCriterion("cl_url >", value, "clUrl");
			return (Criteria) this;
		}

		public Criteria andClUrlGreaterThanOrEqualTo(String value) {
			addCriterion("cl_url >=", value, "clUrl");
			return (Criteria) this;
		}

		public Criteria andClUrlLessThan(String value) {
			addCriterion("cl_url <", value, "clUrl");
			return (Criteria) this;
		}

		public Criteria andClUrlLessThanOrEqualTo(String value) {
			addCriterion("cl_url <=", value, "clUrl");
			return (Criteria) this;
		}

		public Criteria andClUrlLike(String value) {
			addCriterion("cl_url like", value, "clUrl");
			return (Criteria) this;
		}

		public Criteria andClUrlNotLike(String value) {
			addCriterion("cl_url not like", value, "clUrl");
			return (Criteria) this;
		}

		public Criteria andClUrlIn(List<String> values) {
			addCriterion("cl_url in", values, "clUrl");
			return (Criteria) this;
		}

		public Criteria andClUrlNotIn(List<String> values) {
			addCriterion("cl_url not in", values, "clUrl");
			return (Criteria) this;
		}

		public Criteria andClUrlBetween(String value1, String value2) {
			addCriterion("cl_url between", value1, value2, "clUrl");
			return (Criteria) this;
		}

		public Criteria andClUrlNotBetween(String value1, String value2) {
			addCriterion("cl_url not between", value1, value2, "clUrl");
			return (Criteria) this;
		}

		public Criteria andClIsBaseIsNull() {
			addCriterion("cl_is_base is null");
			return (Criteria) this;
		}

		public Criteria andClIsBaseIsNotNull() {
			addCriterion("cl_is_base is not null");
			return (Criteria) this;
		}

		public Criteria andClIsBaseEqualTo(Short value) {
			addCriterion("cl_is_base =", value, "clIsBase");
			return (Criteria) this;
		}

		public Criteria andClIsBaseNotEqualTo(Short value) {
			addCriterion("cl_is_base <>", value, "clIsBase");
			return (Criteria) this;
		}

		public Criteria andClIsBaseGreaterThan(Short value) {
			addCriterion("cl_is_base >", value, "clIsBase");
			return (Criteria) this;
		}

		public Criteria andClIsBaseGreaterThanOrEqualTo(Short value) {
			addCriterion("cl_is_base >=", value, "clIsBase");
			return (Criteria) this;
		}

		public Criteria andClIsBaseLessThan(Short value) {
			addCriterion("cl_is_base <", value, "clIsBase");
			return (Criteria) this;
		}

		public Criteria andClIsBaseLessThanOrEqualTo(Short value) {
			addCriterion("cl_is_base <=", value, "clIsBase");
			return (Criteria) this;
		}

		public Criteria andClIsBaseIn(List<Short> values) {
			addCriterion("cl_is_base in", values, "clIsBase");
			return (Criteria) this;
		}

		public Criteria andClIsBaseNotIn(List<Short> values) {
			addCriterion("cl_is_base not in", values, "clIsBase");
			return (Criteria) this;
		}

		public Criteria andClIsBaseBetween(Short value1, Short value2) {
			addCriterion("cl_is_base between", value1, value2, "clIsBase");
			return (Criteria) this;
		}

		public Criteria andClIsBaseNotBetween(Short value1, Short value2) {
			addCriterion("cl_is_base not between", value1, value2, "clIsBase");
			return (Criteria) this;
		}

		public Criteria andClHasOthersIsNull() {
			addCriterion("cl_has_others is null");
			return (Criteria) this;
		}

		public Criteria andClHasOthersIsNotNull() {
			addCriterion("cl_has_others is not null");
			return (Criteria) this;
		}

		public Criteria andClHasOthersEqualTo(Short value) {
			addCriterion("cl_has_others =", value, "clHasOthers");
			return (Criteria) this;
		}

		public Criteria andClHasOthersNotEqualTo(Short value) {
			addCriterion("cl_has_others <>", value, "clHasOthers");
			return (Criteria) this;
		}

		public Criteria andClHasOthersGreaterThan(Short value) {
			addCriterion("cl_has_others >", value, "clHasOthers");
			return (Criteria) this;
		}

		public Criteria andClHasOthersGreaterThanOrEqualTo(Short value) {
			addCriterion("cl_has_others >=", value, "clHasOthers");
			return (Criteria) this;
		}

		public Criteria andClHasOthersLessThan(Short value) {
			addCriterion("cl_has_others <", value, "clHasOthers");
			return (Criteria) this;
		}

		public Criteria andClHasOthersLessThanOrEqualTo(Short value) {
			addCriterion("cl_has_others <=", value, "clHasOthers");
			return (Criteria) this;
		}

		public Criteria andClHasOthersIn(List<Short> values) {
			addCriterion("cl_has_others in", values, "clHasOthers");
			return (Criteria) this;
		}

		public Criteria andClHasOthersNotIn(List<Short> values) {
			addCriterion("cl_has_others not in", values, "clHasOthers");
			return (Criteria) this;
		}

		public Criteria andClHasOthersBetween(Short value1, Short value2) {
			addCriterion("cl_has_others between", value1, value2, "clHasOthers");
			return (Criteria) this;
		}

		public Criteria andClHasOthersNotBetween(Short value1, Short value2) {
			addCriterion("cl_has_others not between", value1, value2, "clHasOthers");
			return (Criteria) this;
		}

		public Criteria andClPidIsNull() {
			addCriterion("cl_pid is null");
			return (Criteria) this;
		}

		public Criteria andClPidIsNotNull() {
			addCriterion("cl_pid is not null");
			return (Criteria) this;
		}

		public Criteria andClPidEqualTo(String value) {
			addCriterion("cl_pid =", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidNotEqualTo(String value) {
			addCriterion("cl_pid <>", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidGreaterThan(String value) {
			addCriterion("cl_pid >", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidGreaterThanOrEqualTo(String value) {
			addCriterion("cl_pid >=", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidLessThan(String value) {
			addCriterion("cl_pid <", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidLessThanOrEqualTo(String value) {
			addCriterion("cl_pid <=", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidLike(String value) {
			addCriterion("cl_pid like", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidNotLike(String value) {
			addCriterion("cl_pid not like", value, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidIn(List<String> values) {
			addCriterion("cl_pid in", values, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidNotIn(List<String> values) {
			addCriterion("cl_pid not in", values, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidBetween(String value1, String value2) {
			addCriterion("cl_pid between", value1, value2, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPidNotBetween(String value1, String value2) {
			addCriterion("cl_pid not between", value1, value2, "clPid");
			return (Criteria) this;
		}

		public Criteria andClPriceIsNull() {
			addCriterion("cl_price is null");
			return (Criteria) this;
		}

		public Criteria andClPriceIsNotNull() {
			addCriterion("cl_price is not null");
			return (Criteria) this;
		}

		public Criteria andClPriceEqualTo(BigDecimal value) {
			addCriterion("cl_price =", value, "clPrice");
			return (Criteria) this;
		}

		public Criteria andClPriceNotEqualTo(BigDecimal value) {
			addCriterion("cl_price <>", value, "clPrice");
			return (Criteria) this;
		}

		public Criteria andClPriceGreaterThan(BigDecimal value) {
			addCriterion("cl_price >", value, "clPrice");
			return (Criteria) this;
		}

		public Criteria andClPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("cl_price >=", value, "clPrice");
			return (Criteria) this;
		}

		public Criteria andClPriceLessThan(BigDecimal value) {
			addCriterion("cl_price <", value, "clPrice");
			return (Criteria) this;
		}

		public Criteria andClPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("cl_price <=", value, "clPrice");
			return (Criteria) this;
		}

		public Criteria andClPriceIn(List<BigDecimal> values) {
			addCriterion("cl_price in", values, "clPrice");
			return (Criteria) this;
		}

		public Criteria andClPriceNotIn(List<BigDecimal> values) {
			addCriterion("cl_price not in", values, "clPrice");
			return (Criteria) this;
		}

		public Criteria andClPriceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("cl_price between", value1, value2, "clPrice");
			return (Criteria) this;
		}

		public Criteria andClPriceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("cl_price not between", value1, value2, "clPrice");
			return (Criteria) this;
		}

		public Criteria andClGrpIdIsNull() {
			addCriterion("cl_grp_id is null");
			return (Criteria) this;
		}

		public Criteria andClGrpIdIsNotNull() {
			addCriterion("cl_grp_id is not null");
			return (Criteria) this;
		}

		public Criteria andClGrpIdEqualTo(String value) {
			addCriterion("cl_grp_id =", value, "clGrpId");
			return (Criteria) this;
		}

		public Criteria andClGrpIdNotEqualTo(String value) {
			addCriterion("cl_grp_id <>", value, "clGrpId");
			return (Criteria) this;
		}

		public Criteria andClGrpIdGreaterThan(String value) {
			addCriterion("cl_grp_id >", value, "clGrpId");
			return (Criteria) this;
		}

		public Criteria andClGrpIdGreaterThanOrEqualTo(String value) {
			addCriterion("cl_grp_id >=", value, "clGrpId");
			return (Criteria) this;
		}

		public Criteria andClGrpIdLessThan(String value) {
			addCriterion("cl_grp_id <", value, "clGrpId");
			return (Criteria) this;
		}

		public Criteria andClGrpIdLessThanOrEqualTo(String value) {
			addCriterion("cl_grp_id <=", value, "clGrpId");
			return (Criteria) this;
		}

		public Criteria andClGrpIdLike(String value) {
			addCriterion("cl_grp_id like", value, "clGrpId");
			return (Criteria) this;
		}

		public Criteria andClGrpIdNotLike(String value) {
			addCriterion("cl_grp_id not like", value, "clGrpId");
			return (Criteria) this;
		}

		public Criteria andClGrpIdIn(List<String> values) {
			addCriterion("cl_grp_id in", values, "clGrpId");
			return (Criteria) this;
		}

		public Criteria andClGrpIdNotIn(List<String> values) {
			addCriterion("cl_grp_id not in", values, "clGrpId");
			return (Criteria) this;
		}

		public Criteria andClGrpIdBetween(String value1, String value2) {
			addCriterion("cl_grp_id between", value1, value2, "clGrpId");
			return (Criteria) this;
		}

		public Criteria andClGrpIdNotBetween(String value1, String value2) {
			addCriterion("cl_grp_id not between", value1, value2, "clGrpId");
			return (Criteria) this;
		}

		public Criteria andClHotelIdIsNull() {
			addCriterion("cl_hotel_id is null");
			return (Criteria) this;
		}

		public Criteria andClHotelIdIsNotNull() {
			addCriterion("cl_hotel_id is not null");
			return (Criteria) this;
		}

		public Criteria andClHotelIdEqualTo(String value) {
			addCriterion("cl_hotel_id =", value, "clHotelId");
			return (Criteria) this;
		}

		public Criteria andClHotelIdNotEqualTo(String value) {
			addCriterion("cl_hotel_id <>", value, "clHotelId");
			return (Criteria) this;
		}

		public Criteria andClHotelIdGreaterThan(String value) {
			addCriterion("cl_hotel_id >", value, "clHotelId");
			return (Criteria) this;
		}

		public Criteria andClHotelIdGreaterThanOrEqualTo(String value) {
			addCriterion("cl_hotel_id >=", value, "clHotelId");
			return (Criteria) this;
		}

		public Criteria andClHotelIdLessThan(String value) {
			addCriterion("cl_hotel_id <", value, "clHotelId");
			return (Criteria) this;
		}

		public Criteria andClHotelIdLessThanOrEqualTo(String value) {
			addCriterion("cl_hotel_id <=", value, "clHotelId");
			return (Criteria) this;
		}

		public Criteria andClHotelIdLike(String value) {
			addCriterion("cl_hotel_id like", value, "clHotelId");
			return (Criteria) this;
		}

		public Criteria andClHotelIdNotLike(String value) {
			addCriterion("cl_hotel_id not like", value, "clHotelId");
			return (Criteria) this;
		}

		public Criteria andClHotelIdIn(List<String> values) {
			addCriterion("cl_hotel_id in", values, "clHotelId");
			return (Criteria) this;
		}

		public Criteria andClHotelIdNotIn(List<String> values) {
			addCriterion("cl_hotel_id not in", values, "clHotelId");
			return (Criteria) this;
		}

		public Criteria andClHotelIdBetween(String value1, String value2) {
			addCriterion("cl_hotel_id between", value1, value2, "clHotelId");
			return (Criteria) this;
		}

		public Criteria andClHotelIdNotBetween(String value1, String value2) {
			addCriterion("cl_hotel_id not between", value1, value2, "clHotelId");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeIsNull() {
			addCriterion("cl_create_time is null");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeIsNotNull() {
			addCriterion("cl_create_time is not null");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeEqualTo(Date value) {
			addCriterion("cl_create_time =", value, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeNotEqualTo(Date value) {
			addCriterion("cl_create_time <>", value, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeGreaterThan(Date value) {
			addCriterion("cl_create_time >", value, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("cl_create_time >=", value, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeLessThan(Date value) {
			addCriterion("cl_create_time <", value, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("cl_create_time <=", value, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeIn(List<Date> values) {
			addCriterion("cl_create_time in", values, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeNotIn(List<Date> values) {
			addCriterion("cl_create_time not in", values, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeBetween(Date value1, Date value2) {
			addCriterion("cl_create_time between", value1, value2, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("cl_create_time not between", value1, value2, "clCreateTime");
			return (Criteria) this;
		}

		public Criteria andClCreateByIsNull() {
			addCriterion("cl_create_by is null");
			return (Criteria) this;
		}

		public Criteria andClCreateByIsNotNull() {
			addCriterion("cl_create_by is not null");
			return (Criteria) this;
		}

		public Criteria andClCreateByEqualTo(String value) {
			addCriterion("cl_create_by =", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByNotEqualTo(String value) {
			addCriterion("cl_create_by <>", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByGreaterThan(String value) {
			addCriterion("cl_create_by >", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByGreaterThanOrEqualTo(String value) {
			addCriterion("cl_create_by >=", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByLessThan(String value) {
			addCriterion("cl_create_by <", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByLessThanOrEqualTo(String value) {
			addCriterion("cl_create_by <=", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByLike(String value) {
			addCriterion("cl_create_by like", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByNotLike(String value) {
			addCriterion("cl_create_by not like", value, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByIn(List<String> values) {
			addCriterion("cl_create_by in", values, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByNotIn(List<String> values) {
			addCriterion("cl_create_by not in", values, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByBetween(String value1, String value2) {
			addCriterion("cl_create_by between", value1, value2, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClCreateByNotBetween(String value1, String value2) {
			addCriterion("cl_create_by not between", value1, value2, "clCreateBy");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeIsNull() {
			addCriterion("cl_modify_time is null");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeIsNotNull() {
			addCriterion("cl_modify_time is not null");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeEqualTo(Date value) {
			addCriterion("cl_modify_time =", value, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeNotEqualTo(Date value) {
			addCriterion("cl_modify_time <>", value, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeGreaterThan(Date value) {
			addCriterion("cl_modify_time >", value, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("cl_modify_time >=", value, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeLessThan(Date value) {
			addCriterion("cl_modify_time <", value, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("cl_modify_time <=", value, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeIn(List<Date> values) {
			addCriterion("cl_modify_time in", values, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeNotIn(List<Date> values) {
			addCriterion("cl_modify_time not in", values, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeBetween(Date value1, Date value2) {
			addCriterion("cl_modify_time between", value1, value2, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("cl_modify_time not between", value1, value2, "clModifyTime");
			return (Criteria) this;
		}

		public Criteria andClModifyByIsNull() {
			addCriterion("cl_modify_by is null");
			return (Criteria) this;
		}

		public Criteria andClModifyByIsNotNull() {
			addCriterion("cl_modify_by is not null");
			return (Criteria) this;
		}

		public Criteria andClModifyByEqualTo(String value) {
			addCriterion("cl_modify_by =", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByNotEqualTo(String value) {
			addCriterion("cl_modify_by <>", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByGreaterThan(String value) {
			addCriterion("cl_modify_by >", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByGreaterThanOrEqualTo(String value) {
			addCriterion("cl_modify_by >=", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByLessThan(String value) {
			addCriterion("cl_modify_by <", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByLessThanOrEqualTo(String value) {
			addCriterion("cl_modify_by <=", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByLike(String value) {
			addCriterion("cl_modify_by like", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByNotLike(String value) {
			addCriterion("cl_modify_by not like", value, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByIn(List<String> values) {
			addCriterion("cl_modify_by in", values, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByNotIn(List<String> values) {
			addCriterion("cl_modify_by not in", values, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByBetween(String value1, String value2) {
			addCriterion("cl_modify_by between", value1, value2, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClModifyByNotBetween(String value1, String value2) {
			addCriterion("cl_modify_by not between", value1, value2, "clModifyBy");
			return (Criteria) this;
		}

		public Criteria andClSubUrlIsNull() {
			addCriterion("cl_sub_url is null");
			return (Criteria) this;
		}

		public Criteria andClSubUrlIsNotNull() {
			addCriterion("cl_sub_url is not null");
			return (Criteria) this;
		}

		public Criteria andClSubUrlEqualTo(String[] value) {
			addClSubUrlCriterion("cl_sub_url =", value, "clSubUrl");
			return (Criteria) this;
		}

		public Criteria andClSubUrlNotEqualTo(String[] value) {
			addClSubUrlCriterion("cl_sub_url <>", value, "clSubUrl");
			return (Criteria) this;
		}

		public Criteria andClSubUrlGreaterThan(String[] value) {
			addClSubUrlCriterion("cl_sub_url >", value, "clSubUrl");
			return (Criteria) this;
		}

		public Criteria andClSubUrlGreaterThanOrEqualTo(String[] value) {
			addClSubUrlCriterion("cl_sub_url >=", value, "clSubUrl");
			return (Criteria) this;
		}

		public Criteria andClSubUrlLessThan(String[] value) {
			addClSubUrlCriterion("cl_sub_url <", value, "clSubUrl");
			return (Criteria) this;
		}

		public Criteria andClSubUrlLessThanOrEqualTo(String[] value) {
			addClSubUrlCriterion("cl_sub_url <=", value, "clSubUrl");
			return (Criteria) this;
		}

		public Criteria andClSubUrlIn(List<String[]> values) {
			addClSubUrlCriterion("cl_sub_url in", values, "clSubUrl");
			return (Criteria) this;
		}

		public Criteria andClSubUrlNotIn(List<String[]> values) {
			addClSubUrlCriterion("cl_sub_url not in", values, "clSubUrl");
			return (Criteria) this;
		}

		public Criteria andClSubUrlBetween(String[] value1, String[] value2) {
			addClSubUrlCriterion("cl_sub_url between", value1, value2, "clSubUrl");
			return (Criteria) this;
		}

		public Criteria andClSubUrlNotBetween(String[] value1, String[] value2) {
			addClSubUrlCriterion("cl_sub_url not between", value1, value2, "clSubUrl");
			return (Criteria) this;
		}

		public Criteria andClIconClassIsNull() {
			addCriterion("cl_icon_class is null");
			return (Criteria) this;
		}

		public Criteria andClIconClassIsNotNull() {
			addCriterion("cl_icon_class is not null");
			return (Criteria) this;
		}

		public Criteria andClIconClassEqualTo(String value) {
			addCriterion("cl_icon_class =", value, "clIconClass");
			return (Criteria) this;
		}

		public Criteria andClIconClassNotEqualTo(String value) {
			addCriterion("cl_icon_class <>", value, "clIconClass");
			return (Criteria) this;
		}

		public Criteria andClIconClassGreaterThan(String value) {
			addCriterion("cl_icon_class >", value, "clIconClass");
			return (Criteria) this;
		}

		public Criteria andClIconClassGreaterThanOrEqualTo(String value) {
			addCriterion("cl_icon_class >=", value, "clIconClass");
			return (Criteria) this;
		}

		public Criteria andClIconClassLessThan(String value) {
			addCriterion("cl_icon_class <", value, "clIconClass");
			return (Criteria) this;
		}

		public Criteria andClIconClassLessThanOrEqualTo(String value) {
			addCriterion("cl_icon_class <=", value, "clIconClass");
			return (Criteria) this;
		}

		public Criteria andClIconClassLike(String value) {
			addCriterion("cl_icon_class like", value, "clIconClass");
			return (Criteria) this;
		}

		public Criteria andClIconClassNotLike(String value) {
			addCriterion("cl_icon_class not like", value, "clIconClass");
			return (Criteria) this;
		}

		public Criteria andClIconClassIn(List<String> values) {
			addCriterion("cl_icon_class in", values, "clIconClass");
			return (Criteria) this;
		}

		public Criteria andClIconClassNotIn(List<String> values) {
			addCriterion("cl_icon_class not in", values, "clIconClass");
			return (Criteria) this;
		}

		public Criteria andClIconClassBetween(String value1, String value2) {
			addCriterion("cl_icon_class between", value1, value2, "clIconClass");
			return (Criteria) this;
		}

		public Criteria andClIconClassNotBetween(String value1, String value2) {
			addCriterion("cl_icon_class not between", value1, value2, "clIconClass");
			return (Criteria) this;
		}

		public Criteria andClOrderIsNull() {
			addCriterion("cl_order is null");
			return (Criteria) this;
		}

		public Criteria andClOrderIsNotNull() {
			addCriterion("cl_order is not null");
			return (Criteria) this;
		}

		public Criteria andClOrderEqualTo(Short value) {
			addCriterion("cl_order =", value, "clOrder");
			return (Criteria) this;
		}

		public Criteria andClOrderNotEqualTo(Short value) {
			addCriterion("cl_order <>", value, "clOrder");
			return (Criteria) this;
		}

		public Criteria andClOrderGreaterThan(Short value) {
			addCriterion("cl_order >", value, "clOrder");
			return (Criteria) this;
		}

		public Criteria andClOrderGreaterThanOrEqualTo(Short value) {
			addCriterion("cl_order >=", value, "clOrder");
			return (Criteria) this;
		}

		public Criteria andClOrderLessThan(Short value) {
			addCriterion("cl_order <", value, "clOrder");
			return (Criteria) this;
		}

		public Criteria andClOrderLessThanOrEqualTo(Short value) {
			addCriterion("cl_order <=", value, "clOrder");
			return (Criteria) this;
		}

		public Criteria andClOrderIn(List<Short> values) {
			addCriterion("cl_order in", values, "clOrder");
			return (Criteria) this;
		}

		public Criteria andClOrderNotIn(List<Short> values) {
			addCriterion("cl_order not in", values, "clOrder");
			return (Criteria) this;
		}

		public Criteria andClOrderBetween(Short value1, Short value2) {
			addCriterion("cl_order between", value1, value2, "clOrder");
			return (Criteria) this;
		}

		public Criteria andClOrderNotBetween(Short value1, Short value2) {
			addCriterion("cl_order not between", value1, value2, "clOrder");
			return (Criteria) this;
		}

		public Criteria andClIsMenuIsNull() {
			addCriterion("cl_is_menu is null");
			return (Criteria) this;
		}

		public Criteria andClIsMenuIsNotNull() {
			addCriterion("cl_is_menu is not null");
			return (Criteria) this;
		}

		public Criteria andClIsMenuEqualTo(Short value) {
			addCriterion("cl_is_menu =", value, "clIsMenu");
			return (Criteria) this;
		}

		public Criteria andClIsMenuNotEqualTo(Short value) {
			addCriterion("cl_is_menu <>", value, "clIsMenu");
			return (Criteria) this;
		}

		public Criteria andClIsMenuGreaterThan(Short value) {
			addCriterion("cl_is_menu >", value, "clIsMenu");
			return (Criteria) this;
		}

		public Criteria andClIsMenuGreaterThanOrEqualTo(Short value) {
			addCriterion("cl_is_menu >=", value, "clIsMenu");
			return (Criteria) this;
		}

		public Criteria andClIsMenuLessThan(Short value) {
			addCriterion("cl_is_menu <", value, "clIsMenu");
			return (Criteria) this;
		}

		public Criteria andClIsMenuLessThanOrEqualTo(Short value) {
			addCriterion("cl_is_menu <=", value, "clIsMenu");
			return (Criteria) this;
		}

		public Criteria andClIsMenuIn(List<Short> values) {
			addCriterion("cl_is_menu in", values, "clIsMenu");
			return (Criteria) this;
		}

		public Criteria andClIsMenuNotIn(List<Short> values) {
			addCriterion("cl_is_menu not in", values, "clIsMenu");
			return (Criteria) this;
		}

		public Criteria andClIsMenuBetween(Short value1, Short value2) {
			addCriterion("cl_is_menu between", value1, value2, "clIsMenu");
			return (Criteria) this;
		}

		public Criteria andClIsMenuNotBetween(Short value1, Short value2) {
			addCriterion("cl_is_menu not between", value1, value2, "clIsMenu");
			return (Criteria) this;
		}

		public Criteria andClOpenTypeIsNull() {
			addCriterion("cl_open_type is null");
			return (Criteria) this;
		}

		public Criteria andClOpenTypeIsNotNull() {
			addCriterion("cl_open_type is not null");
			return (Criteria) this;
		}

		public Criteria andClOpenTypeEqualTo(Short value) {
			addCriterion("cl_open_type =", value, "clOpenType");
			return (Criteria) this;
		}

		public Criteria andClOpenTypeNotEqualTo(Short value) {
			addCriterion("cl_open_type <>", value, "clOpenType");
			return (Criteria) this;
		}

		public Criteria andClOpenTypeGreaterThan(Short value) {
			addCriterion("cl_open_type >", value, "clOpenType");
			return (Criteria) this;
		}

		public Criteria andClOpenTypeGreaterThanOrEqualTo(Short value) {
			addCriterion("cl_open_type >=", value, "clOpenType");
			return (Criteria) this;
		}

		public Criteria andClOpenTypeLessThan(Short value) {
			addCriterion("cl_open_type <", value, "clOpenType");
			return (Criteria) this;
		}

		public Criteria andClOpenTypeLessThanOrEqualTo(Short value) {
			addCriterion("cl_open_type <=", value, "clOpenType");
			return (Criteria) this;
		}

		public Criteria andClOpenTypeIn(List<Short> values) {
			addCriterion("cl_open_type in", values, "clOpenType");
			return (Criteria) this;
		}

		public Criteria andClOpenTypeNotIn(List<Short> values) {
			addCriterion("cl_open_type not in", values, "clOpenType");
			return (Criteria) this;
		}

		public Criteria andClOpenTypeBetween(Short value1, Short value2) {
			addCriterion("cl_open_type between", value1, value2, "clOpenType");
			return (Criteria) this;
		}

		public Criteria andClOpenTypeNotBetween(Short value1, Short value2) {
			addCriterion("cl_open_type not between", value1, value2, "clOpenType");
			return (Criteria) this;
		}

		public Criteria andClHeightIsNull() {
			addCriterion("cl_height is null");
			return (Criteria) this;
		}

		public Criteria andClHeightIsNotNull() {
			addCriterion("cl_height is not null");
			return (Criteria) this;
		}

		public Criteria andClHeightEqualTo(Integer value) {
			addCriterion("cl_height =", value, "clHeight");
			return (Criteria) this;
		}

		public Criteria andClHeightNotEqualTo(Integer value) {
			addCriterion("cl_height <>", value, "clHeight");
			return (Criteria) this;
		}

		public Criteria andClHeightGreaterThan(Integer value) {
			addCriterion("cl_height >", value, "clHeight");
			return (Criteria) this;
		}

		public Criteria andClHeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("cl_height >=", value, "clHeight");
			return (Criteria) this;
		}

		public Criteria andClHeightLessThan(Integer value) {
			addCriterion("cl_height <", value, "clHeight");
			return (Criteria) this;
		}

		public Criteria andClHeightLessThanOrEqualTo(Integer value) {
			addCriterion("cl_height <=", value, "clHeight");
			return (Criteria) this;
		}

		public Criteria andClHeightIn(List<Integer> values) {
			addCriterion("cl_height in", values, "clHeight");
			return (Criteria) this;
		}

		public Criteria andClHeightNotIn(List<Integer> values) {
			addCriterion("cl_height not in", values, "clHeight");
			return (Criteria) this;
		}

		public Criteria andClHeightBetween(Integer value1, Integer value2) {
			addCriterion("cl_height between", value1, value2, "clHeight");
			return (Criteria) this;
		}

		public Criteria andClHeightNotBetween(Integer value1, Integer value2) {
			addCriterion("cl_height not between", value1, value2, "clHeight");
			return (Criteria) this;
		}

		public Criteria andClWidthIsNull() {
			addCriterion("cl_width is null");
			return (Criteria) this;
		}

		public Criteria andClWidthIsNotNull() {
			addCriterion("cl_width is not null");
			return (Criteria) this;
		}

		public Criteria andClWidthEqualTo(Integer value) {
			addCriterion("cl_width =", value, "clWidth");
			return (Criteria) this;
		}

		public Criteria andClWidthNotEqualTo(Integer value) {
			addCriterion("cl_width <>", value, "clWidth");
			return (Criteria) this;
		}

		public Criteria andClWidthGreaterThan(Integer value) {
			addCriterion("cl_width >", value, "clWidth");
			return (Criteria) this;
		}

		public Criteria andClWidthGreaterThanOrEqualTo(Integer value) {
			addCriterion("cl_width >=", value, "clWidth");
			return (Criteria) this;
		}

		public Criteria andClWidthLessThan(Integer value) {
			addCriterion("cl_width <", value, "clWidth");
			return (Criteria) this;
		}

		public Criteria andClWidthLessThanOrEqualTo(Integer value) {
			addCriterion("cl_width <=", value, "clWidth");
			return (Criteria) this;
		}

		public Criteria andClWidthIn(List<Integer> values) {
			addCriterion("cl_width in", values, "clWidth");
			return (Criteria) this;
		}

		public Criteria andClWidthNotIn(List<Integer> values) {
			addCriterion("cl_width not in", values, "clWidth");
			return (Criteria) this;
		}

		public Criteria andClWidthBetween(Integer value1, Integer value2) {
			addCriterion("cl_width between", value1, value2, "clWidth");
			return (Criteria) this;
		}

		public Criteria andClWidthNotBetween(Integer value1, Integer value2) {
			addCriterion("cl_width not between", value1, value2, "clWidth");
			return (Criteria) this;
		}

		public Criteria andClIsReportIsNull() {
			addCriterion("cl_is_report is null");
			return (Criteria) this;
		}

		public Criteria andClIsReportIsNotNull() {
			addCriterion("cl_is_report is not null");
			return (Criteria) this;
		}

		public Criteria andClIsReportEqualTo(Short value) {
			addCriterion("cl_is_report =", value, "clIsReport");
			return (Criteria) this;
		}

		public Criteria andClIsReportNotEqualTo(Short value) {
			addCriterion("cl_is_report <>", value, "clIsReport");
			return (Criteria) this;
		}

		public Criteria andClIsReportGreaterThan(Short value) {
			addCriterion("cl_is_report >", value, "clIsReport");
			return (Criteria) this;
		}

		public Criteria andClIsReportGreaterThanOrEqualTo(Short value) {
			addCriterion("cl_is_report >=", value, "clIsReport");
			return (Criteria) this;
		}

		public Criteria andClIsReportLessThan(Short value) {
			addCriterion("cl_is_report <", value, "clIsReport");
			return (Criteria) this;
		}

		public Criteria andClIsReportLessThanOrEqualTo(Short value) {
			addCriterion("cl_is_report <=", value, "clIsReport");
			return (Criteria) this;
		}

		public Criteria andClIsReportIn(List<Short> values) {
			addCriterion("cl_is_report in", values, "clIsReport");
			return (Criteria) this;
		}

		public Criteria andClIsReportNotIn(List<Short> values) {
			addCriterion("cl_is_report not in", values, "clIsReport");
			return (Criteria) this;
		}

		public Criteria andClIsReportBetween(Short value1, Short value2) {
			addCriterion("cl_is_report between", value1, value2, "clIsReport");
			return (Criteria) this;
		}

		public Criteria andClIsReportNotBetween(Short value1, Short value2) {
			addCriterion("cl_is_report not between", value1, value2, "clIsReport");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table perms.perms_t_permission
	 * @mbggenerated  Tue Aug 22 13:54:29 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table perms.perms_t_permission
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 30 11:00:16 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}