package com.sstc.hmis.permission.dbaccess.data;

import java.util.Date;

public class PermsTPwdQuestion {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_pwd_question.cl_id
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	private String clId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_pwd_question.cl_blockup
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	private Short clBlockup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_pwd_question.cl_question
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	private String clQuestion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_pwd_question.cl_grp_id
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	private String clGrpId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_pwd_question.cl_hotel_id
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	private String clHotelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_pwd_question.cl_create_time
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	private Date clCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_pwd_question.cl_create_by
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	private String clCreateBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_pwd_question.cl_modify_time
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	private Date clModifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column perms.perms_t_pwd_question.cl_modify_by
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	private String clModifyBy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_pwd_question.cl_id
	 * @return  the value of perms.perms_t_pwd_question.cl_id
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public String getClId() {
		return clId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_pwd_question.cl_id
	 * @param clId  the value for perms.perms_t_pwd_question.cl_id
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public void setClId(String clId) {
		this.clId = clId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_pwd_question.cl_blockup
	 * @return  the value of perms.perms_t_pwd_question.cl_blockup
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public Short getClBlockup() {
		return clBlockup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_pwd_question.cl_blockup
	 * @param clBlockup  the value for perms.perms_t_pwd_question.cl_blockup
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public void setClBlockup(Short clBlockup) {
		this.clBlockup = clBlockup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_pwd_question.cl_question
	 * @return  the value of perms.perms_t_pwd_question.cl_question
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public String getClQuestion() {
		return clQuestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_pwd_question.cl_question
	 * @param clQuestion  the value for perms.perms_t_pwd_question.cl_question
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public void setClQuestion(String clQuestion) {
		this.clQuestion = clQuestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_pwd_question.cl_grp_id
	 * @return  the value of perms.perms_t_pwd_question.cl_grp_id
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public String getClGrpId() {
		return clGrpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_pwd_question.cl_grp_id
	 * @param clGrpId  the value for perms.perms_t_pwd_question.cl_grp_id
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public void setClGrpId(String clGrpId) {
		this.clGrpId = clGrpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_pwd_question.cl_hotel_id
	 * @return  the value of perms.perms_t_pwd_question.cl_hotel_id
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public String getClHotelId() {
		return clHotelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_pwd_question.cl_hotel_id
	 * @param clHotelId  the value for perms.perms_t_pwd_question.cl_hotel_id
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public void setClHotelId(String clHotelId) {
		this.clHotelId = clHotelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_pwd_question.cl_create_time
	 * @return  the value of perms.perms_t_pwd_question.cl_create_time
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public Date getClCreateTime() {
		return clCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_pwd_question.cl_create_time
	 * @param clCreateTime  the value for perms.perms_t_pwd_question.cl_create_time
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public void setClCreateTime(Date clCreateTime) {
		this.clCreateTime = clCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_pwd_question.cl_create_by
	 * @return  the value of perms.perms_t_pwd_question.cl_create_by
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public String getClCreateBy() {
		return clCreateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_pwd_question.cl_create_by
	 * @param clCreateBy  the value for perms.perms_t_pwd_question.cl_create_by
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public void setClCreateBy(String clCreateBy) {
		this.clCreateBy = clCreateBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_pwd_question.cl_modify_time
	 * @return  the value of perms.perms_t_pwd_question.cl_modify_time
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public Date getClModifyTime() {
		return clModifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_pwd_question.cl_modify_time
	 * @param clModifyTime  the value for perms.perms_t_pwd_question.cl_modify_time
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public void setClModifyTime(Date clModifyTime) {
		this.clModifyTime = clModifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column perms.perms_t_pwd_question.cl_modify_by
	 * @return  the value of perms.perms_t_pwd_question.cl_modify_by
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public String getClModifyBy() {
		return clModifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column perms.perms_t_pwd_question.cl_modify_by
	 * @param clModifyBy  the value for perms.perms_t_pwd_question.cl_modify_by
	 * @mbggenerated  Fri Mar 31 19:04:40 CST 2017
	 */
	public void setClModifyBy(String clModifyBy) {
		this.clModifyBy = clModifyBy;
	}
}