package com.sstc.hmis.permission.dbaccess.data;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TApkVersionDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    public TApkVersionDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClIdIsNull() {
            addCriterion("cl_id is null");
            return (Criteria) this;
        }

        public Criteria andClIdIsNotNull() {
            addCriterion("cl_id is not null");
            return (Criteria) this;
        }

        public Criteria andClIdEqualTo(String value) {
            addCriterion("cl_id =", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotEqualTo(String value) {
            addCriterion("cl_id <>", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdGreaterThan(String value) {
            addCriterion("cl_id >", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdGreaterThanOrEqualTo(String value) {
            addCriterion("cl_id >=", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdLessThan(String value) {
            addCriterion("cl_id <", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdLessThanOrEqualTo(String value) {
            addCriterion("cl_id <=", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdLike(String value) {
            addCriterion("cl_id like", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotLike(String value) {
            addCriterion("cl_id not like", value, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdIn(List<String> values) {
            addCriterion("cl_id in", values, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotIn(List<String> values) {
            addCriterion("cl_id not in", values, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdBetween(String value1, String value2) {
            addCriterion("cl_id between", value1, value2, "clId");
            return (Criteria) this;
        }

        public Criteria andClIdNotBetween(String value1, String value2) {
            addCriterion("cl_id not between", value1, value2, "clId");
            return (Criteria) this;
        }

        public Criteria andClNameIsNull() {
            addCriterion("cl_name is null");
            return (Criteria) this;
        }

        public Criteria andClNameIsNotNull() {
            addCriterion("cl_name is not null");
            return (Criteria) this;
        }

        public Criteria andClNameEqualTo(String value) {
            addCriterion("cl_name =", value, "clName");
            return (Criteria) this;
        }

        public Criteria andClNameNotEqualTo(String value) {
            addCriterion("cl_name <>", value, "clName");
            return (Criteria) this;
        }

        public Criteria andClNameGreaterThan(String value) {
            addCriterion("cl_name >", value, "clName");
            return (Criteria) this;
        }

        public Criteria andClNameGreaterThanOrEqualTo(String value) {
            addCriterion("cl_name >=", value, "clName");
            return (Criteria) this;
        }

        public Criteria andClNameLessThan(String value) {
            addCriterion("cl_name <", value, "clName");
            return (Criteria) this;
        }

        public Criteria andClNameLessThanOrEqualTo(String value) {
            addCriterion("cl_name <=", value, "clName");
            return (Criteria) this;
        }

        public Criteria andClNameLike(String value) {
            addCriterion("cl_name like", value, "clName");
            return (Criteria) this;
        }

        public Criteria andClNameNotLike(String value) {
            addCriterion("cl_name not like", value, "clName");
            return (Criteria) this;
        }

        public Criteria andClNameIn(List<String> values) {
            addCriterion("cl_name in", values, "clName");
            return (Criteria) this;
        }

        public Criteria andClNameNotIn(List<String> values) {
            addCriterion("cl_name not in", values, "clName");
            return (Criteria) this;
        }

        public Criteria andClNameBetween(String value1, String value2) {
            addCriterion("cl_name between", value1, value2, "clName");
            return (Criteria) this;
        }

        public Criteria andClNameNotBetween(String value1, String value2) {
            addCriterion("cl_name not between", value1, value2, "clName");
            return (Criteria) this;
        }

        public Criteria andClVersionIsNull() {
            addCriterion("cl_version is null");
            return (Criteria) this;
        }

        public Criteria andClVersionIsNotNull() {
            addCriterion("cl_version is not null");
            return (Criteria) this;
        }

        public Criteria andClVersionEqualTo(String value) {
            addCriterion("cl_version =", value, "clVersion");
            return (Criteria) this;
        }

        public Criteria andClVersionNotEqualTo(String value) {
            addCriterion("cl_version <>", value, "clVersion");
            return (Criteria) this;
        }

        public Criteria andClVersionGreaterThan(String value) {
            addCriterion("cl_version >", value, "clVersion");
            return (Criteria) this;
        }

        public Criteria andClVersionGreaterThanOrEqualTo(String value) {
            addCriterion("cl_version >=", value, "clVersion");
            return (Criteria) this;
        }

        public Criteria andClVersionLessThan(String value) {
            addCriterion("cl_version <", value, "clVersion");
            return (Criteria) this;
        }

        public Criteria andClVersionLessThanOrEqualTo(String value) {
            addCriterion("cl_version <=", value, "clVersion");
            return (Criteria) this;
        }

        public Criteria andClVersionLike(String value) {
            addCriterion("cl_version like", value, "clVersion");
            return (Criteria) this;
        }

        public Criteria andClVersionNotLike(String value) {
            addCriterion("cl_version not like", value, "clVersion");
            return (Criteria) this;
        }

        public Criteria andClVersionIn(List<String> values) {
            addCriterion("cl_version in", values, "clVersion");
            return (Criteria) this;
        }

        public Criteria andClVersionNotIn(List<String> values) {
            addCriterion("cl_version not in", values, "clVersion");
            return (Criteria) this;
        }

        public Criteria andClVersionBetween(String value1, String value2) {
            addCriterion("cl_version between", value1, value2, "clVersion");
            return (Criteria) this;
        }

        public Criteria andClVersionNotBetween(String value1, String value2) {
            addCriterion("cl_version not between", value1, value2, "clVersion");
            return (Criteria) this;
        }

        public Criteria andClUrlIsNull() {
            addCriterion("cl_url is null");
            return (Criteria) this;
        }

        public Criteria andClUrlIsNotNull() {
            addCriterion("cl_url is not null");
            return (Criteria) this;
        }

        public Criteria andClUrlEqualTo(String value) {
            addCriterion("cl_url =", value, "clUrl");
            return (Criteria) this;
        }

        public Criteria andClUrlNotEqualTo(String value) {
            addCriterion("cl_url <>", value, "clUrl");
            return (Criteria) this;
        }

        public Criteria andClUrlGreaterThan(String value) {
            addCriterion("cl_url >", value, "clUrl");
            return (Criteria) this;
        }

        public Criteria andClUrlGreaterThanOrEqualTo(String value) {
            addCriterion("cl_url >=", value, "clUrl");
            return (Criteria) this;
        }

        public Criteria andClUrlLessThan(String value) {
            addCriterion("cl_url <", value, "clUrl");
            return (Criteria) this;
        }

        public Criteria andClUrlLessThanOrEqualTo(String value) {
            addCriterion("cl_url <=", value, "clUrl");
            return (Criteria) this;
        }

        public Criteria andClUrlLike(String value) {
            addCriterion("cl_url like", value, "clUrl");
            return (Criteria) this;
        }

        public Criteria andClUrlNotLike(String value) {
            addCriterion("cl_url not like", value, "clUrl");
            return (Criteria) this;
        }

        public Criteria andClUrlIn(List<String> values) {
            addCriterion("cl_url in", values, "clUrl");
            return (Criteria) this;
        }

        public Criteria andClUrlNotIn(List<String> values) {
            addCriterion("cl_url not in", values, "clUrl");
            return (Criteria) this;
        }

        public Criteria andClUrlBetween(String value1, String value2) {
            addCriterion("cl_url between", value1, value2, "clUrl");
            return (Criteria) this;
        }

        public Criteria andClUrlNotBetween(String value1, String value2) {
            addCriterion("cl_url not between", value1, value2, "clUrl");
            return (Criteria) this;
        }

        public Criteria andClGrpIdIsNull() {
            addCriterion("cl_grp_id is null");
            return (Criteria) this;
        }

        public Criteria andClGrpIdIsNotNull() {
            addCriterion("cl_grp_id is not null");
            return (Criteria) this;
        }

        public Criteria andClGrpIdEqualTo(String value) {
            addCriterion("cl_grp_id =", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdNotEqualTo(String value) {
            addCriterion("cl_grp_id <>", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdGreaterThan(String value) {
            addCriterion("cl_grp_id >", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdGreaterThanOrEqualTo(String value) {
            addCriterion("cl_grp_id >=", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdLessThan(String value) {
            addCriterion("cl_grp_id <", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdLessThanOrEqualTo(String value) {
            addCriterion("cl_grp_id <=", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdLike(String value) {
            addCriterion("cl_grp_id like", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdNotLike(String value) {
            addCriterion("cl_grp_id not like", value, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdIn(List<String> values) {
            addCriterion("cl_grp_id in", values, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdNotIn(List<String> values) {
            addCriterion("cl_grp_id not in", values, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdBetween(String value1, String value2) {
            addCriterion("cl_grp_id between", value1, value2, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClGrpIdNotBetween(String value1, String value2) {
            addCriterion("cl_grp_id not between", value1, value2, "clGrpId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdIsNull() {
            addCriterion("cl_hotel_id is null");
            return (Criteria) this;
        }

        public Criteria andClHotelIdIsNotNull() {
            addCriterion("cl_hotel_id is not null");
            return (Criteria) this;
        }

        public Criteria andClHotelIdEqualTo(String value) {
            addCriterion("cl_hotel_id =", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdNotEqualTo(String value) {
            addCriterion("cl_hotel_id <>", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdGreaterThan(String value) {
            addCriterion("cl_hotel_id >", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdGreaterThanOrEqualTo(String value) {
            addCriterion("cl_hotel_id >=", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdLessThan(String value) {
            addCriterion("cl_hotel_id <", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdLessThanOrEqualTo(String value) {
            addCriterion("cl_hotel_id <=", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdLike(String value) {
            addCriterion("cl_hotel_id like", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdNotLike(String value) {
            addCriterion("cl_hotel_id not like", value, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdIn(List<String> values) {
            addCriterion("cl_hotel_id in", values, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdNotIn(List<String> values) {
            addCriterion("cl_hotel_id not in", values, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdBetween(String value1, String value2) {
            addCriterion("cl_hotel_id between", value1, value2, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClHotelIdNotBetween(String value1, String value2) {
            addCriterion("cl_hotel_id not between", value1, value2, "clHotelId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdIsNull() {
            addCriterion("cl_create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdIsNotNull() {
            addCriterion("cl_create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdEqualTo(String value) {
            addCriterion("cl_create_user_id =", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdNotEqualTo(String value) {
            addCriterion("cl_create_user_id <>", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdGreaterThan(String value) {
            addCriterion("cl_create_user_id >", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("cl_create_user_id >=", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdLessThan(String value) {
            addCriterion("cl_create_user_id <", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("cl_create_user_id <=", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdLike(String value) {
            addCriterion("cl_create_user_id like", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdNotLike(String value) {
            addCriterion("cl_create_user_id not like", value, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdIn(List<String> values) {
            addCriterion("cl_create_user_id in", values, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdNotIn(List<String> values) {
            addCriterion("cl_create_user_id not in", values, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdBetween(String value1, String value2) {
            addCriterion("cl_create_user_id between", value1, value2, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("cl_create_user_id not between", value1, value2, "clCreateUserId");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeIsNull() {
            addCriterion("cl_create_time is null");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeIsNotNull() {
            addCriterion("cl_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeEqualTo(Date value) {
            addCriterion("cl_create_time =", value, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeNotEqualTo(Date value) {
            addCriterion("cl_create_time <>", value, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeGreaterThan(Date value) {
            addCriterion("cl_create_time >", value, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cl_create_time >=", value, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeLessThan(Date value) {
            addCriterion("cl_create_time <", value, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("cl_create_time <=", value, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeIn(List<Date> values) {
            addCriterion("cl_create_time in", values, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeNotIn(List<Date> values) {
            addCriterion("cl_create_time not in", values, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeBetween(Date value1, Date value2) {
            addCriterion("cl_create_time between", value1, value2, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("cl_create_time not between", value1, value2, "clCreateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdIsNull() {
            addCriterion("cl_update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdIsNotNull() {
            addCriterion("cl_update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdEqualTo(String value) {
            addCriterion("cl_update_user_id =", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdNotEqualTo(String value) {
            addCriterion("cl_update_user_id <>", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdGreaterThan(String value) {
            addCriterion("cl_update_user_id >", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("cl_update_user_id >=", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdLessThan(String value) {
            addCriterion("cl_update_user_id <", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("cl_update_user_id <=", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdLike(String value) {
            addCriterion("cl_update_user_id like", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdNotLike(String value) {
            addCriterion("cl_update_user_id not like", value, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdIn(List<String> values) {
            addCriterion("cl_update_user_id in", values, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdNotIn(List<String> values) {
            addCriterion("cl_update_user_id not in", values, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdBetween(String value1, String value2) {
            addCriterion("cl_update_user_id between", value1, value2, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("cl_update_user_id not between", value1, value2, "clUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeIsNull() {
            addCriterion("cl_update_time is null");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeIsNotNull() {
            addCriterion("cl_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeEqualTo(Date value) {
            addCriterion("cl_update_time =", value, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeNotEqualTo(Date value) {
            addCriterion("cl_update_time <>", value, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeGreaterThan(Date value) {
            addCriterion("cl_update_time >", value, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cl_update_time >=", value, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeLessThan(Date value) {
            addCriterion("cl_update_time <", value, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("cl_update_time <=", value, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeIn(List<Date> values) {
            addCriterion("cl_update_time in", values, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeNotIn(List<Date> values) {
            addCriterion("cl_update_time not in", values, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("cl_update_time between", value1, value2, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("cl_update_time not between", value1, value2, "clUpdateTime");
            return (Criteria) this;
        }

        public Criteria andClLogIsNull() {
            addCriterion("cl_log is null");
            return (Criteria) this;
        }

        public Criteria andClLogIsNotNull() {
            addCriterion("cl_log is not null");
            return (Criteria) this;
        }

        public Criteria andClLogEqualTo(String value) {
            addCriterion("cl_log =", value, "clLog");
            return (Criteria) this;
        }

        public Criteria andClLogNotEqualTo(String value) {
            addCriterion("cl_log <>", value, "clLog");
            return (Criteria) this;
        }

        public Criteria andClLogGreaterThan(String value) {
            addCriterion("cl_log >", value, "clLog");
            return (Criteria) this;
        }

        public Criteria andClLogGreaterThanOrEqualTo(String value) {
            addCriterion("cl_log >=", value, "clLog");
            return (Criteria) this;
        }

        public Criteria andClLogLessThan(String value) {
            addCriterion("cl_log <", value, "clLog");
            return (Criteria) this;
        }

        public Criteria andClLogLessThanOrEqualTo(String value) {
            addCriterion("cl_log <=", value, "clLog");
            return (Criteria) this;
        }

        public Criteria andClLogLike(String value) {
            addCriterion("cl_log like", value, "clLog");
            return (Criteria) this;
        }

        public Criteria andClLogNotLike(String value) {
            addCriterion("cl_log not like", value, "clLog");
            return (Criteria) this;
        }

        public Criteria andClLogIn(List<String> values) {
            addCriterion("cl_log in", values, "clLog");
            return (Criteria) this;
        }

        public Criteria andClLogNotIn(List<String> values) {
            addCriterion("cl_log not in", values, "clLog");
            return (Criteria) this;
        }

        public Criteria andClLogBetween(String value1, String value2) {
            addCriterion("cl_log between", value1, value2, "clLog");
            return (Criteria) this;
        }

        public Criteria andClLogNotBetween(String value1, String value2) {
            addCriterion("cl_log not between", value1, value2, "clLog");
            return (Criteria) this;
        }

        public Criteria andClUpdVersionIsNull() {
            addCriterion("cl_upd_version is null");
            return (Criteria) this;
        }

        public Criteria andClUpdVersionIsNotNull() {
            addCriterion("cl_upd_version is not null");
            return (Criteria) this;
        }

        public Criteria andClUpdVersionEqualTo(String value) {
            addCriterion("cl_upd_version =", value, "clUpdVersion");
            return (Criteria) this;
        }

        public Criteria andClUpdVersionNotEqualTo(String value) {
            addCriterion("cl_upd_version <>", value, "clUpdVersion");
            return (Criteria) this;
        }

        public Criteria andClUpdVersionGreaterThan(String value) {
            addCriterion("cl_upd_version >", value, "clUpdVersion");
            return (Criteria) this;
        }

        public Criteria andClUpdVersionGreaterThanOrEqualTo(String value) {
            addCriterion("cl_upd_version >=", value, "clUpdVersion");
            return (Criteria) this;
        }

        public Criteria andClUpdVersionLessThan(String value) {
            addCriterion("cl_upd_version <", value, "clUpdVersion");
            return (Criteria) this;
        }

        public Criteria andClUpdVersionLessThanOrEqualTo(String value) {
            addCriterion("cl_upd_version <=", value, "clUpdVersion");
            return (Criteria) this;
        }

        public Criteria andClUpdVersionLike(String value) {
            addCriterion("cl_upd_version like", value, "clUpdVersion");
            return (Criteria) this;
        }

        public Criteria andClUpdVersionNotLike(String value) {
            addCriterion("cl_upd_version not like", value, "clUpdVersion");
            return (Criteria) this;
        }

        public Criteria andClUpdVersionIn(List<String> values) {
            addCriterion("cl_upd_version in", values, "clUpdVersion");
            return (Criteria) this;
        }

        public Criteria andClUpdVersionNotIn(List<String> values) {
            addCriterion("cl_upd_version not in", values, "clUpdVersion");
            return (Criteria) this;
        }

        public Criteria andClUpdVersionBetween(String value1, String value2) {
            addCriterion("cl_upd_version between", value1, value2, "clUpdVersion");
            return (Criteria) this;
        }

        public Criteria andClUpdVersionNotBetween(String value1, String value2) {
            addCriterion("cl_upd_version not between", value1, value2, "clUpdVersion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 14 11:01:32 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table perms.t_apk_version_detail
     *
     * @mbggenerated Thu Sep 14 11:01:32 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}