package com.sstc.hmis.permission.dbaccess.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.sstc.hmis.permission.dbaccess.data.PermsTGroupHotel;
import com.sstc.hmis.permission.dbaccess.data.PermsTGroupHotelExample;
import com.sstc.hmis.permission.dbaccess.data.PermsTStaffHotel;
import com.sstc.hmis.permission.dbaccess.data.TContactsInfo;
import com.sstc.hmis.permission.dbaccess.data.TGroupInfo;
import com.sstc.hmis.permission.dbaccess.data.TLinkHotelInfo;
import com.sstc.hmis.permission.dbaccess.data.TLinkmanDeptInfo;
import com.sstc.hmis.permission.dbaccess.data.TLinkmanInfo;
import com.sstc.hmis.permission.dbaccess.data.TWorkGroupInfo;
import com.sstc.hmis.permission.dbaccess.data.domain.Hotel;
@Mapper
public interface PermsTGroupHotelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table perms.perms_t_group_hotel
	 * 
	 * @mbggenerated Tue Apr 11 15:03:03 CST 2017
	 */
	int countByExample(PermsTGroupHotelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table perms.perms_t_group_hotel
	 * 
	 * @mbggenerated Tue Apr 11 15:03:03 CST 2017
	 */
	int deleteByExample(PermsTGroupHotelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table perms.perms_t_group_hotel
	 * 
	 * @mbggenerated Tue Apr 11 15:03:03 CST 2017
	 */
	int deleteByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table perms.perms_t_group_hotel
	 * 
	 * @mbggenerated Tue Apr 11 15:03:03 CST 2017
	 */
	int insert(PermsTGroupHotel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table perms.perms_t_group_hotel
	 * 
	 * @mbggenerated Tue Apr 11 15:03:03 CST 2017
	 */
	int insertSelective(PermsTGroupHotel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table perms.perms_t_group_hotel
	 * 
	 * @mbggenerated Tue Apr 11 15:03:03 CST 2017
	 */
	List<PermsTGroupHotel> selectByExample(PermsTGroupHotelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table perms.perms_t_group_hotel
	 * 
	 * @mbggenerated Tue Apr 11 15:03:03 CST 2017
	 */
	PermsTGroupHotel selectByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table perms.perms_t_group_hotel
	 * 
	 * @mbggenerated Tue Apr 11 15:03:03 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PermsTGroupHotel record,
	        @Param("example") PermsTGroupHotelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table perms.perms_t_group_hotel
	 * 
	 * @mbggenerated Tue Apr 11 15:03:03 CST 2017
	 */
	int updateByExample(@Param("record") PermsTGroupHotel record, @Param("example") PermsTGroupHotelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table perms.perms_t_group_hotel
	 * 
	 * @mbggenerated Tue Apr 11 15:03:03 CST 2017
	 */
	int updateByPrimaryKeySelective(PermsTGroupHotel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table perms.perms_t_group_hotel
	 * 
	 * @mbggenerated Tue Apr 11 15:03:03 CST 2017
	 */
	int updateByPrimaryKey(PermsTGroupHotel record);

	List<Hotel> selectAll(PermsTGroupHotel hotelQuery);

	List<PermsTGroupHotel> selectBySelective(@Param("hotel") PermsTGroupHotel record);
 
	int updateStatusByPrimaryKeys(@Param("ids") List<String> ids, @Param("status") int status, @Param("blockup")Short blockup);

	List<PermsTGroupHotel> findStaffHotelByStaffId(PermsTStaffHotel permsTStaffHotel);
	
	List<TGroupInfo> getGroupInfoByHotelId(Map<String, Object> paramMap);
	
	/**
	 * 依据部门ID获取人员列表
	 * @param paramMap 参数Map
	 * @return 查询结果
	 */
	List<String> getUserIdsByDeptId(Map<String, Object> paramMap);
	
	/**
	 * 获取当前用户所在的工作圈
	 * @param paramMap 参数Map
	 * @return 查询结果
	 */
	List<TWorkGroupInfo> getWorkGroupList(Map<String, Object> paramMap);
	
	List<TLinkmanInfo> getUserListByWorkGroupId(Map<String, Object> paramMap);
	
	List<TLinkmanInfo> getAllUser(Map<String, Object> paramMap);
	
	List<TLinkHotelInfo> getLinkmanHotelInfoList(Map<String, Object> paramMap);
	
	/**
	 * 获取酒店下部门职位信息列表
	 * @param paramMap 参数Map
	 */
	List<TLinkmanDeptInfo> getLinkmanDeptInfoList(Map<String, Object> paramMap);
	
	/**
	 * 过滤联系人列表
	 * @param paramMap 参数Map
	 */
	List<TContactsInfo> getContactsInfoList(Map<String, Object> paramMap);
	
	/**
	 * 获取所有有效酒店ID
	 */
	List<String> getAllHotel();
}