package com.sstc.hmis.permission.dbaccess.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.sstc.hmis.permission.dbaccess.data.PermsTDepartment;
import com.sstc.hmis.permission.dbaccess.data.PermsTDepartmentExample;

@Mapper
public interface PermsTDepartmentMapper
{
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * perms.perms_t_department
     * 
     * @mbggenerated Wed Apr 12 15:37:40 CST 2017
     */
    int countByExample(PermsTDepartmentExample example);
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * perms.perms_t_department
     * 
     * @mbggenerated Wed Apr 12 15:37:40 CST 2017
     */
    int deleteByExample(PermsTDepartmentExample example);
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * perms.perms_t_department
     * 
     * @mbggenerated Wed Apr 12 15:37:40 CST 2017
     */
    int deleteByPrimaryKey(String clId);
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * perms.perms_t_department
     * 
     * @mbggenerated Wed Apr 12 15:37:40 CST 2017
     */
    int insert(PermsTDepartment record);
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * perms.perms_t_department
     * 
     * @mbggenerated Wed Apr 12 15:37:40 CST 2017
     */
    int insertSelective(PermsTDepartment record);
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * perms.perms_t_department
     * 
     * @mbggenerated Wed Apr 12 15:37:40 CST 2017
     */
    List<PermsTDepartment> selectByExample(PermsTDepartmentExample example);
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * perms.perms_t_department
     * 
     * @mbggenerated Wed Apr 12 15:37:40 CST 2017
     */
    PermsTDepartment selectByPrimaryKey(String clId);
    
    List<PermsTDepartment> findDeptByPostId(String clPostId);
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * perms.perms_t_department
     * 
     * @mbggenerated Wed Apr 12 15:37:40 CST 2017
     */
    int updateByExampleSelective(@Param("record") PermsTDepartment record,
        @Param("example") PermsTDepartmentExample example);
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * perms.perms_t_department
     * 
     * @mbggenerated Wed Apr 12 15:37:40 CST 2017
     */
    int updateByExample(@Param("record") PermsTDepartment record, @Param("example") PermsTDepartmentExample example);
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * perms.perms_t_department
     * 
     * @mbggenerated Wed Apr 12 15:37:40 CST 2017
     */
    int updateByPrimaryKeySelective(PermsTDepartment record);
    
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * perms.perms_t_department
     * 
     * @mbggenerated Wed Apr 12 15:37:40 CST 2017
     */
    int updateByPrimaryKey(PermsTDepartment record);
    
    List<PermsTDepartment> selectBySelective(@Param("department") PermsTDepartment record);
    
    int deleteByPrimaryKeys(Map<String, Object> condition);
    
    /*
     * 查询部门机构信息；
     */
    List<String> selDeparts(@Param("dpartId") String dpartId);
    
    /**
     * 查询部门及子部门下的员工数量
     * 
     * @param condition
     * @return
     */
    int countDptStaff(Map<String, Object> condition);
    
    /**
     * 查询部门及子部门下的职位数量
     * 
     * @param condition
     * @return
     */
    int countDptPost(Map<String, Object> condition);
    
    /**
     * @param condition
     */
    void deleteDptPost(Map<String, Object> condition);
    
    /**
     * @param condition
     */
    void deletePostByDptId(Map<String, Object> condition);
    
    List<PermsTDepartment> findDeptNameByDeptId(String clHotelId);
    
    List<PermsTDepartment> findChildDeptList(Map<String, Object> paramMap);
}