package com.sstc.hmis.permission.dbaccess.dao;

import com.sstc.hmis.permission.dbaccess.data.PermsTStaffMenu;
import com.sstc.hmis.permission.dbaccess.data.PermsTStaffMenuExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PermsTStaffMenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_menu
	 * @mbggenerated  Wed Aug 23 13:13:39 CST 2017
	 */
	int countByExample(PermsTStaffMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_menu
	 * @mbggenerated  Wed Aug 23 13:13:39 CST 2017
	 */
	int deleteByExample(PermsTStaffMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_menu
	 * @mbggenerated  Wed Aug 23 13:13:39 CST 2017
	 */
	int deleteByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_menu
	 * @mbggenerated  Wed Aug 23 13:13:39 CST 2017
	 */
	int insert(PermsTStaffMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_menu
	 * @mbggenerated  Wed Aug 23 13:13:39 CST 2017
	 */
	int insertSelective(PermsTStaffMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_menu
	 * @mbggenerated  Wed Aug 23 13:13:39 CST 2017
	 */
	List<PermsTStaffMenu> selectByExample(PermsTStaffMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_menu
	 * @mbggenerated  Wed Aug 23 13:13:39 CST 2017
	 */
	PermsTStaffMenu selectByPrimaryKey(String clId);
	
	PermsTStaffMenu selectOneByExample(PermsTStaffMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_menu
	 * @mbggenerated  Wed Aug 23 13:13:39 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PermsTStaffMenu record,
			@Param("example") PermsTStaffMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_menu
	 * @mbggenerated  Wed Aug 23 13:13:39 CST 2017
	 */
	int updateByExample(@Param("record") PermsTStaffMenu record, @Param("example") PermsTStaffMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_menu
	 * @mbggenerated  Wed Aug 23 13:13:39 CST 2017
	 */
	int updateByPrimaryKeySelective(PermsTStaffMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_menu
	 * @mbggenerated  Wed Aug 23 13:13:39 CST 2017
	 */
	int updateByPrimaryKey(PermsTStaffMenu record);
}