package com.sstc.hmis.permission.dbaccess.dao;

import com.sstc.hmis.permission.dbaccess.data.PermsTDptPost;
import com.sstc.hmis.permission.dbaccess.data.PermsTDptPostExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PermsTDptPostMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_post
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int countByExample(PermsTDptPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_post
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int deleteByExample(PermsTDptPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_post
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int deleteByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_post
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int insert(PermsTDptPost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_post
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int insertSelective(PermsTDptPost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_post
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	List<PermsTDptPost> selectByExample(PermsTDptPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_post
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	PermsTDptPost selectByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_post
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PermsTDptPost record, @Param("example") PermsTDptPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_post
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByExample(@Param("record") PermsTDptPost record, @Param("example") PermsTDptPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_post
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByPrimaryKeySelective(PermsTDptPost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_post
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByPrimaryKey(PermsTDptPost record);
}