package com.sstc.hmis.permission.dbaccess.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.sstc.hmis.permission.dbaccess.data.PermsTStaffHotel;
import com.sstc.hmis.permission.dbaccess.data.PermsTStaffHotelExample;
@Mapper
public interface PermsTStaffHotelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_hotel
	 * @mbggenerated  Thu Apr 20 17:27:20 CST 2017
	 */
	int countByExample(PermsTStaffHotelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_hotel
	 * @mbggenerated  Thu Apr 20 17:27:20 CST 2017
	 */
	int deleteByExample(PermsTStaffHotelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_hotel
	 * @mbggenerated  Thu Apr 20 17:27:20 CST 2017
	 */
	int deleteByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_hotel
	 * @mbggenerated  Thu Apr 20 17:27:20 CST 2017
	 */
	int insert(PermsTStaffHotel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_hotel
	 * @mbggenerated  Thu Apr 20 17:27:20 CST 2017
	 */
	int insertSelective(PermsTStaffHotel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_hotel
	 * @mbggenerated  Thu Apr 20 17:27:20 CST 2017
	 */
	List<PermsTStaffHotel> selectByExample(PermsTStaffHotelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_hotel
	 * @mbggenerated  Thu Apr 20 17:27:20 CST 2017
	 */
	PermsTStaffHotel selectByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_hotel
	 * @mbggenerated  Thu Apr 20 17:27:20 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PermsTStaffHotel record,
			@Param("example") PermsTStaffHotelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_hotel
	 * @mbggenerated  Thu Apr 20 17:27:20 CST 2017
	 */
	int updateByExample(@Param("record") PermsTStaffHotel record, @Param("example") PermsTStaffHotelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_hotel
	 * @mbggenerated  Thu Apr 20 17:27:20 CST 2017
	 */
	int updateByPrimaryKeySelective(PermsTStaffHotel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_hotel
	 * @mbggenerated  Thu Apr 20 17:27:20 CST 2017
	 */
	int updateByPrimaryKey(PermsTStaffHotel record);

	/**
	 * 批量更新登录策略
	 * @param staffHotel
	 * @param condition
	 * @return
	 */
	int batchUpdateStratery(@Param("staffHotel")PermsTStaffHotel staffHotel, @Param("condition")Map<String, Object> condition);
}