package com.sstc.hmis.permission.dbaccess.dao;

import com.sstc.hmis.permission.dbaccess.data.PermsTStaffTeam;
import com.sstc.hmis.permission.dbaccess.data.PermsTStaffTeamExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PermsTStaffTeamMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_team
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int countByExample(PermsTStaffTeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_team
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int deleteByExample(PermsTStaffTeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_team
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int deleteByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_team
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int insert(PermsTStaffTeam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_team
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int insertSelective(PermsTStaffTeam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_team
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	List<PermsTStaffTeam> selectByExample(PermsTStaffTeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_team
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	PermsTStaffTeam selectByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_team
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PermsTStaffTeam record,
			@Param("example") PermsTStaffTeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_team
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByExample(@Param("record") PermsTStaffTeam record, @Param("example") PermsTStaffTeamExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_team
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByPrimaryKeySelective(PermsTStaffTeam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_staff_team
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByPrimaryKey(PermsTStaffTeam record);
	
	// add by 刘溶容 2018/01/10 for 环信 begin
	/**
	 * 获取当前该工作圈下所有用户列表
	 */
	List<String> getBeforeUserIdList(Map<String, Object> paramMap);
	// add by 刘溶容 2018/01/10 for 环信 end
}