package com.sstc.hmis.permission.dbaccess.dao;

import com.sstc.hmis.permission.dbaccess.data.PermsTDptStaff;
import com.sstc.hmis.permission.dbaccess.data.PermsTDptStaffExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PermsTDptStaffMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_staff
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int countByExample(PermsTDptStaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_staff
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int deleteByExample(PermsTDptStaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_staff
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int deleteByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_staff
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int insert(PermsTDptStaff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_staff
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int insertSelective(PermsTDptStaff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_staff
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	List<PermsTDptStaff> selectByExample(PermsTDptStaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_staff
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	PermsTDptStaff selectByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_staff
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PermsTDptStaff record,
			@Param("example") PermsTDptStaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_staff
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByExample(@Param("record") PermsTDptStaff record, @Param("example") PermsTDptStaffExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_staff
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByPrimaryKeySelective(PermsTDptStaff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_dpt_staff
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByPrimaryKey(PermsTDptStaff record);
}