package com.sstc.hmis.permission.dbaccess.dao;

import com.sstc.hmis.permission.dbaccess.data.PermsTPwdQuesAnswer;
import com.sstc.hmis.permission.dbaccess.data.PermsTPwdQuesAnswerExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PermsTPwdQuesAnswerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_pwd_ques_answer
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int countByExample(PermsTPwdQuesAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_pwd_ques_answer
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int deleteByExample(PermsTPwdQuesAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_pwd_ques_answer
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int deleteByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_pwd_ques_answer
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int insert(PermsTPwdQuesAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_pwd_ques_answer
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int insertSelective(PermsTPwdQuesAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_pwd_ques_answer
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	List<PermsTPwdQuesAnswer> selectByExample(PermsTPwdQuesAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_pwd_ques_answer
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	PermsTPwdQuesAnswer selectByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_pwd_ques_answer
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PermsTPwdQuesAnswer record,
			@Param("example") PermsTPwdQuesAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_pwd_ques_answer
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByExample(@Param("record") PermsTPwdQuesAnswer record,
			@Param("example") PermsTPwdQuesAnswerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_pwd_ques_answer
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByPrimaryKeySelective(PermsTPwdQuesAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_pwd_ques_answer
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByPrimaryKey(PermsTPwdQuesAnswer record);
}