package com.sstc.hmis.permission.dbaccess.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.sstc.hmis.permission.dbaccess.data.PermsTPersonalisation;
import com.sstc.hmis.permission.dbaccess.data.PermsTPersonalisationExample;

@Mapper
public interface PermsTPersonalisationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_personalisation
     *
     * @mbggenerated Thu Apr 12 14:28:02 CST 2018
     */
    int countByExample(PermsTPersonalisationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_personalisation
     *
     * @mbggenerated Thu Apr 12 14:28:02 CST 2018
     */
    int deleteByExample(PermsTPersonalisationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_personalisation
     *
     * @mbggenerated Thu Apr 12 14:28:02 CST 2018
     */
    int deleteByPrimaryKey(String clId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_personalisation
     *
     * @mbggenerated Thu Apr 12 14:28:02 CST 2018
     */
    int insert(PermsTPersonalisation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_personalisation
     *
     * @mbggenerated Thu Apr 12 14:28:02 CST 2018
     */
    int insertSelective(PermsTPersonalisation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_personalisation
     *
     * @mbggenerated Thu Apr 12 14:28:02 CST 2018
     */
    List<PermsTPersonalisation> selectByExample(PermsTPersonalisationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_personalisation
     *
     * @mbggenerated Thu Apr 12 14:28:02 CST 2018
     */
    PermsTPersonalisation selectByPrimaryKey(String clId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_personalisation
     *
     * @mbggenerated Thu Apr 12 14:28:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") PermsTPersonalisation record, @Param("example") PermsTPersonalisationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_personalisation
     *
     * @mbggenerated Thu Apr 12 14:28:02 CST 2018
     */
    int updateByExample(@Param("record") PermsTPersonalisation record, @Param("example") PermsTPersonalisationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_personalisation
     *
     * @mbggenerated Thu Apr 12 14:28:02 CST 2018
     */
    int updateByPrimaryKeySelective(PermsTPersonalisation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_personalisation
     *
     * @mbggenerated Thu Apr 12 14:28:02 CST 2018
     */
    int updateByPrimaryKey(PermsTPersonalisation record);
    
    // 依据登录用户获取个性化设置
    List<PermsTPersonalisation> getPersonalisationListByUserId(Map<String, String> paramMap);
}