package com.sstc.hmis.permission.dbaccess.dao;

import com.sstc.hmis.permission.dbaccess.data.PermsTRolePermission;
import com.sstc.hmis.permission.dbaccess.data.PermsTRolePermissionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface PermsTRolePermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_role_permission
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int countByExample(PermsTRolePermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_role_permission
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int deleteByExample(PermsTRolePermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_role_permission
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int deleteByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_role_permission
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int insert(PermsTRolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_role_permission
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int insertSelective(PermsTRolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_role_permission
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	List<PermsTRolePermission> selectByExample(PermsTRolePermissionExample example);
	
	/**
	 * 通过角色id查询权限id列表
	 * @param roleId
	 * @return
	 */
	List<PermsTRolePermission> findPermissionIdByRoleId(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_role_permission
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	PermsTRolePermission selectByPrimaryKey(String clId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_role_permission
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PermsTRolePermission record,
			@Param("example") PermsTRolePermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_role_permission
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByExample(@Param("record") PermsTRolePermission record,
			@Param("example") PermsTRolePermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_role_permission
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByPrimaryKeySelective(PermsTRolePermission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table perms.perms_t_role_permission
	 * @mbggenerated  Wed Apr 05 13:58:26 CST 2017
	 */
	int updateByPrimaryKey(PermsTRolePermission record);

	/**
	 * @param 插入行数
	 */
	int batchInsertSelective(List<PermsTRolePermission> newAddPermission);
}