package com.sstc.hmis.permission.dbaccess.dao;

import com.sstc.hmis.permission.dbaccess.data.PermGrpMember;
import com.sstc.hmis.permission.dbaccess.data.PermsTWorkTeam;
import com.sstc.hmis.permission.dbaccess.data.PermsTWorkTeamExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PermsTWorkTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_work_team
     *
     * @mbggenerated Wed Jan 10 09:49:27 CST 2018
     */
    int countByExample(PermsTWorkTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_work_team
     *
     * @mbggenerated Wed Jan 10 09:49:27 CST 2018
     */
    int deleteByExample(PermsTWorkTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_work_team
     *
     * @mbggenerated Wed Jan 10 09:49:27 CST 2018
     */
    int deleteByPrimaryKey(String clId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_work_team
     *
     * @mbggenerated Wed Jan 10 09:49:27 CST 2018
     */
    int insert(PermsTWorkTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_work_team
     *
     * @mbggenerated Wed Jan 10 09:49:27 CST 2018
     */
    int insertSelective(PermsTWorkTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_work_team
     *
     * @mbggenerated Wed Jan 10 09:49:27 CST 2018
     */
    List<PermsTWorkTeam> selectByExample(PermsTWorkTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_work_team
     *
     * @mbggenerated Wed Jan 10 09:49:27 CST 2018
     */
    PermsTWorkTeam selectByPrimaryKey(String clId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_work_team
     *
     * @mbggenerated Wed Jan 10 09:49:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") PermsTWorkTeam record, @Param("example") PermsTWorkTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_work_team
     *
     * @mbggenerated Wed Jan 10 09:49:27 CST 2018
     */
    int updateByExample(@Param("record") PermsTWorkTeam record, @Param("example") PermsTWorkTeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_work_team
     *
     * @mbggenerated Wed Jan 10 09:49:27 CST 2018
     */
    int updateByPrimaryKeySelective(PermsTWorkTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table perms.perms_t_work_team
     *
     * @mbggenerated Wed Jan 10 09:49:27 CST 2018
     */
    int updateByPrimaryKey(PermsTWorkTeam record);
    
	/*
	 * 查询圈成员信息；
	 */
//	List<PermGrpMember> selGrpMember(PermsTWorkTeam record);
	/*
	 * 根据Id查询圈成员信息；
	 */
	List<PermGrpMember> selGrpMemberInfo(@Param("items")List<String> staffIdList);
}